### ISSUE TITLE
Wrong generation when definigion is an array of objects

### ISSUE THREAD

**Issue by Vovanella95** [epam-cross-platform-lab/swagger-dart-code-generator#108]
Wrong generation when definigion is an array of objects

**Comment by PKIE** [comment]
Same issue here. Tried with 1.6.8
Sample openapi schema
[openapi.txt](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/6137520/openapi.txt)
Arra type definition is:
```
"ListCustomItem": {
  "type": "array",
  "items": {
    "$ref": "#/components/schemas/CustomItem"
  }
}
```

As a result the CustomItem is fine, but ListCustomItem generated code is empty:
```
@JsonSerializable(explicitToJson: true)
class ListCustomItem {
  ListCustomItem();

  factory ListCustomItem.fromJson(Map<String, dynamic> json) =>
      _$ListCustomItemFromJson(json);

  static const fromJsonFactory = _$ListCustomItemFromJson;
  static const toJsonFactory = _$ListCustomItemToJson;
  Map<String, dynamic> toJson() => _$ListCustomItemToJson(this);
}
```

**Comment by fryette** [comment]
As a temporary solution please use https://github.com/epam-cross-platform-lab/swagger-dart-code-generator#response-override-value-map-for-requests-generation

**Comment by PKIE** [comment]
Thank you @fryette 
Do you know if there is a way to override types for array type properties?

**Comment by PKIE** [comment]
OK, I managed to change the schema generator (probably it was buggy, and now instead creating new ListCustomItem definition it simply defines the response (or internal array) as array of type

So thanks for help, and sorry for bugging ;)
