### ISSUE TITLE
recomendations for a  ChopperClient customization

### ISSUE THREAD

**Issue by fphilip** [epam-cross-platform-lab/swagger-dart-code-generator#112]
Hello
What is the recommended way to solve the problem with the private visibility of the class generated by Chopper? may be creating an ExampleClient in the same package with parameters and interceptors?

thanks !!

`
Future main() async {

  final chopperClient = ChopperClient(
      services: [_$Example()],   **//private!!!!!!**
      converter: JsonSerializableConverter(),
      interceptors:  [
        // Auth Interceptor
            (Request request) async => applyHeader(request,
                HttpHeaders.authorizationHeader, "7tJBAO3xwIF3UhfIwMYryL2Cqo1dpQ",
            //SharedPrefs.localStorage.getString(HttpHeaders.authorizationHeader),
            override: false),
            (Response response) async {
          if (response?.statusCode == 401) {
            //SharedPrefs.localStorage.remove(HttpHeaders.authorizationHeader);
            // Navigate to some login page or just request new token
          }
          return response;
        },
      ],
      baseUrl: 'https://localhost:8080/api');

  final client = Example.create(chopperClient);
`

**Comment by Vovanella95** [comment]
Hi @fphilip , We will check it and implement ASAP

**Comment by Vovanella95** [comment]
Hi, @fphilip, maybe I've understand question bad, but what is problem to use next way?

...
services: [Example.create()],
...

**Comment by fphilip** [comment]
It works.. no problem, the question was about the best option.. thank's greats job
PS: the use_required_attribute_for_headers=false, is working?

**Comment by Vovanella95** [comment]
@fphilip It should work. Please let us know if no :)

At our current project we create services, no clients. 

IoC.registerSingleton<ExampleService>(ExampleService(_createChopperClient()));

_createChopperCLient method sets all interceptors and chopper client modifications
