### ISSUE TITLE
Change the default way how 'date' is serialised or add an ability to override the behavior

### ISSUE THREAD

**Issue by Pavel-Sulimau** [epam-cross-platform-lab/swagger-dart-code-generator#115]
Hello devs, firstly, I'd like to say thank you for such a cool package, good job!

I've come to you with the following suggestion for improvement: **could you please change the default behavior for how  'date' types are serialized or add a possibility to override that behavior?**

Let me give you a bit more context of what I'm talking about… 
Here is the screenshot from [the swagger specification](https://swagger.io/docs/specification/data-models/data-types/ ) showing how a string with 'date' format identifier is supposed to look like.
<img src="https://user-images.githubusercontent.com/8143332/106127545-b3c18380-616f-11eb-9b9b-fe7fc49e3684.png"  height="250">

At the moment, the current package does not adhere to this standard and will eventually generate a code snipped like this 
`'date': instance.date?.toIso8601String()`. 

`date?.toIso8601String()`, in turn, results in the "2021-01-29T00:00:00.000Z"  string being sent to the server instead of "2021-01-29" which causes issues on my current project as the server rejects such requests.

I've found a hacky way to work around this problem for the moment, but it would be great if you could implement the suggested thing. 
I suppose you might use [the approach mentioned here](https://github.com/google/json_serializable.dart/issues/133) to override the way how [json_serializable](https://pub.dev/packages/json_serializable) serializes a Dart's `DateTime` to a `string`.

P.S. 
Here are the pieces in your example which you may want to change to verify the behavior should you choose to implement it:
<img src="https://user-images.githubusercontent.com/8143332/106129384-3f87df80-6171-11eb-8fef-ce5c0b080172.png"  width="800">
<img src="https://user-images.githubusercontent.com/8143332/106129585-6f36e780-6171-11eb-80a2-7ff703b0fb6f.png"  width="800">

**Comment by Vovanella95** [comment]
Fixed in 1.6.6+2 version. I'm closing this issue.
