### ISSUE TITLE
Array is being submitted as a string with a json inside

### ISSUE THREAD

**Issue by goncalvesjoao** [epam-cross-platform-lab/swagger-dart-code-generator#133]
Guys, I'm having a weird behaviour when I declare that I accept a field 'images' in the parameters of type array of strings.
```json
{
  "type": "array",
    "items": {
      "type": "string"
    },
  "name": "images",
  "in": "formData"
}
```

The generated code, understands that is accepting an array (List) but then when it submits the POST request to the server, it sends not an array of strings but a string with and array inside.

Am I doing something wrong?

**Comment by fryette** [comment]
Hi @goncalvesjoao, as a workaround you can use chopper directly(or write just that request by yourself).
We will take a look into it and will try to fix this/next week.

Sorry for the delay.

Thanks, 
Yauhen Sampir

**Comment by fryette** [comment]
Closed, seems now it's working correctly.
