### ISSUE TITLE
Adding headers to request

### ISSUE THREAD

**Issue by Nehoko** [epam-cross-platform-lab/swagger-dart-code-generator#136]
Api that I'm using requires JSESSIONID in request's header. I Can't find any info about that at your documentation. How can I add header at requests?

**Comment by fryette** [comment]
2 Options
1. By default all headers should be generated if it available in swagger(please share if can)
2. Use [interceptors](https://github.com/lejard-h/chopper/blob/master/interceptors.md) and add headeres here

**Comment by fryette** [comment]
Feel free to open if needed

**Comment by Nehoko** [comment]
My problem was with authorization. Rest-api that I'm using requires cookie with JSESSIONID. Without it api responses with 401 status code.

Can you add to the documentation information about authorization and how can you add cookie/headers/etc to requests?

**Comment by fryette** [comment]
@Nehoko will do
