### ISSUE TITLE
add integration with retrofit 

### ISSUE THREAD

**Issue by WahdanZ** [epam-cross-platform-lab/swagger-dart-code-generator#139]
will be nice if we integrate with https://pub.dev/packages/retrofit

**Comment by fryette** [comment]
Retrofit used DIO, we decided to go with a chopper that is analog of DIO with the same functionality.
If you have any troubles with the chopper feel free to highlight it.

**Comment by Hu-Wentao** [comment]
I think `Dio` has more powerful intercepter, chopper's too weak

**Comment by BarRemisz** [comment]
Also `DIO` is more popular. Is there something can we could do to help integrate with `Retrofit/DIO`?

**Comment by Vovanella95** [comment]
@BarRemisz to do this we should implement new generator

**Comment by thomtomdup** [comment]
Hello. 
Does Retrofit will be added or definitely not ?
Thank you.
