### ISSUE TITLE
Support for OpenAPI 3.0 servers definition

### ISSUE THREAD

**Issue by PKIE** [epam-cross-platform-lab/swagger-dart-code-generator#143]
OpenAPI 3.0 uses servers array instead of host, basePath and schemes.
Are there plans to support it?

https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by fryette** [comment]
Hm...actually good idea.
We are not using it for now on our projects, but let's keep progress in the current issue.
Now everything you can set up with your own ChopperClient(base url and etc).

Agree that it should be supported.
Also contribution very appreciated

**Comment by Vovanella95** [comment]
Hi @PKIE , @fryette 

We already parsing baseUrl. I can't see how can we implement support of multiple servers and such things. If you have idea how to do it - please reopen the issue.
