### ISSUE TITLE
Example App load image doesn't work

### ISSUE THREAD

**Issue by fphilip** [epam-cross-platform-lab/swagger-dart-code-generator#144]
Inserting this code un main.dart the status code returned is 415

`
  print(
      'Hello, my name is ${getResult.body.name}, I am ${getResult.body.category.name}');

  print('updating my image');
  final bytes = await HttpClient()
      .getUrl(Uri.parse(
          'https://i.pinimg.com/originals/de/71/bb/de71bb8a57ff473cc58ebc6af58c4858.jpg'))
      .then((value) => value.close())
      .then((value) => value.first);

  final uploadResult = await client.uploadFile(petId: 11, file: bytes);

  if (uploadResult.statusCode != 200) {
    print('no ok  ${uploadResult.statusCode} ${uploadResult.bodyString}');
  }`

I have seen that the generated code not implemented the multipart requirements for a chopper send function.

I was testing with these changes as a workaround to apply in my project, but I can't resolve it

` @override
  Future<Response<ApiResponse>> uploadFile(
      {int petId, String additionalMetadata, List<int> file, Object body}) {
    final $url = '/pet/$petId/uploadImage';
    final $parts = <PartValueFile>[
      PartValueFile('formData', file)
    ];
    final $request = Request('POST', $url, client.baseUrl,  multipart: true, parts: $parts);
    return client.send<ApiResponse, ApiResponse>($request,
        requestConverter: FormUrlEncodedConverter.requestFactory);
  }`

Any idea how to solve this problem?

**Comment by fphilip** [comment]
Hi
changing this part returns 200
`
  @override
  Future<Response<ApiResponse>> uploadFile(
      {int petId, String additionalMetadata, List<int> file, Object body}) {
    final $url = '/pet/$petId/uploadImage';
    final $parts = <PartValue>[PartValueFile<List<int>>('file', file)];
    final $request = Request('POST', $url, client.baseUrl,  multipart: true, parts: $parts);
    return client.send<ApiResponse, ApiResponse>($request,
        requestConverter: FormUrlEncodedConverter.requestFactory);
  }`

**Comment by Vovanella95** [comment]
Hi @fphilip ! We will take a look into it soon. Currently we focused on chopper null safety migration contribution. Then I've check all issues in swagger generator and fix it. Thanks for using our lib!

**Comment by Vovanella95** [comment]
Hi @fphilip  please provide swagger example for this case and reopen the issue, if it still actual
