### ISSUE TITLE
Generating name as Object

### ISSUE THREAD

**Issue by zhukeev** [epam-cross-platform-lab/swagger-dart-code-generator#152]
if backend responds like this
{
  "count": 0,
  "next": "string",
  "previous": "string",
  "results": [
    {
      "id": 0,
      "user": 0,
      "type": 0,
      "value": "string",
      "created_date": "2021-04-11T06:43:57.900Z",
      "updated_date": "2021-04-11T06:43:57.900Z"
    }
  ]

it generates results as Object, how to workaround ?

**Comment by fryette** [comment]
Could you please provide a swagger file?

**Comment by zhukeev** [comment]
Here's my a .swagger file, you can try to generate https://drive.google.com/file/d/17Pw5gm4dbwzSSJkt7_Hqc8bFpugpyS4J/view?usp=sharing

**Comment by Vovanella95** [comment]
Hi @zhukeev ! We will check your issue asap! I hope this week

**Comment by Vovanella95** [comment]
Hi @zhukeev ! it's really interesting case we have not implemented yet.

You using direct model injection into response. We will implement it soonm but as workaroung you can just put this model to definitions.

`"responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/TrailersList"
            }
          }
        },`

`"TrailersList": {
      "properties": {
        "count": {
          "type": "integer"
        },
        "next": {
          "type": "string",
          "format": "uri",
          "x-nullable": true
        },
        "previous": {
          "type": "string",
          "format": "uri",
          "x-nullable": true
        },
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Trailer"
          }
        }
      }
    }`


And the result will be as expected.

` @Get(path: '/car/trailer/')
  Future<chopper.Response<TrailersList>> carTrailerGet(
      {@Query('limit') int? limit, @Query('offset') int? offset});`


Let me share full modified file as example.
https://1drv.ms/u/s!Ao8J_04PyR8DhN98xMtjocZrqS8m8Q?e=e113y5


Please keep issue opened until we fix it without workarounds. I will let you know when it will be ready

**Comment by zhukeev** [comment]
hey @Vovanella95 thank you! Now I'm workarounding like this `
class Result<T> {
  Result({
    this.count,
    this.next,
    this.previous,
    this.results,
  });

  int? count;
  String? next;
  String? previous;
  List<T>? results;

  static Result<T> fromJson<T>(Map<String, dynamic> json) => Result<T>(
        count: json['count'],
        next: json['next'],
        previous: json['previous'],
        results: List<T>.from(json['results'].map((x) => x.fromJson(x))),
      );

  Map<String, dynamic> toJson() => {
        'count': count,
        'next': next,
        'previous': previous,
        'results':
            List<T>.from(results?.map((x) => (x as dynamic).toJson()) ?? []),
      };
}` and parsing directly from response but  your option is interesting too, thanks one more time

**Comment by Vovanella95** [comment]
Hi again, @zhukeev 

https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/pull/161 :-)

I will check if everything is correct with my set of swaggers tomorrow and release new version.

Currently you can just use branch name in pubspec.yaml

And you don't need any work arounds :)

Please let me know if anything is not OK

**Comment by zhukeev** [comment]
@Vovanella95  Wow, sounds great !

**Comment by zhukeev** [comment]
it says `Exception has occurred.
Could not find factory for type DealDealGet$Response. Is 'DealDealGet$Response: DealDealGet$Response.fromJsonFactory' included in the CustomJsonDecoder instance creation in bootstrapper.dart?`

https://imgur.com/a/FMFxHgs

**Comment by Vovanella95** [comment]
@zhukeev I've fixed this issue in master

Please confirm you using latest version from pub.dev
