### ISSUE TITLE
Add possibility to set suffix for generated swagger models

### ISSUE THREAD

**Issue by Andrushka1012** [epam-cross-platform-lab/swagger-dart-code-generator#164]
it would be great to have possibility set generated model name suffix. So if swagger model is User it would be possible to have generated model named UserDto.

**Comment by Vovanella95** [comment]
Hi @Andrushka1012 , It's good idea we will look into it. Currently we working on refactoring of whole package. After it we will fix all open issues. I hope finish refactoring in few weeks.

**Comment by Vovanella95** [comment]
Hi @Andrushka1012 

I'm going to implement it during week. We're not forgot about you :)

**Comment by Vovanella95** [comment]
@Andrushka1012 I've implemented this. But not releases yet.

You can use remote branch right now or vain for a new version.
https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/pull/166

**Comment by Vovanella95** [comment]
Fixed. Please check 2.0.1 version :) @Andrushka1012

**Comment by Vovanella95** [comment]
merged in master!
