### ISSUE TITLE
Generate tested code

### ISSUE THREAD

**Issue by mzdm** [epam-cross-platform-lab/swagger-dart-code-generator#177]
This is a purely theoretical question ... but I wonder, do you think that is it possible to generate tests as well (if it would be implemented in the generator of course). Because if you're generating a very big amount of APIs (for example Google APIs or etc.) which can have 10, 50, or even 100 APIs, manual testing would be a nightmare.

I would like to contribute such a feature, I don't have much time anytime soon but I wonder if it would be something you would review and you think it is possible and could eventually work.
@Vovanella95 

([google dart apis package](https://github.com/google/googleapis.dart/tree/master/generated/googleapis) is a good example of generated tests, but they use Google Discovery not OpenAPI)

_Originally posted by @mzdm in https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/174#issuecomment-855410830_

**Comment by Vovanella95** [comment]
Hi @mzdm ,

Why you need to test generated code? Why just not ignore it in configuration and not include it into coverage report?

**Comment by mzdm** [comment]
> Hi @mzdm ,
> 
> Why you need to test generated code? Why just not ignore it in configuration and not include it into coverage report?

Sometimes there are needed some manual fixes (like changing models or fixing bugs) so to ensure that nothing else would break, but yea I have changed my mind about this and it's not a priority for me anymore.

So I think I'll close for now since it's not on my radar any time soon. 👍

**Comment by Vovanella95** [comment]
Hi @mzdm ,

In case of bugs just let us know :)
