### ISSUE TITLE
Create req/resp classes only generated API methods

### ISSUE THREAD

**Issue by FantasyOR** [epam-cross-platform-lab/swagger-dart-code-generator#181]
Hi.
Thank you for update of my issues "Generate not all API methods". It's work good.
But classes are create for all method, not just generated ones.
Please update to generated only needed req/resp classes.

Thank you very much for your job.

**Comment by Vovanella95** [comment]
Hi,
I will look into it.

**Comment by fryette** [comment]
Hey.

I would like to suggest asking question ONLY via Github.

We are not going to add such feature, what I can recommend is removing unneeded swagger parts via script and then generate it.

If you want to introduce custom behavior feel free to fork project.

**Comment by FantasyOR** [comment]
Okay.
