### ISSUE TITLE
All properties is nullable

### ISSUE THREAD

**Issue by FantasyOR** [epam-cross-platform-lab/swagger-dart-code-generator#182]
Hi.
I find bug - in dto models all properties is nullable.

![image](https://user-images.githubusercontent.com/3586153/122723370-8f2f8a80-d27b-11eb-9485-3d60dd9f5444.png)

**Comment by Vovanella95** [comment]
Hi @FantasyOR ,

It's not a but. We made all properties nullable because these models are used for making requests too. If you make request using GeneratedModel and you want include not all fields - the only one desision is to keep all properties nullable

**Comment by FantasyOR** [comment]
Thanks. Okay.

**Comment by ened** [comment]
@Vovanella95 While I can see the reasoning for the decision, I disagree with it. Non-Nullable fields should be marked as such in Dart and cause proper JSON parse errors when the response is received with invalid data.

Likewise, for fields that are actually nullable, the consumer of the API client should be required to handle it.

If the same model is used for a request and has a different set of optional fields compared to the response, probably a different model should be used altogether.

**Comment by Vovanella95** [comment]
Hi @ened,

It's needed in cases, when You use it like request body or as request parameter. If properties are not nullable - you will always include them into request body and server can re-write data by empty strings and zeros. So we decided to make all properties nullable, so you can use includeIfNull parameter to manage, what will be sent to server.

In future we want to generate separate set of models for requests, or check more ideas how to fix it. 

Maybe You have some ideas how to fix this?

**Comment by ened** [comment]
1. Non-nullable fields should be set on the object constructor when making the request, never through a setter for the reason you mentioned.
2. Nullable fields, when null, can be managed with the includeWhenNull property, cool.

Separate models for request and response would be the best way, but also this should be up to the swagger user, not a decision in the swagger code generator.

**Comment by Vovanella95** [comment]
We will implement separate models in future. But for now - no.

Also I did not understand point 1. If field not nullable - it will always has value in moment we use it. So it will be anyway sent to server as 0 or empty string or smth.

**Comment by ened** [comment]
For point 1: 

Given the generated code has two fields:

``` dart
class SomeRequest {
  const SomeRequest({
    this.field,
    this.field2,
  });

  final String field;
  final String? field2;
}
```

Then instantiating this with:

``` dart
SomeRequest(field: 'value')
```

Would do exactly what I'd expect it to. If the field is required, the user sets a value to it. If user sets that value to `''`, that's now the users decision.

Currently, the above request class is defined as:

``` dart
class SomeRequest {
  const SomeRequest({
    this.field,
    this.field2,
  });

  final String? field;
  final String? field2;
}
```

Which causes the problem you mentioned (0, empty string, etc.. ). Correct?

**Comment by ened** [comment]
@Vovanella95 hi, do you have any further comment?

**Comment by Vovanella95** [comment]
@ened  hello,

Generation of two fields is too complex and looks like spike. I can't accept it sorry

**Comment by ened** [comment]
@Vovanella95 I was not asking for 2 fields. Just sensible null value and constructor with default arguments to workaround the null, '', 0 issue.. :)

**Comment by ened** [comment]
@Vovanella95 I don't? If the field is `null` it shouldn't be sent and the value in the Dart object should be optional. (`?`)

**Comment by Vovanella95** [comment]
@ened 

class SomeRequest {
  const SomeRequest({
    this.field,
    this.field2,
  });

  final String? field;
  final String? field2;
}

Is not possible construction. we should mark properties as required or make them nullable. Can you propose the way how to generate non-nullable fields and exclude them from requests? Sorry if I missing the point

**Comment by ened** [comment]
Yes, apologies @Vovanella95 , this should be:

``` dart
class SomeRequest {
  const SomeRequest({
    required this.field,
    this.field2,
  });

  final String field;
  final String? field2;
}
```

In this case, when the swagger file defines a required field, this will translate directly to `required` field attribute in the constructor. 

Constructing a `SomeRequest` in this case would ensure the API user sets the required fields right away.

**Comment by Vovanella95** [comment]
But if I want to send this model to server with field==null? In this case it's not possible

**Comment by Vovanella95** [comment]
I mean if I want not to send field to server

**Comment by ened** [comment]
If the field is `null`, you omit it - and let the server understand that a missing field means `null`, `''`, `0` or anything else.

As mentioned previously, if the server needs a request field to be nullable, the Swagger file would use a different object for request and response. If the swagger file "re-uses" the same model object for both request and response, this is a matter of the swagger definition file, not of this plugin.

**Comment by Vovanella95** [comment]
@ened Server not even recognize '' as 'no value'. For example, server can think, you can rename something to empty line, but you did not wanted to change this value. Same for 0

**Comment by ened** [comment]
@Vovanella95 based:

```
class SomeRequest {
  const SomeRequest({
    required this.field,
    this.field2,
  });

  final String field;
  final String? field2;
}
```

If you set `field` to "something", or to "", then it will be sent to the server with that value. The server figures if "" is valid or not.
If you set `field2` to "something", or to "", the same rule applies.

If you don't set `field2`, it is `null` and will not be sent by swagger. I don't see what the problem is.

**Comment by Vovanella95** [comment]
@ened  I don't want to send "" or 0 to the server. Because if the server receives 0, it can decide to change some value to 0. Same for strings.

**Comment by ened** [comment]
@Vovanella95 then just don't set the `field2`, in this example. If you don't set it, my expectation is that this plugin just ignores it and does not sent it to the server, so the server can figure it out. It's very simple, isn't it?

**Comment by Vovanella95** [comment]
@ened  OK but field 2 is nullable. And you still should use ?? or ! operators to get this value.

**Comment by ened** [comment]
@Vovanella95 yes of course. For fields that are marked optional in the swagger files that absolutely fine (and expected).

**Comment by Vovanella95** [comment]
@ened  Yes you're right. But If I really want not to send such parameters to server even if they are marked as required? We need to do this at out project. So possible on another projects it's needed too. That's why I want to generate separate models for request bodies and separate for responses.

**Comment by ened** [comment]
So by definition, if you don't want to send a required field, you are "breaking the API". That's the exact reason we have Swagger!! :-)

In your own project, you should then probably define separate models for request (all optional fields) and response (only "true" optional fields are marked as such) in the swagger file. Again, this code generator should not take break the swagger spec.

**Comment by Vovanella95** [comment]
@ened  Anyway I will no make fields not nullable. I will implement approach with separate models in future. Thanks for understanding :)

**Comment by zorji** [comment]
Hi @ened, I also would like the properties correctly reflect what is defined in the swagger, I'll start my initial attempt here https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/pull/282

However, I do have a question regards to `required=false` and `nullable=true`. I am not too sure what's the best data structure to represent this.

In Swagger `required=false` means a field is optional but it doesn't mean it can be null (i.e. non nullable).
Looks like the only way to model this in Dart is use `null` to represent a field is not returned. (or maybe better discuss further in my PR).

q for @Vovanella95, I do agree with @ened that the generated model should be consistent with the defined Swagger, are you fine for me to start to attempt to set field to non-nullable?
