### ISSUE TITLE
Optional body for POST/PATCH/PUT

### ISSUE THREAD

**Issue by WahdanZ** [epam-cross-platform-lab/swagger-dart-code-generator#183]
I have a POST method without a Body(), which causes the following warning:
Body is null
Use @Body() annotation on your method parameter to provide a body to your request
Chopper already support that 
```dart
@Post(path: '/some/path', optionalBody: true)
```
https://github.com/lejard-h/chopper/issues/149

**Comment by Vovanella95** [comment]
Hi @WahdanZ ,

it's actually good idea!

We will take a look into it

**Comment by Vovanella95** [comment]
Hi @WahdanZ ,

I've added this feature into 2.1.0 branch.

There are just few issues left to fix and it will be released!

**Comment by Vovanella95** [comment]
Hi @WahdanZ please chech 2.1.1 version. I've added support of this. Please let us know if something works wrong.

Thanks for this cool idea!
