### ISSUE TITLE
Class Attribute / Request Param collision

### ISSUE THREAD

**Issue by point-source** [epam-cross-platform-lab/swagger-dart-code-generator#187]
I have a swagger spec which details some requests that accept a string parameter called "client". This shadows the client attribute of the generated class which prevents the method from accessing the chopper client. 

How can I override one or the other of these in the generator?

**Comment by Vovanella95** [comment]
Hi @point-source ,
you can try use use_path_for_request_names for request names. Possible it will change parameter names (I'm not sure).

You can share swagger file (or part of it) and I will fix swagger generator pr provide solution for you.

**Comment by point-source** [comment]
I tried that but it only changed the method names, not the parameter names. Here is the code that is failing:

```dart
  @override
  Future<Response<ClientAddressesGet$Response>> clientAddressesList(
      {String? client,
      String? company_name,
      String? contact_name,
      String? street1,
      String? db_date_updated__gt,
      String? db_date_updated__lt,
      int? limit,
      int? offset}) {
    final $url = '/client_addresses';
    final $params = <String, dynamic>{
      'client': client,
      'company_name': company_name,
      'contact_name': contact_name,
      'street1': street1,
      'db_date_updated__gt': db_date_updated__gt,
      'db_date_updated__lt': db_date_updated__lt,
      'limit': limit,
      'offset': offset
    };
    final $request = Request('GET', $url, client.baseUrl, parameters: $params);
    return client.send<ClientAddressesGet$Response,
        ClientAddressesGet$Response>($request);
  }
```

The `String? client` arg shadows the chopper client from the enclosing class so that `client.baseUrl` fails to resolve. (Error: The property 'baseUrl' can't be unconditionally accessed because the receiver can be 'null'.)

This can be fixed by the use of `this.` to avoid shadowing:

```
    final $request = Request('GET', $url, this.client.baseUrl, parameters: $params);
    return this.client.send<ClientAddressesGet$Response,
        ClientAddressesGet$Response>($request);
  }
```

However, it may be better to just make the chopper client attribute into a private field (assuming that's compatible with the rest of this API) since unnecessary `this.` usage causes the analyzer to warn.

Here is the relevant swagger spec: https://gist.github.com/point-source/06bf4559145ecd01a2d806df61895b81

**Comment by Vovanella95** [comment]
Hi!

The issue happened because request parameter was named 'client' and it conflicted with chopper client instance.
I've created a PR and release new version soon.

**Comment by Vovanella95** [comment]
C.C. @point-source

**Comment by point-source** [comment]
Yep, this issue appears solved on branch version/2.0.8_plus. To be clear, it adds a $ sign in front of the param name which I believe is the intended behavior but stating just to confirm.

Also, this spec suffers from the [enum issue](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/189) that was mostly fixed on 2.0.9. So in order to fully generate this one, I need the changes from 2.0.9 and 2.0.8 merged together. Not a big deal as I can do this in a fork, just letting you know.

**Comment by Vovanella95** [comment]
Hi @point-source 

We add $ at the beginning of all parameters named by key words.  For example parameter 'if' will be named $if etc. As far I know it's good practice

**Comment by point-source** [comment]
Works for me! Feel free to close either now or whenever you merge. Thanks
