### ISSUE TITLE
Swagger specs failing to build (Rentalworks API)

### ISSUE THREAD

**Issue by point-source** [epam-cross-platform-lab/swagger-dart-code-generator#201]
As the [original issue](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/189#issuecomment-885288108) was closed (somewhat rightfully so), I wanted to open a new one here to track the collection as a whole. I am trying to generate clients for [this entire folder](https://www.dropbox.com/sh/2t3s99zsmgf89ar/AACGJzjw3cPRCCEMDMvn6is9a?dl=0) but right now only these (3 of 9) are succeeding:

- account_services
- exports
- plugins

I have tested on 2.0.7, 2.0.8, 2.0.8+1, 2.9.0 (branch), 2.1.0 (branch), and master as of [this commit](d946ad2ac896c66bad2f8e16f5f0ab76a2d29a31)

Let me know if any more information is needed

**Comment by Vovanella95** [comment]
Hi @point-source ,

I've fixed issues with your crazy 200k+ lines swaggers :D

Please checl 2.0.1 branch for now. I will release new version when test everything.

**Comment by point-source** [comment]
Will test in about an hour. Thank you so much! Do you guys have a donation page? :heart:

**Comment by point-source** [comment]
Looks like it's all good! Closing.
