### ISSUE TITLE
2.1.0-prerelease.2/3 is using snake_cased method names and incorrect type names

### ISSUE THREAD

**Issue by point-source** [epam-cross-platform-lab/swagger-dart-code-generator#204]
It seems that methods are being named with snake_case and types have been inconsistently named such that the names don't match between the class declaration and references.

Specifically, this:

```dart
  ///
  ///@param external_code
  ///@param name
  ///@param slug
  ///@param limit Number of results to return per page.
  ///@param offset The initial index from which to return the results.

  @Get(path: '/account_event_statuses')
  Future<chopper.Response<AccountEventStatusesGet$Response>>
      accountEventStatusesList(
          {@Query('external_code') String? external_code,
          @Query('name') String? name,
          @Query('slug') String? slug,
          @Query('limit') int? limit,
          @Query('offset') int? offset});
```

has changed to this:

```dart
  ///
  ///@param external_code
  ///@param name
  ///@param slug
  ///@param limit Number of results to return per page.
  ///@param offset The initial index from which to return the results.
  @Get(path: '/account_event_statuses')
  Future<chopper.Response<AccountEventStatusesList$Response>>
      account_event_statuses_list(
          {@Query('external_code') String? external_code,
          @Query('name') String? name,
          @Query('slug') String? slug,
          @Query('limit') int? limit,
          @Query('offset') int? offset});
```

Since the new code does not follow dart format conventions, the analyzer warns on the snake-case method names. 

Additionally, the new type name `AccountEventStatusesList$Response` does not resolve since the definition for it is still named `AccountEventStatusesGet$Response`.

I have tested this on this package using 2.1.0-prerelease .2 and .3: https://github.com/point-source/dart_lasso

_Originally posted by @point-source in https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/200#issuecomment-893837650_

**Comment by Vovanella95** [comment]
Hi @point-source ,

We decided to always generate request names from path and remove next build option: `use_path_for_request_names`

If your project uses version less than 2.1.0-prerelease.7, please just set use_path_for_request_names to true.
