### ISSUE TITLE
Request url params specified by non-primitive types are not properly serialized/encoded into requests

### ISSUE THREAD

**Issue by point-source** [epam-cross-platform-lab/swagger-dart-code-generator#205]
Using [this package](https://github.com/point-source/dart_rentalworks) (generated with swagger_dart_code_generator) to perform the following request:

```dart
  var rw = RentalWorks.withCredentials('https://my-company.rentalworksweb.com/api/v1',
      'my-username', 'my-password');
  var quotes = await rw.home.quoteGet(filter: [
    FwStandardModelsFwQueryFilter(
        field: 'QuoteNumber', op: '=', value: '306142')
  ]);

  if (!quotes.isSuccessful) {
    print('${quotes.statusCode}: ${quotes.base.reasonPhrase}');
  }

  for (WebApiModulesAgentQuoteQuote d in quotes.body?.items ?? []) {
    print(d.description);
  }
```

This results in a 500: Internal Server Error because the FwStandardModelsFwQueryFilter gets converted to a string rather than serialized to json and url encoded. The request that gets created is:

`Request (GET https://my-company.rentalworksweb.com/api/v1/quote?filter=Instance+of+%27FwStandardModelsFwQueryFilter%27)`

when it should be:

`Request (GET https://my-company.rentalworksweb.com/api/v1/quote?filter=%7B%0A%20%20%22Field%22%3A%20%22QuoteNumber%22%2C%0A%20%20%22Op%22%3A%20%22%3D%22%2C%0A%20%20%22Value%22%3A%20%22306142%22%0A%7D)`

Tested on 2.1.0-prerelease.3

**Comment by point-source** [comment]
I am currently working around this with the following interceptor code:

```dart
  Request Function(Request) get _paramConverterInterceptor =>
      (Request request) =>
          request.copyWith(parameters: _convertParams(request.parameters));

  dynamic _convertParams(dynamic value) {
    switch (value.runtimeType) {
      case String:
      case int:
      case Null:
      case double:
        return value;
      default:
        if (value is Iterable) {
          return value.map(_convertParams);
        }
        if (value is Map<String, dynamic>) {
          return value
              .map((key, value) => MapEntry(key, _convertParams(value)));
        }
        final json = value?.toJson();
        if (json is Map) {
          return jsonEncode(_convertParams(json));
        }
        return value;
    }
  }
```

Additionally, while developing this workaround, I came across what I believe to be a[ bug in chopper](https://github.com/lejard-h/chopper/issues/283).

**Comment by Vovanella95** [comment]
Hi @point-source , Please ensure .swagger.dart file is correct. If no - we will fix it just let us know how.  Or if it's chopper issue - close this issue.

Thanks in advance :)

**Comment by point-source** [comment]
The swagger seems to be fine as far as I can tell. I'm not 100% sure if this is a chopper issue or not but it looks like one to me. The workaround I posted is something that can be integrated with this library to workaround the issue. As you can see, I did file a bug report with chopper as well. In the meantime, I will work on making a swagger file and test that demonstrates this issue to try to definitively nail it down to either chopper or sdcg.

**Comment by fryette** [comment]
@point-source you always can create a file with chopper annotation by yourself without swagger code generator.
But probably for us would be much better to have a swagger file that we can reproduce issue.
Or you can create test swagger for us if it is too private

**Comment by Vovanella95** [comment]
@point-source  please share the expected generated file and the actual one. And also example of swagger code.

**Comment by point-source** [comment]
I'm sorry guys, I just have not had time to look at this. Way behind on development in other areas. I'm going to close this for now and reopen when I can. Thanks for the help
