### ISSUE TITLE
 type 'YamlMap' is not a subtype of type 'bool?' in type cast

### ISSUE THREAD

**Issue by zhukeev** [epam-cross-platform-lab/swagger-dart-code-generator#208]
Can not run with this file. version : ^2.1.0-prerelease.3

*Swagger file*

[link](https://docs.google.com/document/d/1PR9K6gca2eTAyYqA35x5J5ylME-_P26XSwign2qHrAc/edit?usp=sharing)

*build.yaml*

``
targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          with_base_url: true
          with_converter: true
          use_required_attribute_for_headers: true
          ignore_headers: true
          use_default_null_for_lists: false
          use_inheritance: false
          build_only_models: false
          use_path_for_request_names: false
          include_if_null:
            enabled: true
            value: false
          input_folder: "lib/"
          output_folder: "lib/services/generated_rest_service/"
          enums_case_sensitive: true
          default_values_map:
            - type_name: int
              default_value: "0"
          # response_override_value_map: 
``

*Logs*
```

[INFO] Bootstrap:Precompiling build script......
[FINE] Bootstrap:../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/swagger_dart_code_generator-2.1.0-prerelease.3/lib/src/swagger_models/swagger_root.g2.dart:20:12: Warning: Operand of null-aware operation '??' has type 'Map<String, SwaggerPath>' which excludes null.
 - 'Map' is from 'dart:core'.
 - 'SwaggerPath' is from 'package:swagger_dart_code_generator/src/swagger_models/swagger_path.dart' ('../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/swagger_dart_code_generator-2.1.0-prerelease.3/lib/src/swagger_models/swagger_path.dart').
    paths: _mapPaths(json['paths'] as Map<String, dynamic>) ?? {},
           ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/swagger_dart_code_generator-2.1.0-prerelease.3/lib/src/swagger_models/swagger_components.g2.dart:21:16: Warning: Operand of null-aware operation '??' has type 'Map<String, SwaggerSchema>' which excludes null.
 - 'Map' is from 'dart:core'.
 - 'SwaggerSchema' is from 'package:swagger_dart_code_generator/src/swagger_models/responses/swagger_schema.dart' ('../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/swagger_dart_code_generator-2.1.0-prerelease.3/lib/src/swagger_models/responses/swagger_schema.dart').
    responses: mapResponses(json['responses'] as Map<String, dynamic>?) ?? {},
               ^
../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/swagger_dart_code_generator-2.1.0-prerelease.3/lib/src/swagger_models/swagger_components.g2.dart:23:9: Warning: Operand of null-aware operation '??' has type 'Map<String, SwaggerSchema>' which excludes null.
 - 'Map' is from 'dart:core'.
 - 'SwaggerSchema' is from 'package:swagger_dart_code_generator/src/swagger_models/responses/swagger_schema.dart' ('../../Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/swagger_dart_code_generator-2.1.0-prerelease.3/lib/src/swagger_models/responses/swagger_schema.dart').
        mapResponses(json['requestBodies'] as Map<String, dynamic>?) ?? {},
        ^
[INFO] Bootstrap:Precompiling build script... completed, took 7.3s

[INFO] Bootstrap:There was output on stdout while precompiling the build  script, run with `--verbose` to see it (you will need to run a `clean` first to re-generate it).

[FINE] Bootstrap:Core package locations file does not exist
[SEVERE] swagger_dart_code_generator:swagger_dart_code_generator:

type 'YamlMap' is not a subtype of type 'bool?' in type cast


package:swagger_dart_code_generator/src/models/generator_options.g2.dart 42:44  _$GeneratorOptionsFromJson
package:swagger_dart_code_generator/src/models/generator_options.dart 31:7      new GeneratorOptions.fromJson
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 47:32      new SwaggerDartCodeGenerator
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 10:5       swaggerCodeBuilder
package:build_runner_core/src/package_graph/apply_builders.dart 179:47          new BuilderApplication.forBuilder.<fn>.<fn>.<fn>
dart:async                                                                      runZonedGuarded
package:build_runner_core/src/package_graph/apply_builders.dart 388:10          _scopeLogSync
package:build_runner_core/src/package_graph/apply_builders.dart 179:13          new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner_core/src/package_graph/apply_builders.dart 342:27          _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                                       Iterable.toList
package:build_runner_core/src/package_graph/apply_builders.dart 289:8           createBuildPhases
package:build_runner_core/src/generate/build_impl.dart 110:29                   BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 34:42                  BuildRunner.create
package:build_runner                                                            BuildCommand._run
package:args/command_runner.dart 196:13                                         CommandRunner.runCommand
package:build_runner                                                            run
.dart_tool/build/entrypoint/build.dart 31:16                                    main

[+22234 ms] "flutter run" took 22,318ms.


[   +5 ms] pub finished with exit code 78
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:366:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:241:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1043:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
```

**Comment by Vovanella95** [comment]
Hi @zhukeev ,
I will try to check it today

**Comment by Vovanella95** [comment]
Ahh problem is not in build.yaml. I'll fix this ASAP (tomorrow or next weak)

**Comment by zhukeev** [comment]
Any news out there ?

**Comment by Vovanella95** [comment]
Hi @zhukeev , promise to check it today

**Comment by Vovanella95** [comment]
Hi again. I've tried to generate your config and looks like something wrong in your build.yaml. Please ensure all spaces are correct. Here is formatted build.yaml file:

`targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          with_base_url: true
          with_converter: true
          use_required_attribute_for_headers: true
          ignore_headers: true
          use_default_null_for_lists: false
          use_inheritance: false
          build_only_models: false
          use_path_for_request_names: false
          include_if_null:
            enabled: true
            value: false
          input_folder: "lib/"
          output_folder: "lib/services/generated_rest_service/"
          enums_case_sensitive: true
          default_values_map:
            - type_name: int
              default_value: "0"`


Also try to call `flutter clean` and then `flutter pub get`. If you will still have error - please share you repository and let me see.

C.C. @zhukeev

**Comment by Vovanella95** [comment]
Check working example at next [branch](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/tree/issue/208)

[build.yaml](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/blob/issue/208/example/build.yaml)

**Comment by Vovanella95** [comment]
### Most important thing you're using prerelease. There is include_if_null is just bool? value.

just change build.yaml to` include_if_null: false`

**Comment by Vovanella95** [comment]
I will change README when branch will be merged into master

**Comment by Vovanella95** [comment]
C.C. @zhukeev

**Comment by zhukeev** [comment]
I got it thanks

**Comment by zhukeev** [comment]
then it says 
``` type 'Null' is not a subtype of type 'String' in type cast ```

**Comment by zhukeev** [comment]
oh it's ok now, I replaced build.yaml with the example app's one

**Comment by zhukeev** [comment]
but it generates like this ```
  ///
  @Get(path: '/user/user/{id}/')
  Future<chopper.Response<User>> userUserIdGet();
```
**without parameter**

**Comment by Vovanella95** [comment]
@zhukeev , Will check it right now

**Comment by Vovanella95** [comment]
@zhukeev  It's not depend on this property. You just have supercool swagger file with new border cases :) It's really great I can improve our generator!

Give me just few minutes

**Comment by Vovanella95** [comment]
@zhukeev  please check this one: https://pub.dev/packages/swagger_dart_code_generator/versions/2.1.0-prerelease.4

Your file is generated without issues.

Is everything OK?

**Comment by zhukeev** [comment]
Thanks!  Let me check now

**Comment by zhukeev** [comment]
Yes it generates without any issue but the problem with GET, DELETE methods still there - without id properies

**Comment by Vovanella95** [comment]
@Get(path: '/user/user/{id}/')
  Future<chopper.Response<User>> userUserIdGet();

Is generated without parameters anyway. because it has '"parameters": [],' in swagger file.

**Comment by Vovanella95** [comment]
"delete": {
          "operationId": "user_user_delete",
          "description": "",
          "parameters": [],
          "responses": {
            "204": {
              "description": ""
            }
          },
          "tags": [
            "user"
          ]
        },
        
        
        Delete also has no parameters in swagger file.

**Comment by zhukeev** [comment]
Ahh, thanks

**Comment by Vovanella95** [comment]
Ah, they has common parameter below. Unfortunatelly it's not supported right now. I can implement it in few days. Can we create separate issue for this?

**Comment by Vovanella95** [comment]
@zhukeev  C.C.

**Comment by Vovanella95** [comment]
It's easy fix but I don't have time right now to handle it. But I will do this anyway

**Comment by zhukeev** [comment]
Yes, sure

**Comment by Vovanella95** [comment]
Created!
https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/new

Closing this one.
