### ISSUE TITLE
Generated code has lint errors

### ISSUE THREAD

**Issue by guymclean** [epam-cross-platform-lab/swagger-dart-code-generator#221]
In version 2.0.4 you "Added equals override method to all Models" which allows us to unit test our code, thanks! Newer versions of Dart specify you must also override 'hashCode' when overriding '=='. As part of our CI pipelines we run 'dart fix' which automatically fixes issues like this one. This now means that each time we run build runner, the generated code reverts to having these lint issues highlighted. Would it be possible to also override 'hashCode' as well as '=='?

**Comment by Vovanella95** [comment]
Hi @guymclean ,

We will generate getHashCode override too. Thanks for raising this issue.

**Comment by Vovanella95** [comment]
Hi again.
Please check v 2.1.0-prerelease.8

@guymclean
