### ISSUE TITLE
Support for path parameters?

### ISSUE THREAD

**Issue by prasmussen** [epam-cross-platform-lab/swagger-dart-code-generator#239]
Is there support for [path params](https://github.com/lejard-h/chopper/blob/master/requests.md#path-parameters)?

My swagger definition contains operation with path params. I'm able to generate code, but I don't see any `@Path` annotations or function parameters where the values can be given.

**Comment by fryette** [comment]
Is it possible to share the swagger?
It helps us to faster assist with that issue.
Feel free to send it privately to **ysampir@gmail.com** or *Vovanella95@mail.ru*

Thanks!

**Comment by Vovanella95** [comment]
Hi @prasmussen , Path parameters are already supported. If you have issues with them - please share swagger file. But anyway path parameters are supported. THat's my answer

**Comment by prasmussen** [comment]
Thanks, then there is probably something strange with my swagger file. Will investigate further on my own.

**Comment by Vovanella95** [comment]
@prasmussen  your swagger file should be converted to json format.  Here is an example of path parameter

```
"/api/v3/someData/{id}": {
      "get": {
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
```
