### ISSUE TITLE
[BUG] Path params not generated

### ISSUE THREAD

**Issue by prasmussen** [epam-cross-platform-lab/swagger-dart-code-generator#240]
**Describe the bug**
The following swagger definition does not generate a function argument for the defined path param. The path param is defined as a  [Common Parameters for All Methods of a Path](https://swagger.io/docs/specification/describing-parameters/#common-for-path) which seems to not be supported?

**To Reproduce**
Swagger:
```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "path-params-demo",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/users/{userId}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "userId",
          "in": "path",
          "required": true,
          "description": "user id"
        }
      ],
      "get": {
        "summary": "get user",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "operationId": "get-users-userId"
      }
    }
  },
  "components": {
    "schemas": {},
    "parameters": {}
  }
}
```

Generated code:
```dart
@override
Future<Response<dynamic>> usersUserIdGet() {
  final $url = '/users/{userId}';
  final $request = Request('GET', $url, client.baseUrl);
  return client.send<dynamic, dynamic>($request);
}
```

**Expected behavior**
Expected generated function to take `userId` as argument

**Library version used:**
Commit: 63cdc323ceb49c1e928c7ed1b3f58d4052063fc5

**Comment by Vovanella95** [comment]
Hi @prasmussen , looks like easy fix. Will fix it today

**Comment by Vovanella95** [comment]
@prasmussen , enjoy 2.1.1+3 version already in pub.dev

Please, let us know in case of any issues

**Comment by prasmussen** [comment]
It works now 👍 
Thanks a lot for the quick fix :)
