### ISSUE TITLE
[QUESTION] Path still gets generated even when told not to

### ISSUE THREAD

**Issue by dtaskai** [epam-cross-platform-lab/swagger-dart-code-generator#245]
Path still gets generated in the swagger.dart file when specified like the following in the build.yaml file:

targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "lib/"
          output_folder: "lib/swagger_generated_code/"
          exclude_paths:
            - "/api/mobile/actuator/"

Am I using wrong syntax or is this an actual bug?

**Comment by Vovanella95** [comment]
hi @dtaskai , exclude_path and include_path are regex strings. to make your path excluded, you need to add something like this:

`\/api\/mobile\/actuator\/`

Please use Regex validator to check is you String passing or not. For example, you can use this validator: https://regex101.com/

**Comment by Vovanella95** [comment]
@dtaskai , if something is not clear - please let us know

**Comment by dtaskai** [comment]
The exclusion didn't work on my project even after using regex syntax, so I have tried it on the example project:

Added an exclusion to `/rooms`
`
swagger_dart_code_generator:
        options:
          input_folder: "lib/"
          output_folder: "lib/swagger_generated_code/"
          exclude_paths:
            - "\/rooms"
 `

Ran `flutter build run build_runner build`

Then it still generated the code for `/rooms`

```
@Get(path: '/rooms')
  Future<chopper.Response<List<Room>>> roomsGet(
      {@Query('id') required String? id});
```

**Comment by Vovanella95** [comment]
Ok good let me check it

**Comment by Vovanella95** [comment]
@dtaskai  Yep you're right. We removed it in 2+ version. Let me fix.

**Comment by Vovanella95** [comment]
@dtaskai Please try it on latest version. Also you can put just `/rooms` to exclude_path. It works.

Latest version is 2.1.3+2

**Comment by dtaskai** [comment]
Works on both the example and my personal project, thank you!
