### ISSUE TITLE
[QUESTION] Backend returns a 404, but the generated swagger code returns a 200

### ISSUE THREAD

**Issue by dtaskai** [epam-cross-platform-lab/swagger-dart-code-generator#249]
I have this part in my swagger file, which defines a 200 and a 404 for the URL which accepts a String and returns a json response:

`
"responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/UniPost"
              }
            }
          },
          "404": {
            "description": "Not found"
          }
        }
`

But when I try and test the generated client with a non-existent string ID my browser and even Postman returns a 404, but the generated client returns a 200 in every case.

`
test("Get a topic which does not exist", () async {
    Response<List<Topic>> topicNotExist = await apiClient.topicsUuidGet(uuid: "asdfgháéáéáéá");
    print(topicNotExist.statusCode);
  });
`

It prints 200.

Where does it go wrong?

**Comment by Vovanella95** [comment]
Hi @dtaskai , It's interesting case. It should work fine. I can't answer without debugging because it's reason is not obvious.

**Comment by dtaskai** [comment]
Tried to reproduce it in a fresh project and in there it works flawlessly, probably some dependency issue, thanks for your quick response!

**Comment by Vovanella95** [comment]
@dtaskai strange thing :D Please let us know in case of any issue! Can we close an issue then?

**Comment by dtaskai** [comment]
Yes, definitely!
