### ISSUE TITLE
Path Parameter Error on ref

### ISSUE THREAD

**Issue by andrlange** [epam-cross-platform-lab/swagger-dart-code-generator#253]
The build creates undefined object types using refs

**To Reproduce**
having the parameter id: in the path user/{id}
"/usert/{id}": {
      "get": {
parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/ObjectId"
            }
          }
        ],
     }
}

**Expected behavior**
Conversion on the ObjectId reference to it's real type String
"ObjectId": {
        "type": "string",
        "pattern": "^[a-fA-F0-9]{24}$",
        "example": "6148653375f4d9018966c771"
      },
 

**Library version used:**
2.2.0

**Additional context**
dart error: Undefined class 'ObjectId'

**Comment by fryette** [comment]
@andrlange I'm not sure but could you please make `flutter pub upgrade` and than rerun generation?

**Comment by Vovanella95** [comment]
Hi @andrlange , looks interesting. I will check it asap

**Comment by Vovanella95** [comment]
Hi again @andrlange ,

The issue happens because your request does not have responses. this field is mandatory. If I put your example to swagger editor - error will occured.
<img width="768" alt="Screenshot 2021-09-29 at 16 54 50" src="https://user-images.githubusercontent.com/11267533/135282740-3e7c64b2-e55c-4771-a95f-25d4a45496bb.png">

So handle it add responses to your swagger request. For example:

`"/usert/{id}": {
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/ObjectId"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ObjectId"
              }
            }
          }
        }
      }
    }`


Please let us know if it will not help.

**Comment by Vovanella95** [comment]
I've generated code and it looks fine.

`///
  ///@param id
  @Get(path: '/usert/{id}')
  Future<chopper.Response<List<ObjectId>>> usertIdGet(
      {@Path('id') required ObjectId? id});`

**Comment by andrlange** [comment]
Thanks for your super fast response. I have responses on my request but a after bumping json_serializable from 4.1.3 to 5.0.2 it works ...

**Comment by fryette** [comment]
@andrlange changelog upgraded accordingly.
Our mistake. Thx!
