### ISSUE TITLE
[QUESTION] int values for enums

### ISSUE THREAD

**Issue by Miiel** [epam-cross-platform-lab/swagger-dart-code-generator#268]
I'm working with an API that returns integer values for enums instead of their String names. So instead of:

```dart
enum UserRole {
  @JsonValue('swaggerGeneratedUnknown')
  swaggerGeneratedUnknown,
  @JsonValue('Guest')
  guest,
  @JsonValue('User')
  user,
  @JsonValue('Admin')
  admin
}
```

I would need this to be generated:
```dart
enum UserRole {
  @JsonValue(-1)
  swaggerGeneratedUnknown,
  @JsonValue(0)
  guest,
  @JsonValue(1)
  user,
  @JsonValue(2)
  admin
}
```

Is this possible with this package?

**Comment by Vovanella95** [comment]
Hi @Miiel 

I will check if it's possible to generate it like this. Actually it's good idea to generate int enums

**Comment by Vovanella95** [comment]
Hi @Miiel 

Please check latest version. Let us know in case of any issues
