### ISSUE TITLE
[QUESTION] name convention upgrading swagger_dart_code_generator

### ISSUE THREAD

**Issue by fphilip** [epam-cross-platform-lab/swagger-dart-code-generator#274]
Hi, when upgrade flutter version and swagger_dart_code_generator version to 2.2.4 i have found that the names of the methods change. I have a way to configure it?
![image](https://user-images.githubusercontent.com/2574152/140915835-22bdb125-61b7-4a6c-9a97-19cdc587973b.png)

![image](https://user-images.githubusercontent.com/2574152/140915113-a667b19f-26fc-4941-81c2-631eb75a466e.png)

**Comment by fryette** [comment]
Hi!

Because sometimes we have to deal with the same method names, that is why we introduced unique naming (actually it is constructed from URL, which is unique).

I'm sorry for such breaking changes.

If you have further questions feel free to reopen the issue

**Comment by fphilip** [comment]
Can we think of a behavior property that allows us to configure operation id vs url + method?

**Comment by fryette** [comment]
@fphilip as swagger documentation saying

> operationId is an optional unique string used to identify an operation. If provided, these IDs must be unique among all operations described in your API.

So we cannot rely on an optional string to satisfy all customers

We migrated more than 2K tests in 3 hours.

I'm really really sorry about additional efforts, we really trying to avoid such things as much as possible
