### ISSUE TITLE
Can we think of a behavior property that allows us to configure operation id vs url + method?

### ISSUE THREAD

**Issue by fphilip** [epam-cross-platform-lab/swagger-dart-code-generator#275]
Can we think of a behavior property that allows us to configure operation id vs url + method?

more than 300 test to migrate

_Originally posted by @fphilip in https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/274#issuecomment-964238298_

**Comment by Vovanella95** [comment]
Hi @fphilip , it's possible, we removed it when totally rewrited requests generator. Make sense to return this functionality back. I will think about it, but I need weak or two for this.

**Comment by fphilip** [comment]
> Hi @fphilip , it's possible, we removed it when totally rewrited requests generator. Make sense to return this functionality back. I will think about it, but I need weak or two for this.

do have "donate" button?

**Comment by Vovanella95** [comment]
Hi @fphilip , no :)

**Comment by Vovanella95** [comment]
@fphilip  Feel free to use 2.2.5 version
