### ISSUE TITLE
Please make a full use case example.

### ISSUE THREAD

**Issue by RoarGronmo** [epam-cross-platform-lab/swagger-dart-code-generator#278]
To make it easier for "newbies" in Flutter to start using this library, you should make following use case scenario in pub.dev:

1. Create the dart files from .swagger files (this you have already done here).
2. Create a simple project using the files which has been created.
3. Spice it with scenarios like "accessTokens" in headers (which is often used).

**Comment by Vovanella95** [comment]
Hi @RoarGronmo , We had good example before, and then it was removed when re refactored project. I will add good example project soon.
