### ISSUE TITLE
[FEATURE] Add YAML swagger files support

### ISSUE THREAD

**Issue by nkt1001** [epam-cross-platform-lab/swagger-dart-code-generator#284]
**Describe the solution you'd like**
I would like to be able to work with swagger files in YAML format

**Comment by fryette** [comment]
We also think that it would be great to support YAML files, that is why we are in process of rewriting some parts to be able to integrate more easily and finally switch completely from JSON to YAML.

**Comment by Vovanella95** [comment]
Hi @nkt1001 

Please use latest version in pub.dev. Yaml support is already added
