### ISSUE TITLE
swagger `int32` array is recognized as Dart `dynamic` if present directly from `body` in swagger file. 

### ISSUE THREAD

**Issue by RoarGronmo** [epam-cross-platform-lab/swagger-dart-code-generator#289]
**Describe the bug**
Swagger file with this section: 
```
    "/Order/firmCountries": {
      "get": {
        "tags": [
          "Order"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "integer",
                    "format": "int32"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "integer",
                    "format": "int32"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "integer",
                    "format": "int32"
                  }
                }
              }
            }
          }
        }
      }
    },

```

are recognized as `dynamic` not i.e. `List<int>`

BTW: You can recognize and remedy like this: 
```
        var value = response?.body;

        var list_int = List<int>.from(value);
```
...but it should already have been recognized as `List<int>`.

Code generated in : `*.swagger.dart`

```
  ///
  @Get(path: '/Order/firmCountries')
  Future<chopper.Response> orderFirmCountriesGet();
```

Code generated in: `*.swagger.chopper.dart`
```
  @override
  Future<Response<dynamic>> orderFirmCountriesGet() {
    final $url = '/Order/firmCountries';
    final $request = Request('GET', $url, client.baseUrl);
    return client.send<dynamic, dynamic>($request);
  }
```
Here I Expected not `Future<Response<dynamic>>` to be returned, but `Future<Response<List<int>>>` instead.

**To Reproduce**
Yaml files
[pubspec.yaml.txt](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/7739437/pubspec.yaml.txt)
[build.yaml.txt](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/7739439/build.yaml.txt)

Swagger file:
[mwork_api.swagger.txt](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/7739447/mwork_api.swagger.txt)

**Library version used:**
`2.2.10`

**Comment by Vovanella95** [comment]
Hi @RoarGronmo 
thanks for raising and issue. Will try to check it soon!

**Comment by Vovanella95** [comment]
Hi @RoarGronmo  please check 2.3.0 version
