### ISSUE TITLE
2.3.0 causes build warnings with no explanation

### ISSUE THREAD

**Issue by RoarGronmo** [epam-cross-platform-lab/swagger-dart-code-generator#291]
**Describe the bug**
Getting warnings like this: `swagger_code_generation:swagger_dart_code_generation on swaggers/mwork_api.swagger:[Frm]` on all generated types. The warning does not tell what the problem might be...

**To Reproduce**
Build with this `swagger` file on `2.3.0`

[swagger.json.txt](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/7763033/swagger.json.txt)

**Expected behavior**
Please provide what the problem is in the warning.

**Library version used:**
`2.3.0`

**Additional context**
The problem is not severe, the code produced seems to work as expected.

**Comment by fryette** [comment]
Is it possible to share swagger file?

**Comment by RoarGronmo** [comment]
The swagger file is included above (linked as 'swagger.json.txt') it is renamed to .txt since github doesn't accept files ending with .swagger.

**Comment by Vovanella95** [comment]
@RoarGronmo  Fixed in 2.3.1, I forgot to remove prints in generator :D
