### ISSUE TITLE
doesn't seem to be generating all enums

### ISSUE THREAD

**Issue by rcloss** [epam-cross-platform-lab/swagger-dart-code-generator#294]
When I generate the generated code my <redacted>.swagger.enums.dart doesn't seem to contain all the enum types, I've attached a snippet of a schema and it's generated the enums for postType and conversationType, but it's not generating them for the nested payload->type enum. 

So when it tries to declare the following

`final enums.GetPostResponseConversationMessagesItem$PayloadType? type;` it fails because that doesn't exist, is it just a yaml setting update that I'm missing that would fix this or is it a bug? Just looking for some guidance on this

`"postType": {
                  "type": "string",
                  "description": "Type of post",
                  "enum": ["text", "stylizedText", "image", "animated", "urlText", "quoted", "audio", "threadMessage", "threadResponse", "status", "social"]
              },
              "conversationType": {
                  "type": "string",
                  "description": "Type of conversation eg Post, Chat, Group, Thread",
                  "enum": ["Post", "Chat", "Group", "Thread"]
              },
              "payload": {
                  "type": "object",
                  "description": "Post content payload",
                  "properties": {
                    "message": {
                        "type": "string",
                        "description": "Body of comment"
                    },
                    "type": {
                        "type": "string",
                        "description": "Type of comment",
                        "enum": ["text", "stylizedText", "image", "animated", "urlText", "quoted", "audio", "threadMessage", "threadResponse", "status", "social"]
                    }
                  }
              },`

**Comment by fryette** [comment]
Hi!
Now most of us are on vacation.
We will take a look at it in 1 or 2 weeks, thanks!

**Comment by fryette** [comment]
@rcloss could you please share a full snippet of the swagger?

**Comment by fryette** [comment]
Closed as no customer response.
