### ISSUE TITLE
[BUG] additionalProperties key from schema is not handled correctly

### ISSUE THREAD

**Issue by dJani97** [epam-cross-platform-lab/swagger-dart-code-generator#295]
**Describe the bug**
Using "additionalProperties" in a definition causes the generated field to be of type `Object`.

**To Reproduce**
The swagger json can be found in this [example on swaggerhub](https://app.swaggerhub.com/apis/jani7/Demo/1.0).

Running `swagger-dart-code-generator` on this json results in the `ExampleDTO` having a generic `Object? examples` field instead of `Map<String, List<EmbeddedExampleDTO>> examples` described in the swagger file.

Here is a snippet from the generated Dart class:

    @JsonSerializable(explicitToJson: true)
    class ExampleDTO {
      ExampleDTO({
        this.examples,
      });
    
      factory ExampleDTO.fromJson(Map<String, dynamic> json) =>
          _$ExampleDTOFromJson(json);
    
      @JsonKey(name: 'examples')
      final Object? examples;
    
      // (...)
    }

**Expected behavior**
The `example` field should be generated as `Map<String, List<EmbeddedExampleDTO>> examples`.

For example, the `Export > Client SDK > Dart` function on SwaggerHub seems to generate a proper implementation:

    class ExampleDTO {
      Map<String, List<EmbeddedExampleDTO>> examples = {};
      
      // (...)
    }

**Library version used:**
swagger_dart_code_generator: ^2.3.2

**Additional context**
I noticed that this problem was already referenced in https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/58 which was closed with the message "fixed all issues in 1.2.0 version".

**Comment by fryette** [comment]
I think that feature can be quite easily implemented.

We will add it to our roadmap and will try to deliver it this month.

Documentation: https://swagger.io/docs/specification/data-models/dictionaries/

**Comment by fryette** [comment]
So, we double-checked this issue and seems **Expected** result is not achievable.
If a property has `additional properties` it means that it's a dictionary. 
For example:

```
  ExampleDTO:
    type: object
    required:
      - examples
    properties:
      examples:
        type: object
        properties:
          default:
            type: string
        additionalProperties:
          type: array
          items:
            $ref: '#/definitions/EmbeddedExampleDTO'
```

We are going to change generated field from `Object` to `Map<String, dynamic>` and let users parse it as they want.
