### ISSUE TITLE
[BUG] Generation fails for a list of enum

### ISSUE THREAD

**Issue by mikedigit** [epam-cross-platform-lab/swagger-dart-code-generator#305]
In my swagger file I have enums, one of them named `CRMAPIPortfolioControllersDtoConsentStatusEnum` which maps correctly if used alone but won't if in a List of enum.
To illustrate what I'm saying here is an extract of my *.swagger.dart which creates a chopper call with following signature:

Future<chopper.Response<CRMDomainReadModelsProfilesPagedDataResult1CRMInfrastructureElasticSearchReadModelsContactReadModel>>
v1PortfolioGet(
          {bool? sortAsc,
          enums.CRMInfrastructureElasticSearchContactSortColumn? sortColumn,
          String? from,
          String? to,
          bool? withArchivedContacts,
          String? searchTerm,
          enums.ProfileKindEnum? profileKinds,
          enums.SourceEnum? sources,
          `List<CRMAPIPortfolioControllersDtoConsentStatusEnum>?` consentStatuses,     <-------------- problem here
          int? size,
          int? page}) {
    generatedMapping.putIfAbsent(
        CRMDomainReadModelsProfilesPagedDataResult1CRMInfrastructureElasticSearchReadModelsContactReadModel,
        () => CRMDomainReadModelsProfilesPagedDataResult1CRMInfrastructureElasticSearchReadModelsContactReadModel
            .fromJsonFactory);
            
As you can see, `List<CRMAPIPortfolioControllersDtoConsentStatusEnum>` is generated in place of `List<enums.CRMAPIPortfolioControllersDtoConsentStatusEnum>` which result in an import error.

If I add `enums.` manually everything works as expected.

Please let me know if you need to know more.

**Comment by Vovanella95** [comment]
Hi @mikedigit 

Thanks for raising issue. I will check it.

**Comment by Vovanella95** [comment]
Hi again @mikedigit !

Could you please share swagger file (or part of it) with this problem?

**Comment by Vovanella95** [comment]
@mikedigit  sure. vovanella95@mail.ru

Also you can share only part of swagger file to avoid privacy issues

**Comment by Vovanella95** [comment]
@mikedigit I've fixed your file in latest version (2.3.7+). Please let us know if something wrong

**Comment by Vovanella95** [comment]
@mikedigit I've fixed your file in latest version (2.3.7+). Please let us know if something wrong

**Comment by mikedigit** [comment]
> @mikedigit I've fixed your file in latest version (2.3.7+). Please let us know if something wrong

works like a charm thanks !
