### ISSUE TITLE
[BUG] int enum generates "anonymous" labels 

### ISSUE THREAD

**Issue by fncap** [epam-cross-platform-lab/swagger-dart-code-generator#307]
Take a look on the following spec

```json
"TenantAvailabilityState": {
  "enum": [
    1,
    2,
    3
  ],
  "type": "integer",
  "format": "int32",
  "x-enumNames": [
    "Available",
    "InActive",
    "NotFound"
  ]
},
```

this produce following Dart

```dart
enum TenantAvailabilityState {
  @JsonValue('swaggerGeneratedUnknown')
  swaggerGeneratedUnknown,
  @JsonValue(1)
  value_1,
  @JsonValue(2)
  value_2,
  @JsonValue(3)
  value_3
}

const $TenantAvailabilityStateMap = {
  TenantAvailabilityState.value_1: '1',
  TenantAvailabilityState.value_2: '2',
  TenantAvailabilityState.value_3: '3'
};
```

What I'm expecting is an `enum` generated with same labels that are listed in `x-enumNames` spec's field, instead of `value_1`, `value_2` and `value_3`!

Isn't it?

**Comment by Vovanella95** [comment]
Hi @fncap , thanks for raising issue. Actually, it's not a bug and looks like cool feature. I will try to take a look on it

**Comment by fryette** [comment]
Link with all possibilities of annotation enums:
https://stackoverflow.com/questions/66465888/how-to-define-enum-mapping-in-openapi
