### ISSUE TITLE
[FEATURE] Get opportunity deserialize bool value type from "1" or "0'

### ISSUE THREAD

**Issue by ATeteryatnikov** [epam-cross-platform-lab/swagger-dart-code-generator#319]
My server mark the property like boolean and the generated swagger file was created with boolean type. In fact server send 1/0 value and deserialization fails. I don't have opportunity for fix it on server side.

I look on another plugins from openapi:
https://github.com/OpenAPITools/openapi-generator/tree/master/docs/generators
(openapi not work for me because it not support nullsafety feature)

- one plugin named 'dart' parsed bool with variants: 

```
 case 'bool':
          if (value is bool) {
            return value;
          }
          final valueString = '$value'.toLowerCase();
          return valueString == 'true' || valueString == '1';
```
   

- another one 'dart-dio-next' offer use array of Serializers and u can override it for use custom serialization/deserialization.

I think it will be a good feature :)

**Comment by Vovanella95** [comment]
Hi @ATeteryatnikov ,
It's interesting feature.

It's correct that field defined as bool in yaml, but in fact there are integer values?

**Comment by ATeteryatnikov** [comment]
@Vovanella95 
Yes. Generally is correct. But I use json.
It's look like:
```
{
    "type": "boolean"
}
```
In fact server send integer values (1 or 0) 
```
{
     "expired": 0
}
````

**Comment by Vovanella95** [comment]
@ATeteryatnikov  I will try to check it next week

**Comment by fryette** [comment]
@ATeteryatnikov We are going to support only official documentation from swagger. If in swagger you see boolean than boolean should be returned.

You have two options
1) Define custom response(check Readme) and deserialize it
2) Fix the swagger file.
