### ISSUE TITLE
[BUG] Support for deepObject for query parameters

### ISSUE THREAD

**Issue by alextarrago** [epam-cross-platform-lab/swagger-dart-code-generator#320]
Support for deepObject notation for query parameters. 

This spec does not generate the expected behaviour.

```
/service-categories:
    get:
      operationId: listCategories
      tags:
        - ServiceCategories
      parameters:
        - $ref: '#/components/parameters/ServiceCategoryCriteria'
```

```
ServiceCategoryCriteria:
      type: object
      properties:
        parentId:
          $ref: '#/components/schemas/LongFilter'
        onlyServicesActive:
          type: boolean
          default: false
        enabled:
          $ref: '#/components/schemas/BooleanFilter'
```

Intercepting the parameters in the client interceptor gives us the following code:

`{q: Instance of 'ServiceCategoryCriteria'}`

Some guidance on here? :)

**Comment by alextarrago** [comment]
Hi @Vovanella95, thanks for the fast reply!
How can I share the yaml file to you, privately?

Thanks.

**Comment by Vovanella95** [comment]
@alextarrago  sure, vovanella95@mail.ru

**Comment by Vovanella95** [comment]
@alextarrago  OK I have generated your example. I have request with parameter ServiceCategoryCriteria. What is the issue? 

`/service/categories` method is generated, it has parameter named q and type `ServiceCategoryCriteria`

**Comment by Vovanella95** [comment]
@alextarrago  closing the issue due to no response. Please reopen it if it actual

**Comment by calebdeji** [comment]
Hi @Vovanella95 ,

similar to this https://github.com/OAI/OpenAPI-Specification/issues/1706, 

```yaml
parameters:
        - name: filter
          in: query
          schema:
            type: object
          style: deepObject
          explode: true
          description: Filter by category ID
```

The query param generated from this 
```dart
_cmsRemoteDataSource.subCategoriesGet(
          filter: {r'[category][id][$eq]': 25},
        )
```

is `filter.[category][id][$eq]=25`, the dot before [category] shouldn't be there.
