### ISSUE TITLE
[BUG] Required values is nullable

### ISSUE THREAD

**Issue by mohachouch** [epam-cross-platform-lab/swagger-dart-code-generator#324]
Thank you very much for this library

**Describe the bug**
Required value in swager file is nullable when generating.

**To Reproduce**
 "BrowserInfoPostDto": {
        "required": [
          "acceptHeader",
          "colorDepth",
          "javaEnabled",
          "javascriptEnabled",
          "language",
          "timeZoneOffset",
          "userAgent"
        ],
        "type": "object",
        "properties": {
          "acceptHeader": {
            "type": "string"
          },
          "javaEnabled": {
            "type": "boolean"
          },
          "javascriptEnabled": {
            "type": "boolean"
          },
          "language": {
            "type": "string"
          },
          "colorDepth": {
            "type": "integer",
            "format": "int32"
          },
          "screenHeight": {
            "type": "integer",
            "format": "int32"
          },
          "screenWidth": {
            "type": "integer",
            "format": "int32"
          },
          "timeZoneOffset": {
            "type": "string"
          },
          "userAgent": {
            "type": "string"
          }
        },

Output
@JsonKey(name: 'acceptHeader')
  final String? acceptHeader;
  @JsonKey(name: 'javaEnabled')
  final bool? javaEnabled;
  @JsonKey(name: 'javascriptEnabled')
  final bool? javascriptEnabled;
  @JsonKey(name: 'language')
  final String? language;
  @JsonKey(name: 'colorDepth')
  final int? colorDepth;
  @JsonKey(name: 'screenHeight')
  final int? screenHeight;
  @JsonKey(name: 'screenWidth')
  final int? screenWidth;
  @JsonKey(name: 'timeZoneOffset')
  final String? timeZoneOffset;
  @JsonKey(name: 'userAgent')
  final String? userAgent;

**Expected behavior**
@JsonKey(name: 'acceptHeader')
  final String acceptHeader;
  @JsonKey(name: 'javaEnabled')
  final bool javaEnabled;
  @JsonKey(name: 'javascriptEnabled')
  final bool javascriptEnabled;
  @JsonKey(name: 'language')
  final String language;
  @JsonKey(name: 'colorDepth')
  final int colorDepth;
  @JsonKey(name: 'screenHeight')
  final int? screenHeight;
  @JsonKey(name: 'screenWidth')
  final int? screenWidth;
  @JsonKey(name: 'timeZoneOffset')
  final String timeZoneOffset;
  @JsonKey(name: 'userAgent')
  final String userAgent;

Thank you very much for your help

**Comment by Vovanella95** [comment]
Hi @mohachouch 

It's expected behaviour for this moment. We generating all required fields nullable. It's needed to have ability to use these models as request parameters, because (at least on our project) we should not send required fields sometimes.

I already have idea how to fix. We will generate separate models for Responses, and such models will have not-nullable fields

**Comment by mohachouch** [comment]
Thank you very much for your response and this wonderful work

**Comment by fryette** [comment]
I would suggest keeping it open to not forget fix it when we move to non nullable

**Comment by samarth-ramesh** [comment]
Hey @Vovanella95, any chance we can get the non-nullable required values (implemented vide #282)?

**Comment by Vovanella95** [comment]
Hi @samarth-ramesh , I will try to implement it in a week or two

**Comment by Vovanella95** [comment]
@samarth-ramesh  please let us know in case of issues. I have checked it on my swaggers but who knows :D

**Comment by samarth-ramesh** [comment]
Works now, thanks a lot :)

**Comment by Vovanella95** [comment]
@jhancock4d  please share example of swagger
