### ISSUE TITLE
[BUG] Object is not typed correctly when using allOf.

### ISSUE THREAD

**Issue by michalsrutek** [epam-cross-platform-lab/swagger-dart-code-generator#329]
**Describe the bug**
Object is not typed correctly when using allOf.

**To Reproduce**

Let's say I have the following swagger.

```json
{
    "openapi": "3.0.3",
    "info": {
        "title": "Test API",
        "version": "1.0.0"
    },
    "paths": {
        "/test": {
            "get": {
                "operationId": "testRetrieve",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Test"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Customer": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "readOnly": true
                    },
                    "email": {
                        "type": "string",
                        "format": "email",
                        "readOnly": true
                    }
                },
                "required": [
                    "email",
                    "name"
                ]
            },
            "Test": {
                "type": "object",
                "properties": {
                    "customer": {
                        "allOf": [
                            {
                                "$ref": "#/components/schemas/Customer"
                            }
                        ],
                        "readOnly": true
                    }
                },
                "required": [
                    "customer"
                ]
            }
        }
    }
}
```

This produces the following code.

```dart
@JsonSerializable(explicitToJson: true)
class Test {
  Test({
    this.customer,
  });

  factory Test.fromJson(Map<String, dynamic> json) => _$TestFromJson(json);

  @JsonKey(name: 'customer')
  final dynamic customer;

  ...
}
```

Note that the `customer` property is not typed.

**Expected behavior**

I expect the `customer` property to be typed, as shown below.

```dart
@JsonSerializable(explicitToJson: true)
class Test {
  Test({
    this.customer,
  });

  factory Test.fromJson(Map<String, dynamic> json) => _$TestFromJson(json);

  @JsonKey(name: 'customer')
  final Customer? customer;

  ...
}
```

**Swagger specification link**
[Link to swagger/OpenApi documentation](https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/)

**Library version used:**
2.3.10

**Comment by Vovanella95** [comment]
Hi @michalsrutek 

Thanks for raising issue. I will fix your issue, but pay attention, that actually, customer is not Customer. If 'allOf' has not only ref, but additional properties - we should create special class, contains all fields of Customer + all properties, mentioned in it. 

So generator will generate Customer when there are no properties inside of allOf, and dynamic in cases, when you add it, for example, like this:

`Test:
      type: object
      properties:
        customer:
          allOf:
            - $ref: '#/components/schemas/Customer'
            - properties:
                id:
                  type: string
                  x-annotation-builtinType: string
                  x-annotation-inherited: true
          readOnly: true
      required:
        - customer`

**Comment by Vovanella95** [comment]
@michalsrutek  enjoy 2.3.12 version :)

**Comment by michalsrutek** [comment]
@Vovanella95 Perfect. Thank you for your amazing work! 👍
