### ISSUE TITLE
[BUG] Enum type is not serialized using its toJson method

### ISSUE THREAD

**Issue by jonasanker** [epam-cross-platform-lab/swagger-dart-code-generator#335]
**Describe the bug**
When calling an API call with a request class that has an enum type property, a `NoSuchMethodError` is thrown as no `toJson` method was found for the enum type.

It could seem that the generated models code are not using the appropriate `enumClassnameToJson()` method when serializing the enum value.

Error Message
```
NoSuchMethodError: Class 'PaymentType' has no instance method 'toJson'.
Receiver: Instance of 'PaymentType'
Tried calling: toJson
```

Stacktrace
```
E/flutter ( 6760): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Converting object to an encodable object failed: Instance of 'InitatePurchaseRequest'
E/flutter ( 6760): #0      _JsonStringifier.writeObject (dart:convert/json.dart:688:7)
E/flutter ( 6760): #1      _JsonStringStringifier.printOn (dart:convert/json.dart:877:17)
E/flutter ( 6760): #2      _JsonStringStringifier.stringify (dart:convert/json.dart:862:5)
E/flutter ( 6760): #3      JsonEncoder.convert (dart:convert/json.dart:262:30)
E/flutter ( 6760): #4      JsonCodec.encode (dart:convert/json.dart:172:45)
E/flutter ( 6760): #5      JsonConverter.encodeJson (package:chopper/src/interceptor.dart:245:42)
E/flutter ( 6760): #6      JsonConverter.convertRequest (package:chopper/src/interceptor.dart:239:12)
E/flutter ( 6760): #7      ChopperClient._encodeRequest (package:chopper/src/base.dart:178:23)
E/flutter ( 6760): #8      ChopperClient._handleRequestConverter (package:chopper/src/base.dart:277:26)
E/flutter ( 6760): #9      ChopperClient.send (package:chopper/src/base.dart:301:21)
E/flutter ( 6760): #10     _$CoffeecardApiV2._apiV2PurchasesPost (package:coffeecard/generated/api/coffeecard_api_v2.swagger.swagger.chopper.dart:42:10)
E/flutter ( 6760): #11     CoffeecardApiV2.apiV2PurchasesPost (package:coffeecard/generated/api/coffeecard_api_v2.swagger.swagger.dart:57:12)
E/flutter ( 6760): #12     PurchaseRepository.initiatePurchase (package:coffeecard/data/repositories/v2/purchase_repository.dart:17:33)
```

**To Reproduce**

Below code snippet calls the generated API code
```dart
Future<InitiatePurchaseResponse> initiatePurchase(
    int productId,
    PaymentType paymentType,
  ) async {
    return await _api.apiV2PurchasesPost(
      body: InitatePurchaseRequest(
        productId: productId,
        paymentType: paymentType,
      ),
    );
}
```

The Post method takes the below `InitatePurchaseRequest` in the HTTP body. Notice that the property `paymentType` is an enum

**InitatePurchaseRequest**
```json
"InitatePurchaseRequest": {
    "type": "object",
    "description": "Initiate a new purchase request",
    "additionalProperties": false,
    "required": [
        "productId",
        "paymentType"
    ],
    "properties": {
        "productId": {
            "type": "integer",
            "description": "Id of product to be purchased",
            "format": "int32",
            "example": 1
        },
        "paymentType": {
            "description": "Payment Type used to fulfill purchase",
            "example": "MobilePay",
            "oneOf": [
                {
                    "$ref": "#/components/schemas/PaymentType"
                }
            ]
        }
    }
}
```
**PaymentType**
```json
"PaymentType": {
    "type": "string",
    "description": "PaymentType represents the type of Payment which is used to fulfill a purchase",
    "x-enumNames": [
        "MobilePay"
    ],
    "enum": [
        "MobilePay"
    ]
}
```

**Expected behaviour**
The Request class with an enum property is serialized correctly and a successful HTTP request is sent to the server.

**Swagger specification link**
Link to [Cafe Analog CoffeeCard API v2](https://beta-v2.analogio.dk/coffeecard/swagger/v2/swagger.json)

**Library version used:**
```yaml
dependencies:
  chopper: 4.0.4

dev_dependencies:
  chopper_generator: 4.0.3
  json_serializable: 6.1.3
  swagger_dart_code_generator: 2.3.2
```

**Additional context**
None. Just tag me if more information is needed

**Comment by Vovanella95** [comment]
Hi @jonasanker , actually good issue. Will try to fix it soon!

**Comment by Vovanella95** [comment]
Hi @jonasanker 

`InitatePurchaseRequest.paymentType` is dynamic because it's `oneOf`. When you set dynamic field some value - it should be convertable to json. Enum is not convertable to json by default. So you need just use some String value instead of enum. Method `jsonEncode` is not working with enums.

Let me demonstrate an example:

`
void main() {
  final aa = jsonEncode(SomeClass('someThing').toJson()); // OK
  final bb = jsonEncode(SomeClass(MyEnum.one).toJson()); // NOT OK
  final cc = jsonEncode(MyEnum.one); // ALSO NOT OK
}

@JsonSerializable(explicitToJson: true)
class SomeClass {
  @JsonKey()
  final dynamic someField;

  SomeClass(this.someField);

  Map<String, dynamic> toJson() => _$SomeClassToJson(this);
}

enum MyEnum {
  one,
  two,
  three,
}
`

**Comment by Vovanella95** [comment]
@jonasanker  anyway if field not dynamic, but generated as enum - you can use Enum of course, because we add custom `toJson` methods to such fields. I'm closing the issue. Don't hesitate to contact us if something is not clear.
