### ISSUE TITLE
[FEATURE] implement toString for models

### ISSUE THREAD

**Issue by dJani97** [epam-cross-platform-lab/swagger-dart-code-generator#340]
**Is your feature request related to a problem? Please describe.**

A basic toString implementation on model classes would help with logging and debugging.

Currently toString is not overridden and `Instance of 'MyModel'` gets logged to the console.

**Describe the solution you'd like**

A basic toString implementation similar to what the IDE can generate, or even a simple call like `@override String toString() => jsonEncode(this);` would help to make logging more verbose.

**Comment by Vovanella95** [comment]
Hi @dJani97  actually good idea!

**Comment by Vovanella95** [comment]
Hi again @dJani97 

Feel free to use [prerelease](https://pub.dev/packages/swagger_dart_code_generator/versions/2.4.0-prerelease.3) version
