### ISSUE TITLE
[BUG] Json Schema Definition named "Query" generates invalid code

### ISSUE THREAD

**Issue by vipw** [epam-cross-platform-lab/swagger-dart-code-generator#343]
**Describe the bug**
If I add a definition to the swagger file with the name of query, the generated classes have a namespace collision with Chopper/annotations.dart's Query class.

**To Reproduce**
This swagger file reproduces the issue:
```{
  "swagger": "2.0",
  "info": {
    "description": "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.",
    "version": "1.0.0",
    "title": "Swagger Petstore",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "petstore.swagger.io",
  "basePath": "/v2",
  "schemes": [
    "https",
    "http"
  ],
  "paths": {
    "/pet/findByStatus": {
      "get": {
        "summary": "Finds Pets by status",
        "description": "Multiple status values can be provided with comma separated strings",
        "operationId": "findPetsByStatus",
        "produces": [
          "application/xml",
          "application/json"
        ],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "description": "Status values that need to be considered for filter",
            "required": true,
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "available",
                "pending",
                "sold"
              ],
              "default": "available"
            },
            "collectionFormat": "multi"
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Pet"
              }
            }
          },
          "400": {
            "description": "Invalid status value"
          }
        }
      }
    }
  },
  "definitions": {
    "Query": {
      "type": "object"
    },
    "Pet": {
      "type": "object"
    }
  }
}
```

**Expected behavior**
I would expect the @chopper.Query annotation to be used instead of @Query. This will allow common words like Query, Path, Body, Header, etc. to be used in the API .

**Library version used:**
2.3.13

**Additional context**
I'll start working on a PR for this.

**Comment by Vovanella95** [comment]
Hi @vipw  could you put code into triple quotes? ```

Code will be readable then and I will fix it

**Comment by Vovanella95** [comment]
@vipw  anyway I fixed your issue. Please check 2.4.1 version

**Comment by vipw** [comment]
I was able to fix it by changing `_getParameterAnnotation()` in `swagger_requests_generator.dart` by prefixing "chopper." to the symbol passed to `refer()`.

But that was just enough to unblock my single issue with Query. I think the other annotations should also be changed to use the chopper. prefix to avoid collisions.

**Comment by Vovanella95** [comment]
@vipw  Just check latest version, you don't need any workaround 😄

**Comment by vipw** [comment]
This is still broken in 2.4.2, the generated code still has 
`import 'package:chopper/chopper.dart';`

Any generated class named Query, Path, Get, Post, etc. will still fail to compile. The generated code should import all libraries with "as xyz" syntax and then only reference imported classes with the imported namespaces.

**Comment by Vovanella95** [comment]
Hi @vipw , yes we import chopper to support chopper annotations. Your file is generated without errors, so problem in usage of package, right?

Could you provide example of failing code?

**Comment by Vovanella95** [comment]
Do you have collect list of exception classes? We can add it to our lib and generate it with dollar.

**Comment by vipw** [comment]
@Vovanella95 The example swagger above does generate valid code, but if a "Query" object is included as a parameter (for example as the body of a POST), then the generated code is like this:

```
  ///Add a new query
  ///@param body Query object that needs to be created in the database
  Future<chopper.Response<Query>> addQuery(
      {required num? objPro, required Query? body}) {
    generatedMapping.putIfAbsent(Query, () => Query.fromJsonFactory);

    return _addQuery(objPro: objPro, body: body);
  }
```

The Query in Query.fromJsonFactory is resolved as chopper/lib/src/annotations.dart::Query.

What I would propose as a systematic solution is have all the imports to be namespaced.

Chopper is actually being double-imported, and `Response` is referred to as `chopper.Response`. 
```
import 'package:chopper/chopper.dart';
import 'dart:convert';

import 'client_mapping.dart';
import 'package:chopper/chopper.dart' as chopper;
```

You can drop the `import 'package:chopper/chopper.dart';`, use only the `import 'package:chopper/chopper.dart' as chopper;`, and make the annotations like e.g. `@chopper.Path` instead of `@Path`, these sorts of namespace collisions can be avoided.

The same should probably also be done for the json_annotation and and collection imports, but I think it's far less likely anyone will try naming an object `JsonKey` or `DeepCollectionEquality`. But you know, sometimes you're just the client and don't get to choose the server's API...

**Comment by Vovanella95** [comment]
Hi @vipw really nice catch. I will take a look into it soon

**Comment by Vovanella95** [comment]
Possible it's really better just to use chopper. before each Chopper class. Will try to implement it this way

**Comment by Vovanella95** [comment]
@vipw  looks like it's not possible to use chopper annotations without importing chopper directly. We will have compilation error in this case.

```dart
chopper.@ChopperApi()
```

**Comment by Vovanella95** [comment]
@vipw  thanks looks like my syntax knowledge is poor)))

I will make fix as soon as possible

**Comment by Vovanella95** [comment]
Hi @vipw, I tried to implement this thing, and have problem with chopper. chopper generated file is not valid because it's requires chopper import. 

```dart
class _$PetServiceJson extends PetServiceJson {
  _$PetServiceJson([ChopperClient? client]) { //not valid line
    if (client == null) return;
    this.client = client;
  }
```

Any other ideas how to fix it?

**Comment by fryette** [comment]
Why simply not generate response class with name `$Query` instead of looking into workaround for chopper?
