### ISSUE TITLE
[BUG] example project fails to generate code

### ISSUE THREAD

**Issue by vipw** [epam-cross-platform-lab/swagger-dart-code-generator#346]
**Describe the bug**
With a fresh checkout of this project (d27237607d3b865c29379ae2cb1cdba08e459f7b), the example fails to generate code.

**To Reproduce**
cd to the example subdirectory and run:
`flutter pub get`
`flutter pub run build_runner build --delete-conflicting-outputs`

**Expected behavior**
Classes to be generated for the swagger petstore example.

**Library version used:**
d27237607d3b865c29379ae2cb1cdba08e459f7b

**Additional context**
The code that's being generated has paths in the `export` 
Output:
```
[SEVERE] swagger_dart_code_generator:swagger_dart_code_generator on input_folder/swagger_dart_code_generator_temp.dart (cached):

Could not format because the source could not be parsed:

line 2, column 61 of .: Expected to find ';'.
  ╷
2 │ export 'input_folder\pet_service_swagger.swagger.dart' show InputFolder\petServiceSwagger;
```

**Comment by Vovanella95** [comment]
@vipw  woah it's nice catch. could you share your swagger file name?

**Comment by vipw** [comment]
It's using the default swagger files from the example.
```
input_urls:
             - "https://raw.githubusercontent.com/epam-cross-platform-lab/swagger-dart-code-generator/master/example/input_folder/pet_service_json.json"
             - https://raw.githubusercontent.com/epam-cross-platform-lab/swagger-dart-code-generator/master/example/input_folder/pet_service_yaml.yaml
```

I think the files are downloaded to `input_folder` which the generator then uses.

**Comment by Vovanella95** [comment]
@vipw  Looks like problem in slashes. I am working on macOS machine. Will check it on my Windows laptop

**Comment by ByronHolt** [comment]
Experiencing issues with slashes on windows, everything above version 2.3.13 is not working.

**Comment by Vovanella95** [comment]
@ByronHolt  yes yes, the main priority for us -  to fix Windows for now

**Comment by Vovanella95** [comment]
Hi @ByronHolt I've fixed your issue, but lost phone and cannot sign in with two factor auth at weekend. Today evening I will push changes and close this issue. Thanks for waiting.
