### ISSUE TITLE
Add ability to pass interceptors into the create() method of generated ChopperService 

### ISSUE THREAD

**Issue by denisano** [epam-cross-platform-lab/swagger-dart-code-generator#349]
The static create() method builds ChopperClient instance and pass it into private API impl class. ChopperClient class supports 'interceptors' parameter that allows to pass list of interceptors. It is very usefull ability of ChopperClient. But currently there is no (in the generated client) ability to pass 'interceptors' into the create() method. Interceptors give full control on request/response events with 'onRequest()' and 'onResponse()' listeners. 

Currently we are using interceptors to implement log requests/responses (Chopper HttpLoggingInterceptor), generate Curl-code (Chopper CurlInterceptor), do jwt-based authentication (custom interceptor implementation) and some other tasks. All these interceptors are working fine, but to support it we need to make replace generated 'create()' method with self version. Below the code demonstrated the diffs:

**Current generated code**:
```
@ChopperApi()
abstract class MyAppApi extends ChopperService {
  static MyAppApi create(
      {ChopperClient? client,
      String? baseUrl}) {
    if (client != null) {
      return _$MyAppApi(client);
    }

    final newClient = ChopperClient(
        services: [_$MyAppApi()],
        converter: $JsonSerializableConverter(),
        baseUrl: baseUrl ?? 'http://');
    return _$MyAppApi(newClient);
  }
```

**Corrected code that supports passing the 'interceptors'**:
```
@ChopperApi()
abstract class MyAppApi extends ChopperService {
  static MyAppApi create(
      {ChopperClient? client,
      String? baseUrl,
      Iterable<dynamic>? interceptors}) {
    if (client != null) {
      return _$MyAppApi(client);
    }

    final newClient = ChopperClient(
        services: [_$MyAppApi()],
        converter: $JsonSerializableConverter(),
        interceptors: interceptors ?? [],
        baseUrl: baseUrl ?? 'http://');
    return _$MyAppApi(newClient);
  }
```

**Comment by Vovanella95** [comment]
Hi @DenisAnkh !
Actually, you can do this, creating custom chopper client and customise it as you want. But if it's comfortable to have interceptors in .create method - OK, i think it's easy fix.

**Comment by DenisAnkh** [comment]
Hi @Vovanella95 !

> Actually, you can do this, creating custom chopper client and customise it as you want.
I have tried this, but there is a problem - Chopper Client() constructor requires supply 'services' option that must contain instance of private class `services: [_$MyAppApi()]`, but this private class is not available because it is private. 

> But if it's comfortable to have interceptors in .create method - OK, i think it's easy fix.
I think it is an easy but very useful fix that would address the issue.

**Comment by Vovanella95** [comment]
@DenisAnkh  I will provide fix next week. Thanks for raising issue!

**Comment by Vovanella95** [comment]
Hi @DenisAnkh I've fixed you issue but lost my phone and can not sign in at weekend :D 

Today evening I will push changes and close this issue. Just keep you informed

**Comment by DenisAnkh** [comment]
Hi @Vovanella95! Thank you! Looking forward the feature :)
