### ISSUE TITLE
[BUG] an empty file \lib\swagger_dart_code_generator_temp.dart remains after successful build

### ISSUE THREAD

**Issue by dJani97** [epam-cross-platform-lab/swagger-dart-code-generator#352]
**Describe the bug**
An empty file `\lib\swagger_dart_code_generator_temp.dart` is left behind after each build. I don't recall having this problem in earlier versions, but I don't know exactly when it got introduced.

**To Reproduce**

    git clone https://github.com/epam-cross-platform-lab/swagger-dart-code-generator
    cd .\swagger-dart-code-generator\example
    flutter pub get
    flutter packages pub run build_runner build --delete-conflicting-outputs

**Expected behavior**
I would expect temp files to be deleted, or be used outside of the `/lib` folder.
I also suggest removing this file not only in case of success, but also in case of a build failure.

**Library version used (latest of everything, as of today):**
    OS: Windows 11
    Flutter 2.10.2 • channel stable
    swagger_dart_code_generator: ^2.4.2
    chopper_generator: ^4.0.5
    json_annotation: ^4.4.0
    json_serializable: ^6.1.4

**Comment by Vovanella95** [comment]
Fixed here: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/pull/353
