### ISSUE TITLE
[QUESTION] custom authentication

### ISSUE THREAD

**Issue by alexproca** [epam-cross-platform-lab/swagger-dart-code-generator#357]
**Please describe a problem.**
How should custom authentication be implemented? Right now I need to add a custom Authorization header and I manually modify the generated chopper code to add a Header interceptor that will compute and add the bearer jwt

**Describe the solution you'd like**
Some way to extend the client so custom interceptors can be added or just pass them at the client initialization without passing the whole chopper client.

**Comment by Vovanella95** [comment]
Hi @alexproca , you should not add custom headers to your requests. Just use interceptors for it. create your own class extends Interceptor and override onRequest method.

For example: 
```dart
class AuthInterceptor extends RequestInterceptor {
  @override
  FutureOr<Request> onRequest(Request request) {
    request.headers.addAll({
      'xUserName': 'myUser1',
      'xToken': 'token',
    });

    return request;
  }
}
```

and then when you're creating chopper client you can do next:

```dart
final petsApi = PetServiceYaml.create(
    interceptors: [
      AuthInterceptor(),
    ],
  );
```


Is it fix your problem?

**Comment by alexproca** [comment]
Thank your for your answer. I'm looking for something like that but the generated code doesn’t have the option to pass interceptors

```
@ChopperApi()
abstract class PetServiceYaml extends ChopperService {
  static PetServiceYaml create({ChopperClient? client, String? baseUrl}) {
    if (client != null) {
      return _$PetServiceYaml(client);
    }

    final newClient = ChopperClient(
        services: [_$PetServiceYaml()],
        converter: $JsonSerializableConverter(),
        baseUrl: baseUrl ?? 'http://petstore.swagger.io/v2');
    return _$PetServiceYaml(newClient);
  }
```

[Generated example](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/blob/master/example/lib/swagger_generated_code/pet_service_yaml.swagger.dart)

**Comment by Vovanella95** [comment]
@alexproca  can you specify version of generator you're using?

**Comment by alexproca** [comment]
<img width="777" alt="Screenshot 2022-03-09 at 10 41 11" src="https://user-images.githubusercontent.com/252961/157404556-fa666586-40c8-4908-bbcd-564a0e05d4c1.png">

**Comment by alexproca** [comment]
I changed version from 'any' to 2.4.3 and now the API has the interceptors parameter. Thank you @Vovanella95 for your input.

<img width="563" alt="Screenshot 2022-03-09 at 11 23 36" src="https://user-images.githubusercontent.com/252961/157412449-cac8194f-3b17-46fe-91b0-1745ce7ed9dc.png">

**Comment by Vovanella95** [comment]
@alexproca  Yes I asked for version because I remember I added this feature recently :) I'm closing the issue. Please let us know in case of questions.

**Comment by alexproca** [comment]
As a suggestion maybe you can replace in the readme the 'any' version with 2.4.3

**Comment by Vovanella95** [comment]
Good idea actually :)

**Comment by alexproca** [comment]
I had to also solve a conflict with a version override

```
dependency_overrides:
  json_annotation: ^4.1.0
```
