### ISSUE TITLE
[BUG] How to generate models without hashcode override 

### ISSUE THREAD

**Issue by bawantha** [epam-cross-platform-lab/swagger-dart-code-generator#359]
Could not resolve annotation for `int get hashCode`.
  ╷
1 │ @override
  │ ^^^^^^^^^
  ╵

**Comment by Vovanella95** [comment]
Hi @bawantha 

We can add option to not generate it if it's not needed. But what is actual problem?

**Comment by bawantha** [comment]
```[SEVERE] json_serializable:json_serializable on lib/swagger_generated_code/generic_search.models.swagger.dart (cached):

line 1, column 384153 of package:app/swagger_generated_code/generic_search.models.swagger.dart: Could not resolve annotation for `int get hashCode`.
  ╷
1 │ @override
  │ ^^^^^^^^^
  ╵
[SEVERE] Failed after 248ms
```
I'm getting this error, I don't know why

**Comment by Vovanella95** [comment]
@bawantha  could you please share part of swagger code with this model? I will take a look into it

**Comment by Vovanella95** [comment]
@bawantha  ping

**Comment by Vovanella95** [comment]
![rasstroennyj-fanat-kriketa-1-768x385](https://user-images.githubusercontent.com/11267533/159286560-18788e2b-1f28-4560-8f21-a9bad8bd5070.jpeg)

**Comment by bawantha** [comment]
I'm sorry brother I cannot share the swagger with you, it's confidential If I have time I will recreate issue with different swagger, until then 👋

**Comment by Vovanella95** [comment]
@bawantha  You can share just part of it and modify it as you wish to keep confidential data. I just want to understand root cause to avoid such situations.
