### ISSUE TITLE
Chopper Authenticator Implementation

### ISSUE THREAD

**Issue by flowhorn** [epam-cross-platform-lab/swagger-dart-code-generator#360]
**Is your feature request related to a problem? Please describe.**
When initializing the api, i would like to pass a chopper Authenticator.

**Describe the solution you'd like**
For things like token-refresh, I need to use the Authenticator class instead of the interceptorts, to be able to retry the request with new tokens. You could pass these optionally in the constructor like you do with the interceptors.

Thank you very much, this project helps me a lot!

**Comment by Vovanella95** [comment]
Hi @flowhorn , why can't we do like this?

```dart
final petsApi = PetServiceYaml.create(client: ChopperClient(
    authenticator: MyAuthentificator();
  ));
```

**Comment by Vovanella95** [comment]
@flowhorn  OK I see :) I will add authenticator parameter to create method.

**Comment by flowhorn** [comment]
Thank you very much for your work!

**Comment by Vovanella95** [comment]
@flowhorn  your feature has been added in latest version of our generator. Please let us know in case if any issues.
