### ISSUE TITLE
[QUESTION] Need option to shorten model names

### ISSUE THREAD

**Issue by skiryuk** [epam-cross-platform-lab/swagger-dart-code-generator#361]
Now we have long model names on the project after generation. Is there a way to shorten them? 
Maybe in the settings specify a prefix that will be deleted?

![image](https://user-images.githubusercontent.com/18750948/159700417-d004bf90-3c5e-4e3a-98a9-7de4851b5587.png)

**Comment by Vovanella95** [comment]
Hi @skiryuk , it's interesting case. I think it's really specific, we need another way to avoid it. Possible we can create some kind of regex to modify model names. Need to think about it. 

Maybe you have some another ideas?

**Comment by skiryuk** [comment]
> Hi @skiryuk , it's interesting case. I think it's really specific, we need another way to avoid it. Possible we can create some kind of regex to modify model names. Need to think about it.
> 
> Maybe you have some another ideas?

Regular expression mean the post processing generated files? We had a similar idea to cut static the name at the beginning of the field, but with a regular expression more interesting.

We have seen here that the name is going from the namespace .NET
![image](https://user-images.githubusercontent.com/18750948/159713656-0e8e9170-155f-49fb-9557-3c00d318fbac.png)

**Comment by Vovanella95** [comment]
@skiryuk  not post processing. I can add this change to method, where we generating class name. Possible, it's easy to implement. Let me try to do this. I will let you know soon.

**Comment by skiryuk** [comment]
> @skiryuk not post processing. I can add this change to method, where we generating class name. Possible, it's easy to implement. Let me try to do this. I will let you know soon.

Thank you, it would be very cool

**Comment by Vovanella95** [comment]
@skiryuk 

you can do the next, to use this feature right now:

`pubspec.yaml`
```yaml
swagger_dart_code_generator:
  git: 
    url: git@github.com:epam-cross-platform-lab/swagger-dart-code-generator.git
    ref: version/2.4.6
```

`build.yaml`
```
cutFromModelNames: "V3"
```

**Comment by skiryuk** [comment]
As it turned out, the property is called `cut_from_model_names` and everything works with it, please add it to the documentation

**Comment by Vovanella95** [comment]
@skiryuk  already did :)
