### ISSUE TITLE
[QUESTION] Need option to split models into multiple files

### ISSUE THREAD

**Issue by skiryuk** [epam-cross-platform-lab/swagger-dart-code-generator#362]
Now we have on the project after the generation all models are folded into one file.
Is it possible to divide into several files, for example, by controller?
Can make such an option?

**Comment by Vovanella95** [comment]
Hi @skiryuk , we already have option to generate models to separate files. It's named `separate_models `. Are you want separate file for each model?

**Comment by Vovanella95** [comment]
@skiryuk  if you want to put all models into one file - you can have a lot of conflicts with same models names. What means group models on the controller api? Possible we can generate something help you to solve this

**Comment by Vovanella95** [comment]
It's possible to generate each model to separate file, but it contradicts our vision of generator. We can solve your problem in different way. I need just more details about issue you trying to solve.

**Comment by Vovanella95** [comment]
@skiryuk  Swagger can not guarantee, that Agents and Auth use different models. So we need to create separate file for each model. Why huge files is a problem? You don't need to modify or even open it.

**Comment by skiryuk** [comment]
> @skiryuk Swagger can not guarantee, that Agents and Auth use different models. So we need to create separate file for each model. Why huge files is a problem? You don't need to modify or even open it.

I thought there would be problems with the opening of a large file. But in principle, it will probably be right for now. If there are really problems, I will reveal a question again. 

And why the storage of each model in a separate file is contrary to your generator vision ?

**Comment by Vovanella95** [comment]
@skiryuk I don't like a lot of files. It's difficult to navigate and not trivial to implement and support. Sorry :(

**Comment by Vovanella95** [comment]
@skiryuk I will close this issue because it's not a problem files are huge. I have generated files with 200K+ lines and everything works OK. There're no reasons to open generated files if there are no issues. In case if issues - please raise it here, we will pick it up and fix.
