### ISSUE TITLE
[BUG] "build_only_models: true" causes missing "import 'dart:convert';"

### ISSUE THREAD

**Issue by jl-insiders** [epam-cross-platform-lab/swagger-dart-code-generator#372]
First I wanted to say thank you for sharing this library. Currently, we are using the models only feature which was working well up to v2.3.13.

**Describe the bug**
When setting "build_only_models: true" in build.yaml, 
the generated file: pet_service_json.swagger.dart
is missing "import 'dart:convert';" for jsonEncode.

**To Reproduce**
I can reproduce this using the swagger file from the example in this repo.
Edit build.yaml and set "build_only_models" to true.
flutter pub run build_runner build --delete-conflicting-outputs
Then look in pet_service_json.swagger.dart and notice that 
import 'dart:convert'; is not in the file.

**Library version used:**
v2.4.7

**Comment by Vovanella95** [comment]
Hi @jl-insiders  will take a look into it asap
