### ISSUE TITLE
[QUESTION] How to intercept and change the response

### ISSUE THREAD

**Issue by LaurentiuSimionescu** [epam-cross-platform-lab/swagger-dart-code-generator#375]
Implemented a local mock server solution to test different scenarios in our app.
I am loading a list of mock responses from local JSON files.
In the interceptor, I can load everything and I end up with a Map<String, dynamic>.
But now I am unable to change the content of the response with the one that I constructed.
I get Response<dynamic> is not type of Response<LoginResponse> for example.

There is no access to the converter, and if ever there was access not sure how to make it work.
 This is the interceptor snippet.

```dart
final String responseBody = 
    await rootBundle.loadString(result.second, cache: false);

final http.Response httpResponse =
    http.Response(responseBody, int.parse(result.first));

final Response newResponse = response.copyWith(base: httpResponse);

return newResponse;
```

**Comment by Vovanella95** [comment]
Hi @LaurentiuSimionescu, you can try get String body and use ModelName.fromJson(). then modify it and then convert back to json. Possible, I missing your problem. Could you provide more details?

**Comment by Vovanella95** [comment]
Hi @LaurentiuSimionescu, interceptors are not ment to be used for response transformation.
If you will try to do this - you will have next error `Interceptors should not transform the body of the responseUse Response converter instead`. To modify response, please, use Converter. You can implement your own converter and pass it to ChopperClient.

For example:
``dart
final petsApi = PetServiceYaml.create(
    client: ChopperClient(converter: MyConverter()),
  );

///.....
  @override
  FutureOr<Request> convertRequest(Request request) {
    return request;
  }

  @override
  FutureOr<Response<BodyType>> convertResponse<BodyType, InnerType>(Response response) async {
    return Future.value(Response<BodyType>(http.Response('', 200), Pet() as BodyType),);
  }
}
```

**Comment by LaurentiuSimionescu** [comment]
Hi, thanks for the update.
Got another question if you might help, how can I stop the actual request to the server and send back a local response?

**Comment by Vovanella95** [comment]
@LaurentiuSimionescu  why can't you mock whole service and just mock returned data? 

```dart
class PetServiceMock extends Mock implements PetService {}

when(() => petServiceMock.getPets()).thenAnswer((_) => Future.value(SomeSpecialPet()));
```

**Comment by Vovanella95** [comment]
Looks like everything OK here. Closing the issue.
