### ISSUE TITLE
[FEATURE] Handle default values for enums

### ISSUE THREAD

**Issue by via-guy** [epam-cross-platform-lab/swagger-dart-code-generator#382]
**Is your feature request related to a problem? Please describe.**
In #381 we tried to implement default values for enums. The problem is that the code generated by `json_serializable` doesn't include the `enums.` prefix for the default value types, which breaks compilation. Alternatively, I tried to use the `fromJson` function that we generate to pass the default value, but then the `@JsonKey` annotation has a non-constant expression, so compilation breaks again.

**Describe the solution you'd like**
We need to fix `json_serializable` to include the import prefix `enums.` in the generated code. I have tried to do this myself but it looks like the `Element` loses its import information, so we may even need to fix the `analyzer` project to include it.

**Swagger specification link**
### Single default value
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Some service",
    "version": "1.0"
  },
  "components": {
    "schemas": {
      "Success": {
        "title": "Success",
        "enum": [
          "one",
          "two"
        ],
        "type": "string",
        "description": "An enumeration."
      }
    },
    "responses": {
      "SpaEnumResponse": {
        "description": "Success",
        "content": {
          "application/json": {
            "schema": {
              "properties": {
                "success": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Success"
                    }
                  ],
                  "description": "The type of client validation for this field",
                  "default": "one"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

```dart
test('Enums should have default values', () {
  final map = jsonDecode(schemasWithEnumsFromAllOf) as Map<String, dynamic>;
  final result = generator.generateResponses(map, 'fileName');

  expect(
    result,
    contains(
          '@JsonKey(name: \'success\', toJson: successToJson, fromJson: successFromJson, defaultValue: enums.Success.one)',
    ),
  );
});
```

### Default values list
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Some service",
    "version": "1.0"
  },
  "components": {
    "schemas": {
      "Success": {
        "title": "Success",
        "enum": [
          "one",
          "two"
        ],
        "type": "string",
        "description": "An enumeration."
      }
    },
    "responses": {
      "SpaEnumResponse": {
        "description": "Success",
        "content": {
          "application/json": {
            "schema": {
              "properties": {
                "successes": {
                  "items": {
                    "$ref": "#/components/schemas/Success"
                  },
                  "description": "The type of client validation for this field",
                  "type": "array",
                  "default": ["one", "two"]
                }
              }
            }
          }
        }
      }
    }
  }
}
```

```dart
test('Enum list should have default values', () {
  final map = jsonDecode(schemasWithEnumList) as Map<String, dynamic>;
  final result = generator.generateResponses(map, 'fileName');

  expect(
    result,
    contains(
          '@JsonKey(name: \'successes\', toJson: successListToJson, fromJson: successListFromJson, defaultValue: [enums.Success.one, enums.Success.two])',
    ),
  );
});
```

**Comment by Vovanella95** [comment]
@via-guy  If you want to implement it by your own - you can modify generation of _modelFromJson methods. It will be easy and safe fix. Or just let me do this. For example:

```dart
fromJson: vODResponseProductTypeFromJson


enums.VODResponseProductType vODResponseProductTypeFromJson(
    Object? vODResponseProductType) {
  if (vODResponseProductType is String) {
    return enums.$VODResponseProductTypeMap.entries
        .firstWhere(
            (element) =>
                element.value.toLowerCase() ==
                vODResponseProductType.toLowerCase(),
            orElse: () => const MapEntry(
                enums.VODResponseProductType.swaggerGeneratedUnknown, ''))
        .key;
  }

  return //** PUT DEFAULT VALUE HERE **//;
}
`

**Comment by Vovanella95** [comment]
@via-guy  I think, to achieve it, you need to modify only next method in generator

```dart
String generateEnumFromJsonToJson(
      SwaggerEnum swaggerEnum, bool enumsCaseSensitive)

```

**Comment by Vovanella95** [comment]
@via-guy  but anyway you can just wait while I will handle it

**Comment by Vovanella95** [comment]
@via-guy  we can add parameter to method, generation fromJson. This parameter will be default value. Different models will pass different default values.

**Comment by via-guy** [comment]
You mean adding the parameter to `generateEnumFromJsonToJson`? Because that won't work, as it'll mean that we need multiple generations for the enum based on the default value.

Alternatively, we can't add a parameter to the generated function, e.g. 
```dart
enums.Success successFromJson(Object? success, [enums.Success? defaultValue = enums.Success.one]) {
```
because this function gets passed to `@JsonKey`, which expects a function with just 1 argument.

**Comment by Vovanella95** [comment]
@via-guy  you can generate separate fromJson functions for each model. For example:

```dart
class TempModel {

@JsonKey(fromJson: _myModelFromJson)
final enums.ModelType type;
}

Function _myModelModelTypeFromJson(Object data) {
 return myModelFromJson(data, 'defaultValueForThisModel';
}

//This method already generated. Just add default value here
enums.ModelTypeFromJson(Object data, String defaultValue) {
}
```


I'm not sure but it will possible work :)

**Comment by Vovanella95** [comment]
It's not trivial task, we should:

1. Add default value parameter to fromJson methods
2. generate _modelEnumFromJson method for each model

**Comment by Vovanella95** [comment]
@via-guy I supposed all of them was about default values. Sorry. Please revert needed one

**Comment by via-guy** [comment]
@Vovanella95 ok, I think I got it in #391. It works in my project, but it may not be perfect.
It's a shame that we couldn't just get `json_serializable` to work instead. Would've been so much cleaner...

**Comment by Vovanella95** [comment]
@via-guy great I will try to check your code and release new version asap. I think it will happen next week
