### ISSUE TITLE
[BUG] Missing parameter annotations when parsing "$ref" fields

### ISSUE THREAD

**Issue by doodlezucc** [epam-cross-platform-lab/swagger-dart-code-generator#384]
Spotify's [open-api-schema.yml](https://developer.spotify.com/_data/documentation/web-api/reference/open-api-schema.yml) contains reference fields to parameter components. Despite getting parsed correctly and using the type definition of their referenced component, parameters are not annotated correctly in the generated `.swagger.dart` file.

**Generated:**
```dart
///Get Playlist Items
///
///@param
///@param
///@param fields
///@param
///@param
///@param
@Get(path: '/playlists/{playlist_id}/tracks')
Future<chopper.Response<Object>> _playlistsPlaylistIdTracksGet(
    {@Path('playlist_id') required String? playlistId,
    @Query('market') String? market,
    @Query('fields') String? fields,
    @Query('limit') int? limit,
    @Query('offset') int? offset,
    @Query('additional_types') String? additionalTypes});
```

**Source (heavily truncated):**
```yml
/playlists/{playlist_id}/tracks:
  get:
    operationId: get-playlists-tracks
    summary: |
      Get Playlist Items
    description: |
      Get full details of the items of a playlist owned by a Spotify user.
    parameters:
      - $ref: '#/components/parameters/PathPlaylistId'
      - $ref: '#/components/parameters/QueryMarket'
      -
        name: fields
        required: false
        in: query
        schema:
          title: Fields
          description: |
            Filters for the query: a comma-separated list of the
            fields to return. [...]
          type: string
      - $ref: '#/components/parameters/QueryLimit'
      - $ref: '#/components/parameters/QueryOffset'
      - $ref: '#/components/parameters/QueryAdditionalTypes'
    responses:
      "200":
        $ref: "#/components/responses/PagingObject"
      "401":
        $ref: "#/components/responses/Unauthorized"
      "403":
        $ref: "#/components/responses/Forbidden"
      "429":
        $ref: "#/components/responses/TooManyRequests"
    security:
      -
        oauth_2_0:
          - playlist-read-public
          - playlist-read-private

[...]

parameters:
  PathPlaylistId:
    name: playlist_id
    required: true
    in: path
    schema:
      title: Playlist ID
      description: |
        The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) of the playlist.
      example: 3cEYpjA9oz9GiPac4AsH4n
      type: string
  QueryLimit:
      name: limit
      required: false
      in: query
      schema:
        title: Limit
        description: |
          The maximum number of items to return. Default: 20. Minimum: 1. Maximum: 50.
        default: 20
        example: 10
        type: integer
        minimum: 0
        maximum: 50
```

Only the locally defined parameter `fields` appears in the doc comment. Apart from that, there's also an issue regarding parameter descriptions which are completely absent in the generated file. There are no additional options specified in my `build.yaml` besides input and output.

**Library version used:**
`swagger_dart_code_generator 2.4.9`

**Comment by Vovanella95** [comment]
Hi @doodlezucc , thanks for raising issue. We will handle it asap

**Comment by doodlezucc** [comment]
Thanks a lot! I'm having a look at it myself right now and was able to fix the issue in a separate fork: https://github.com/doodlezucc/swagger-dart-code-generator/commit/ff5d449554c7eed648030ad267244c2df59c1dd1

Essentially, references to parameter components are not being resolved as of yet. If a `SwaggerRequestParameter` only has the `ref` property set, then other fields like the name or description are not inherited.

**Comment by Vovanella95** [comment]
@doodlezucc  nearly fixed this issue. Did you also fixed it here? :)

**Comment by searchy2** [comment]
Thank you so much Uladzimir. Ref support came in the nick of time.

Thanks to this change, all my API endpoints are generated and working perfectly!

Instead of the old ObjectList class, now we get List<Object> correctly.

I wish you the best good sir!

**Comment by Vovanella95** [comment]
@searchy2  thanks!
