### ISSUE TITLE
[BUG] Multipart/form-data request is not being generated 🐛

### ISSUE THREAD

**Issue by alextarrago** [epam-cross-platform-lab/swagger-dart-code-generator#385]
Hi guys!

**Describe the bug**
We are generating our current specification and some of the services are not properly generated. All of the multipart/form-data services are being created as common @Post calls without any @PartFile attributes, leading us on not being able to use the generator for those services. Our spec is attached for your references (using OpenAPI 3.0). 

**To Reproduce**
```
 "/account/files": {
      "get": {
        "summary": "List all the user files",
        "operationId": "listFiles",
        "tags": [
          "Account"
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserFiles"
                }
              }
            },
            "description": "An array of File"
          },
          "default": {
            "$ref": "#/components/responses/Problem"
          }
        }
      },
      "post": {
        "summary": "Uploads File",
        "description": "Empty description",
        "operationId": "uploadFile",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "required": [
                  "id",
                  "file"
                ],
                "properties": {
                  "id": {
                    "type": "string"
                  },
                  "file": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "default": {
            "$ref": "#/components/responses/Problem"
          }
        }
      }
    },
```

**Expected behavior**
The multipart request to be created properly.

**Library version used:**
2.4.9

Are we missing something?

**Comment by Vovanella95** [comment]
Hi @alextarrago could you please share code yo expect to be generated here?

**Comment by Vovanella95** [comment]
@alextarrago  closing an issue due to no answer. Please reopen it with example of expected generated code if it will be actual.

**Comment by andywearearch** [comment]
@Vovanella95 we have also ran into this issue today

we have tried our generator with our json and the example json in this repo

It appears that the @multipart decorator isn't being added to multipart requests as per the chopper documentation
https://pub.dev/documentation/chopper/latest/chopper/Multipart-class.html

Let me know if you need anymore information about this issue, thanks in advance!

**Comment by Vovanella95** [comment]
Hi @andywearearch 

Can wegenerate code somehow, to fix it? If yes - please provide example of swagger request and expected generated code for it.

**Comment by andywearearch** [comment]
@Vovanella95 

I have done a bit of digging and im pretty sure this is what needs to be generated from the following swagger yaml/json

I have referenced both the chopper documentation linked above and the swagger multipart file documentation here (Open API Spec 3.0): 

https://swagger.io/docs/specification/describing-request-body/file-upload/

```
        content:
          multipart/form-data:
            schema:
              type: object
              description: Avatar File Upload
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
```

Should generate something like this:

```
@Post(path: '/avatars')
@Multipart()
 Future<chopper.Response<Avatar>> _avatarsPost(@PartFile() List<int> file);
```

I believe you will be able to test this using the example in your repo if you update your swagger file to use the OAS 3.0 and match what is described above

Unfortunately i cannot send any code repos but this should be enough information to generate something your side

I am happy to help test this out on a specific commit if needed as well

Again let me know if you need any more info, cheers

**Comment by Vovanella95** [comment]
@andywearearch thanks for researching. I'm reopening the issue and will fix it!

**Comment by Vovanella95** [comment]
Hi @andywearearch  @alextarrago 
I've made initial implementation. Could you please try swagger generator version from branch and check, is it works as expected? 

Your swagger example now generated with PartFile parameter and Multipart annotation.

**Comment by anandsubbu007** [comment]
Not Generating any parameter

version: `swagger_dart_code_generator: ^2.8.1`

```
     "/test/upload": {
            "post": {
                "operationId": "uploadFile",
                "parameters": [],
                "requestBody": {
                    "required": true,
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/StorageDto"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": ""
                    }
                },
                "tags": [
                    "Test"
                ],
                "security": [
                    {
                        "FireToken": []
                    }
                ]
            }
        }
```

```
        "StorageDto": {
                "type": "object",
                "properties": {
                    "image": {
                        "type": "file",
                        "nullable": true,
                        "properties": {
                            "image": {
                                "type": "string",
                                "format": "binary"
                            }
                        }
                    },
                    "fileId": {
                        "type": "string",
                        "nullable": true,
                        "description": "Image Path",
                        "example": "fileId/{name}.png"
                    }
                }
            }
```

Generating like this
```
  @Post(path: '/test/upload')
  Future<chopper.Response> _testUploadPost();

```

**Comment by anandsubbu007** [comment]
Hi @Vovanella95, can you please help me with this issue?

i can't able to generate code is the API is form-data request

**Comment by Vovanella95** [comment]
Hi @anandsubbu007, I'm on business trip till 22 Oct. I've reopened this issue, will handle it asap when return back.

**Comment by Vovanella95** [comment]
Hi @anandsubbu007, I've checked your issue. I'm not really competent in multipart requests, so I need Your help.

Is it will be fine to generate this method next way? If yes - I will generate it this way. If no - please share expected generated method result.

```dart
Future<chopper.Response> testUploadPost({String? cacheControl, StorageDto? body,}) {
    return _testUploadPost(cacheControl: cacheControl, body: body);
  }

  ///
  @Post(path: '/test/upload')
  @Multipart()
  Future<chopper.Response> _testUploadPost(
      {@Header('Cache-Control') String? cacheControl,
      @Body() StorageDto? body,});
```


Thanks a lot and let's do this generator better together :)

**Comment by anandsubbu007** [comment]
Hi @Vovanella95, Thank For This Generator Package.

yes, i think so.

**Comment by Vovanella95** [comment]
@anandsubbu007 cool, I will make fix in day or two. Thanks for quick answer!

**Comment by Vovanella95** [comment]
Fixed

**Comment by anandsubbu007** [comment]
when i use multipart/form data.
Enumname is not generating

**Comment by Vovanella95** [comment]
@anandsubbu007  please share part of swagger file and expected result

**Comment by anandsubbu007** [comment]
@Vovanella95  Sorry, for late response.

Still This warning is showing
```
POST test/upload
Body is null
Use @Body() annotation on your method parameter to provide a body to your request
   e.g.: Future<Response> postRequest(@Body() Map body);
Or explicitly suppress this warning by setting the optionalBody property
   e.g.: @Post(optionalBody: true)
```

If i use this body with enum property. it is not generating
```
            "StorageDto": {
                "type": "object",
                "properties": {
                    "image": {
                        "type": "file",
                        "nullable": true,
                        "properties": {
                            "image": {
                                "type": "string",
                                "format": "binary"
                            }
                        }
                    },
                    "fileId": {
                        "type": "string",
                        "nullable": true,
                        "description": "Image Path",
                        "example": "fileId/{name}.png"
                    },
                    "bucket": {
                        "description": "Storage Bucket of ",
                        "default": "Other",
                        "nullable": true,
                        "readOnly": true,
                        "$ref": "#/components/schemas/EStorageBucket"
                    }
                }
            },
```
throwing this error. enum value is not recognized in this.

```
line 90, column 81 of .: Expected to find '}'.
   ╷
90 │ Future<chopper.Response> testUploadPost({List<String>? image, String? fileId, ? bucket, }) { 
   │                                                                                 ^^^^^^
   ╵
line 93, column 132 of .: Expected an identifier.
```

may i know correct way to convet uint8list or file to List<String> to upload file.
