### ISSUE TITLE
[QUESTION] How to build this package's source code (generating ".g2.dart")

### ISSUE THREAD

**Issue by doodlezucc** [epam-cross-platform-lab/swagger-dart-code-generator#388]
I'm trying to edit some of the source code of this package. You seem to be using `json_serializable` on the swagger models to generate `.g2.dart` files. I'm struggling to understand how and why these files are called `g2` instead of simply `g`.

Dart's json generator ignores the serializable files because they're missing the exact line `part of [name].g.dart` at the top. The way this package's files are structured, it's seemingly impossible to run build_runner inside the project directory without either ignoring all files or encountering tons of warnings and errors.

It's not like I need to edit the swagger generator's serializable, but I'm curious as to how you rebuild your files. Did you manually change their names or is there an additional option in the build config I'm not seeing?

**Comment by Vovanella95** [comment]
Hi @doodlezucc  you can just remove `.g2` to `.g` and make it `.g2` again when generation is completed. Also before generation please comment `build.yaml `file, otherwise generation will not work

**Comment by doodlezucc** [comment]
Right, I have tried that... but it's a bit cumbersome, isn't it? Why not just leave it at `.g`?

**Comment by Vovanella95** [comment]
@doodlezucc  We added all .g files to gitignore to not commit generated files if it's not needed

**Comment by doodlezucc** [comment]
Ah, I see. Thanks for clarifying!
