### ISSUE TITLE
[QUESTION] Create schema property as not "final"

### ISSUE THREAD

**Issue by gabsgoncs** [epam-cross-platform-lab/swagger-dart-code-generator#389]
Problem:
Generated code for schema objects always have properties set as "final". E.g.: A post result model is created with final properties, not allowing me to modify the local result if necessary.

Expected solution:
Object properties not flagged with "readOnly : true" on the swagger file not generated as final.

If there is any way of handling this situation I would be happy to know. Have looked a lot into it and can't seem to find an answear.

**Comment by Vovanella95** [comment]
Hi @gabsgoncs , it's how it's meant to be. We generate immutable models, immutability is good approach. If you want to modify your models - just use `copyWith` method. We already generation it.

Any other questions?

**Comment by Vovanella95** [comment]
@gabsgoncs  I'm closing issue. Please raise new one in case on questions
