### ISSUE TITLE
[QUESTION] Generate JSON factory mapping with build_runner

### ISSUE THREAD

**Issue by vaetas** [epam-cross-platform-lab/swagger-dart-code-generator#395]
Hello,
I've updated this package from verzion `2.0.8+1` to `^2.4.10`. I see that one of the changes is populating the `generatedMapping` map in runtime like this 

```dart
generatedMapping.putIfAbsent(
        ResultDataType, () => ResultDataType.fromJsonFactory);
```

I'm using an isolate for JSON decoding and encoding (as my objects can be fairly large). Following code worked perfectly in the previous version I mentioned.

```dart
import 'dart:async';

import 'package:chopper/chopper.dart' as chopper;
import 'package:app/src/api/app.swagger.dart';
import 'package:isolate/isolate_runner.dart';

class IsolateConverter extends chopper.Converter {
  IsolateConverter(
    this.converter, {
    required this.isolateRunner,
  });

  final $JsonSerializableConverter converter;
  final IsolateRunner isolateRunner;

  @override
  FutureOr<chopper.Request> convertRequest(chopper.Request request) {
    return isolateRunner.run(converter.convertRequest, request);
  }

  @override
  FutureOr<chopper.Response<ResultType>> convertResponse<ResultType, Item>(
    chopper.Response response,
  ) {
    return isolateRunner.run(
      (argument) {
        return converter.convertResponse<ResultType, Item>(
          argument as chopper.Response<Object>,
        );
      },
      response,
    );
  }
}
```

Then I provided this into my `ChopperClient` like this:
```dart
converter: IsolateConverter(
  $JsonSerializableConverter(),
  isolateRunner: isolateRunner,
),
```

With the new version it still compiles. However, I'm getting following error.

```dart
Could not find factory for type RestResponseResultDataType. Is 'RestResponseResultDataType: RestResponseResultDataType.fromJsonFactory' included in the CustomJsonDecoder instance creation in bootstrapper.dart?
```

The factory is missing from the map. My guess would be that isolates copy the objects and maybe something gets lost somewhere...

It works if I copy the static generated mappings from my last version.

Maybe I'm doing something wrong. So I was wondering If you have any insight to this, or if I can enable legacy generated mapping in my `build.yaml`.

Thank you!

**Comment by Vovanella95** [comment]
Hi @vaetas 

how to create instance if isolateRunner here? 

```dart
converter: IsolateConverter(
  $JsonSerializableConverter(),
  isolateRunner: isolateRunner,
),
```

**Comment by Vovanella95** [comment]
Hi @vaetas!

Indeed we're decided to generate generatedMapping on fly. It's needed to tree-shaking works properly. For example, if we have 1000 models but use only few of them - on previous approach all models keep, but now they will be removed. This way your app will take less size.

According your situation I have a proposal. 


```dart
import 'dart:async';

import 'package:chopper/chopper.dart' as chopper;
import 'package:example/swagger_generated_code/client_mapping.dart';
import 'package:isolate/isolate_runner.dart';

import 'swagger_generated_code/pet_service_yaml.swagger.dart';

class IsolateConverter extends chopper.Converter {
  IsolateConverter(
    this.converter, {
    required this.isolateRunner,
  });

  final $JsonSerializableConverter converter;
  final IsolateRunner isolateRunner;

  @override
  FutureOr<chopper.Request> convertRequest(chopper.Request request) {
    return isolateRunner.run(converter.convertRequest, request);
  }

  @override
  FutureOr<chopper.Response<ResultType>> convertResponse<ResultType, Item>(
    chopper.Response response,
  ) {
    return isolateRunner.run(
      (argument) {
        generatedMapping
            .addAll((argument as RequestMappingContainer).generatedMapping);

        return converter.convertResponse<ResultType, Item>(
          argument.response as chopper.Response<Object>,
        );
      },
      RequestMappingContainer(
          response: response, generatedMapping: generatedMapping),
    );
  }
}

class RequestMappingContainer {
  final Map<Type, Object Function(Map<String, dynamic>)> generatedMapping;
  final chopper.Response response;

  RequestMappingContainer({
    required this.generatedMapping,
    required this.response,
  });
}
```

It works in my example. Is it helps?

**Comment by vaetas** [comment]
Hi @Vovanella95 
Your solution works perfectly! Thank you!

**Comment by ankit-triomics** [comment]
@Vovanella95 i am having some issue with generated mappings, if i make some changes in my swagger and run build runner again then some mappings get deleted and that gives me the issue of Could not find factory for type XYZ. Is 'XYZ: XYZ.fromJsonFactory' included in the CustomJsonDecoder instance creation in bootstrapper.dart?

**Comment by Vovanella95** [comment]
@ankit-triomics  please share your swagger file (or part of it). Without it I can't fix it.

**Comment by ankit-triomics** [comment]
@Vovanella95 i have mailed you the swagger file on this Vovanella95@mail.ru

**Comment by Vovanella95** [comment]
@ankit-triomics  received it. Will handle

**Comment by Vovanella95** [comment]
@ankit-triomics 
I'm on business trip next 2 weeks. Will handle all tickets asap when return home :)

**Comment by ankit-triomics** [comment]
sure @Vovanella95 , have a great time.

**Comment by Vovanella95** [comment]
Ok reopen issue if problem will be still actual
