### ISSUE TITLE
[FEATURE] Generate tests

### ISSUE THREAD

**Issue by Ltei** [epam-cross-platform-lab/swagger-dart-code-generator#405]
Would it be possible to generate tests for every method?

**Comment by fryette** [comment]
Please provide an expected result of such tests.

**Comment by Vovanella95** [comment]
@Ltei  does it make sense to generate tests for generated code? Why just not exclude it from coverage?

**Comment by Vovanella95** [comment]
@Ltei  you can use, for example, this package to remove generated files from coverage
https://pub.dev/packages/remove_from_coverage

**Comment by Ltei** [comment]
Hi!
I want to use your package to generate code for [Legifrance API](https://developer.aife.economie.gouv.fr/index.php?option=com_apiportal&view=apitester&usage=api&apitab=tests&apiName=DILA+-+L%C3%A9gifrance+Beta&apiId=404c503e-d69d-4f2d-9909-00d33bd56701&managerId=2&type=rest&apiVersion=1.6.2.5&Itemid=265&swaggerVersion=2.0&lang=fr)

However, the swagger doesn't correspond to the API (many types differs, some names changed)

The goal of such tests would be to test very basic usage of the api (with default values everywhere), just to check for this kind of issue.
Of course wont be the cleanest tests ever and that's not the goal

**Comment by Vovanella95** [comment]
We're not going to generate tests for now, because it does not make sense. Closing the issue.
