### ISSUE TITLE
Having null values in generated Json

### ISSUE THREAD

**Issue by kawmy** [epam-cross-platform-lab/swagger-dart-code-generator#409]
hi there i wanted to handle my generated json to automatically ignore null jsons like
this the generated json for now
```

}
  "teacherId": null,
  "name": "string",
  "minimum": 0,
  "maximum": 0,
  "percentage": 0,
  "description": "string",
  "scoringType": "Attendance",
  "id":null
{
```
but i want it like 

this

```
}
  "name": "string",
  "minimum": 0,
  "maximum": 0,
  "percentage": 0,
  "description": "string",
  "scoringType": "Attendance",
{
```
how to make the toJson factory automatically recognize nulls and ignore them from being generated in the request json?

**Comment by kawmy** [comment]
Yes perfect but i saw deafault value was null and not false . Now i did set it to false and its working .
But u are saying it should be true?

**Comment by Vovanella95** [comment]
@kawmy  if it's true - null values will be added to your json. If false - they will not. If it's null - the same as for true.

About default value - it was mistake. By default it's null.

**Comment by Vovanella95** [comment]
@kawmy any other questions?

**Comment by kawmy** [comment]
No thanks.
