### ISSUE TITLE
[BUG]Could not find factory for type XX

### ISSUE THREAD

**Issue by alextarrago** [epam-cross-platform-lab/swagger-dart-code-generator#410]
We are getting this error from all the object models from our API. Everything was working fine, we just regenerate de SPEC and all models have this specific error.

`Could not find factory for type Orders. Is 'Orders: Orders.fromJsonFactory' included in the CustomJsonDecoder instance creation in bootstrapper.dart?
flutter: 
#0      $CustomJsonDecoder._decodeMap (package:simplr/data/api/simplr.swagger.dart:15423:14)
#1      $CustomJsonDecoder.decode (package:simplr/data/api/simplr.swagger.dart:15414:14)
#2      $JsonSerializableConverter.convertResponse (package:simplr/data/api/simplr.swagger.dart:15445:28)
#3      ChopperClient._decodeResponse (package:chopper/src/base.dart:186:29)
#4      ChopperClient._handleSuccessResponse (package:chopper/src/base.dart:260:17)
#5      ChopperClient.send (package:chopper/src/base.dart:333:19)`

**Comment by Vovanella95** [comment]
Hi @alextarrago . Could you provide example of generated request, where you have this error?

**Comment by Vovanella95** [comment]
@alextarrago it can happens because before making call generatedMappind.putIfAbsent is not called. That's why I ask to provide part of generated code

**Comment by alextarrago** [comment]
Sure, there you go... 
`Future<chopper.Response<Orders>> ordersGet(
      {enums.OrdersEmbed? embed, Pageable? pageable, OrderCriteria? q}) {
    generatedMapping.putIfAbsent(Pageable, () => Pageable.fromJsonFactory);
    generatedMapping.putIfAbsent(
        OrderCriteria, () => OrderCriteria.fromJsonFactory);

    return _ordersGet(
        embed: enums.$OrdersEmbedMap[embed]?.toString(),
        pageable: pageable,
        q: q);
  }`

**Comment by Vovanella95** [comment]
Hy @alextarrago, thanks for code snipper! Can you also share swagger file part of this request? I see Orders object is not added to generated mapping

**Comment by alextarrago** [comment]
Of course!
```
"/orders": {
      "get": {
        "summary": "List all the Orders",
        "description": "Would provide all the orders available",
        "operationId": "listOrders",
        "tags": [
          "Orders"
        ],
        "parameters": [
          {
            "$ref": "#/components/parameters/OrdersEmbed"
          },
          {
            "$ref": "#/components/parameters/Pageable"
          },
          {
            "$ref": "#/components/parameters/OrderCriteria"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Orders"
                }
              }
            },
            "description": "An array of Orders"
          },
          "default": {
            "$ref": "#/components/responses/Problem"
          }
        }
      },
```

**Comment by Vovanella95** [comment]
@alextarrago and please schema of "Orders"

**Comment by Vovanella95** [comment]
@alextarrago I have a fix. Can I ask you to check it, using swagger generator version from branch? You need just update pubspec.yaml, re-generate code and let me know, is everything fine.

```dart
swagger_dart_code_generator:
  git:
    url: https://github.com/epam-cross-platform-lab/swagger-dart-code-generator.git
    ref: version/2.5.3
```

**Comment by AhmedHamdan54** [comment]
@Vovanella95  I am working on the same project and I can confirm that the fix didn´t work.
It´s still showing the same error,

```
I/flutter ( 9099): Could not find factory for type Orders. Is 'Orders: Orders.fromJsonFactory' included in the CustomJsonDecoder instance creation in bootstrapper.dart?
I/flutter ( 9099): #0      $CustomJsonDecoder._decodeMap (package:simplr/data/api/simplr.swagger.dart:16497:14)
I/flutter ( 9099): #1      $CustomJsonDecoder.decode (package:simplr/data/api/simplr.swagger.dart:16488:14)
I/flutter ( 9099): #2      $JsonSerializableConverter.convertResponse (package:simplr/data/api/simplr.swagger.dart:16519:28)
I/flutter ( 9099): #3      ChopperClient._decodeResponse (package:chopper/src/base.dart:186:29)
I/flutter ( 9099): #4      ChopperClient._handleSuccessResponse (package:chopper/src/base.dart:260:17)
I/flutter ( 9099): #5      ChopperClient.send (package:chopper/src/base.dart:333:19)
```

**Comment by Vovanella95** [comment]
@AhmedHamdan54  or @alextarrago  please provide full swagger file or just request which fails and all schemas, defined in this request. I will fix it asap

**Comment by alextarrago** [comment]
can you send private email address please?

**Comment by Vovanella95** [comment]
@alextarrago  sure!

**Comment by Vovanella95** [comment]
@AhmedHamdan54  great I see the problem! Will fix it tomorrow!

**Comment by Vovanella95** [comment]
@AhmedHamdan54  @alextarrago  please check latestversion

**Comment by alextarrago** [comment]
Hi @Vovanella95 thanks for being that fast! We are now facing another problem we did not have on the previous version. Some of the data models are being generated as a Map<String, dynamic>...

```
typedef StringFilter = Map<String, dynamic>;
typedef LongFilter = Map<String, dynamic>;
typedef IntegerFilter = Map<String, dynamic>;
typedef BigDecimalFilter = Map<String, dynamic>;
typedef BooleanFilter = Map<String, dynamic>;
typedef InstantFilter = Map<String, dynamic>;
```

On the spec you will see its definition:
```
...
"StringFilter": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Filter"
          },
          {
            "type": "object",
            "properties": {
              "contains": {
                "type": "string"
              },
              "doesNotContain": {
                "type": "string"
              },
              "equals": {
                "type": "string"
              },
              "notEquals": {
                "type": "string"
              },
              "in": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "notIn": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        ]
      },
...
```

Any ideas?

**Comment by Vovanella95** [comment]
@alextarrago  agh you're right! Let me handle it

**Comment by Vovanella95** [comment]
@alextarrago  can you try 2.5.4+1?

**Comment by alextarrago** [comment]
Amazing! Now it's perfect! Thanks @Vovanella95 👍

**Comment by Vovanella95** [comment]
Thanks YOU to stay in touch and using our generator!

**Comment by ankit-triomics** [comment]
@Vovanella95 i am facing this issue 
```Could not find factory for type OrganisationMembersGet$36Response. Is 'OrganisationMembersGet$36Response: OrganisationMembersGet$36Response.fromJsonFactory' included in the CustomJsonDecoder instance creation in bootstrapper.dart?```

**Comment by Vovanella95** [comment]
@ankit-triomics  are you still have this issue?

**Comment by iresharma** [comment]
I am working with @ankit-triomics the problem seems to be that the generator is not putting/adding the the factory to the generateMappings map.

If we understand it correctly the generator code relies on the generateMapping map during runtime to map the correct factory to the correct type. What is is happening is for some functions/endpoints it's skipping the `putIfAbsent` statement.

**Comment by ankit-triomics** [comment]
we are using the version 2.4.6 @Vovanella95

**Comment by Vovanella95** [comment]
@ankit-triomics  try to use latest one and let me know
