### ISSUE TITLE
Suddenly `int` parameters are interpreted as `string` parameters (from at least 2.5.6+1)

### ISSUE THREAD

**Issue by RoarGronmo** [epam-cross-platform-lab/swagger-dart-code-generator#415]
**Describe the bug**
When upgrading from (at lowest `2.3.10` to `2.5.6+1`) some `int` paramaters are interpreted as `string` paramters.

**To Reproduce**
[mwork_api.swagger.txt](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/8790683/mwork_api.swagger.txt)

**Expected behavior**
Expecting the generator to generate the files as before, since there where no significant version rise.
This wasn't so in `2.3.10`

**Problem**
Pinpoint the two required paramters which should be in `int32`
![image](https://user-images.githubusercontent.com/11217296/170815384-2eb8cc01-517a-4df8-b60b-09593027c770.png)

Here theese two variables are interpreted as strings...
![image](https://user-images.githubusercontent.com/11217296/170815486-9de9944b-3261-4223-bbe2-2beab91cb9bb.png)

**Library version used:**
My yaml files: 
[pubspec.yaml.txt](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/8790686/pubspec.yaml.txt)
[build.yaml.txt](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/8790688/build.yaml.txt)

Library version used `2.5.6+1`

**Additional context**

**Comment by RoarGronmo** [comment]
The problem seems to be introduced in `2.5.5`, in `2.5.4` it works OK.

**Comment by Vovanella95** [comment]
Hi @RoarGronmo , I will check it. Thanks for raising!

**Comment by RoarGronmo** [comment]
TYI: The issue is still there in `2.5.7`

**Comment by Vovanella95** [comment]
@RoarGronmo  hello! Yes I know :) Will handle your issue this or next week! Your issue is first one in my priority

**Comment by Vovanella95** [comment]
Hi @RoarGronmo please check `swagger_dart_code_generator: ^2.5.8`. Should work fine

**Comment by RoarGronmo** [comment]
Confirming that `2.5.8` works as expected !!
