### ISSUE TITLE
best way to send files

### ISSUE THREAD

**Issue by kawmy** [epam-cross-platform-lab/swagger-dart-code-generator#423]
hi there ive a dto like this in server :
```

        [Required]
        public string Banner { get; set; }
        [Required]
        public string MainProfile { get; set; }
        [Required]
        public string Video { get; set; }
        [Required]
        public string Parvane { get; set; }

      
        public ShopStatus Status { get; set; }
```
  i wanted to know what is the best way to send files in a dto to server using your package?

**Comment by Vovanella95** [comment]
Hi @kawmy , our lib is needed for generation code from Swagger files. To send files using our lib - you need to configure swagger file appropriately. 

For more info you can read [swagger spec](https://swagger.io/docs/specification/describing-request-body/file-upload/)

Any other questions?

**Comment by Vovanella95** [comment]
@kawmy  you can check example in this issue.

https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/385
