### ISSUE TITLE
[FEATURE] Generate Integers as Int and not as Num

### ISSUE THREAD

**Issue by malaschitz** [epam-cross-platform-lab/swagger-dart-code-generator#424]
**Is your feature request related to a problem? Please describe.**
All integers are generated as num. I have to call the cast every time I use it. 

**Describe the solution you'd like**
Generate integers, int64 as int.

**Swagger specification link**
https://swagger.io/docs/specification/data-models/data-types/#numbers

**Comment by malaschitz** [comment]
Yes. Thanks !

**Comment by gogolon** [comment]
Hello, as you can read in dart docs (https://api.dart.dev/stable/2.19.4/dart-core/int-class.html) the default implementation of int in dart is 64 bit, so there is no reason to generate int64 as num. Could you please make it possible to generate ints64 as integers?
