### ISSUE TITLE
[BUG] Generating invalid dart. Missing some nested objects

### ISSUE THREAD

**Issue by vtjiles** [epam-cross-platform-lab/swagger-dart-code-generator#425]
**Describe the bug**
I am having some issues creating a package for the [SureMDM API](http://suremdmapidoc.42gears.com/) and was hoping you could help. It appears some nested objects are not being created and I'm not sure whether I can fix it in the build.yaml or not.

Example errors (with links to the test repo):
- [hashCode is already defined](https://github.com/vtjiles/sure_mdm/blob/master/lib/src/generated/sure_mdm.models.swagger.dart#L8713)
- Undefined classes for objects like [GroupByIDModel$Groups](https://github.com/vtjiles/sure_mdm/blob/master/lib/src/generated/sure_mdm.models.swagger.dart#L7739), [GroupGetModel$Groups](https://github.com/vtjiles/sure_mdm/blob/master/lib/src/generated/sure_mdm.models.swagger.dart#L7814), [CompliancePolicyPayLoad$Item$OSVersionRule](https://github.com/vtjiles/sure_mdm/blob/master/lib/src/generated/sure_mdm.models.swagger.dart#L9538), .... 
- Undefined name [String$Item](https://github.com/vtjiles/sure_mdm/blob/master/lib/src/generated/sure_mdm.swagger.dart#L766), [int$Item](https://github.com/vtjiles/sure_mdm/blob/master/lib/src/generated/sure_mdm.swagger.dart#L539), ...
- Missing enums like [enums.$ActionCompliance$ItemTypeMap](https://github.com/vtjiles/sure_mdm/blob/master/lib/src/generated/sure_mdm.models.swagger.dart#L20628)
- Getters (year,month, day) not defined [_dateToJson](https://github.com/vtjiles/sure_mdm/blob/master/lib/src/generated/sure_mdm.models.swagger.dart#L20931)

Also, the SureMDM schema defines the api base url in a "servers" property instead of "host". Is it possible to use a url from that array or to provide the base url as a string in build.yaml?

**To Reproduce**
[Swagger File](http://suremdmapidoc.42gears.com/specs/openapi_v1.json)
[SureMDM Dart Repo](https://github.com/vtjiles/sure_mdm)
[Build YAML](https://github.com/vtjiles/sure_mdm/blob/master/build.yaml)

**Expected behavior**
Valid dart is generated and all object classes are available.

**Library version used:**
Please specify library version
2.6.0
Also failed to generate with a few 2.4.x and 2.5.x versions

**Additional context**
I was able to use this package for another side project with a much simpler schema and it saved me so much time! Thank you for sharing this package with the community and for your continued efforts supporting it!

**Comment by Vovanella95** [comment]
Hi @vtjiles , thanks for raising bug. I will fix it next week.

**Comment by vtjiles** [comment]
Thanks, but it also seems I need a feature that's not currently supported so I understand if you prefer to close this. 

I attempted to simplify the JSON and only load a few methods, but the request body was not added to the method signature. It seems that happened when using [`oneOf`](https://github.com/vtjiles/sure_mdm/blob/9da77f71947c8a4f2fe0b53f731da79f3aa0e942/swagger/sure_mdm.json#L3328-L3433) and based on [another issue](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/369) it seems there is no plan to support polymorphism.

**Comment by Vovanella95** [comment]
Hi @vtjiles  I've partially fixed your swagger file. I need some more time to finish fixing.

**Comment by vtjiles** [comment]
In working more with the API I have learned the swagger doc does not contain the full list of values for enums, incorrect types for responses, and casing for field names that does not match what is returned by their API. Even if the generator produces valid code I do not think it will be possible to handle all these issues caused by a bad swagger file.

I appreciate that you've taken the time to look into this and will try the generator again on my next project with a valid swagger doc. It would be great if this package could eventually support `oneOf` with base classes, but I realize that's a pretty tough feature to add.

**Comment by Vovanella95** [comment]
@vtjiles ok fine)) I will revert changes I made. Thanks for investigation! Please let us know in case of any issues!
