### ISSUE TITLE
[QUESTION] Build Fail - FileSystem Exception (errno 5). No OS permission.

### ISSUE THREAD

**Issue by DylanCross** [epam-cross-platform-lab/swagger-dart-code-generator#426]
Build fails on "flutter pub run build_runner build" command. Appears the code is not getting permission to create files. 

I'm using windows 10. I'm the admin / only user. I've disabled all anti-virus and firewall, I've run from powershell in VS, and powershell as Admin seperate, and tried command line. Flutter is installed in My Docs, and is the swagger-generator. 

I've tried running with the "swagger-dart-code-generator/lib" as my input folder, and straight My Documents and it still sayd no permission to create file. 

I've updated flutter to 3.0.2, run flutter clean, and  pub cache repair. 

I also restarted my machine. 

Here's the straight terminal output. 

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

FileSystemException: Cannot create file, path = 'lib/src' (OS Error: Access is denied.
, errno = 5)
dart:io                                                                      _File.createSync
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 62:30   _generateExtensions
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 118:32  SwaggerDartCodeGenerator.buildExtensions
package:build_runner_core/src/package_graph/apply_builders.dart 403:33       _validateBuilder
package:build_runner_core/src/package_graph/apply_builders.dart 183:9        new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner_core/src/package_graph/apply_builders.dart 346:27       _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                                    Iterable.toList
package:build_runner_core/src/package_graph/apply_builders.dart 293:8        createBuildPhases
package:build_runner_core/src/generate/build_impl.dart 109:29                BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 34:42               BuildRunner.create
package:build_runner/src/generate/build.dart 109:35                          build
package:build_runner/src/entrypoint/build.dart 35:18                         BuildCommand._run
package:args/command_runner.dart 209:13                                      CommandRunner.runCommand
package:build_runner/src/entrypoint/run.dart 26:18                           run
.dart_tool\build\entrypoint\build.dart 28:16                                 main

pub finished with exit code 1

**Comment by Vovanella95** [comment]
Hi @DylanCross, it's strange. Looks like your system does not permit to create files using `File(additionalResultPath).createSync();`. 

Let's find out what is the problem.
1. What OS are you using?
2. What command are you using to generate code?
3. Try to generate code using another generator in this project. Let's check is it works
4. Try to move your project to another folder maybe
5. Try to run generation in admin terminal

**Comment by DylanCross** [comment]
> 



> Hi @DylanCross, it's strange. Looks like your system does not permit to create files using `File(additionalResultPath).createSync();`.
> 
> Let's find out what is the problem.
> 
> 1. What OS are you using? **Windows 10**
> 2. Are you using `input_urls` feature? **Nope**
> 3. What command are you using to generate code? **Tried both flutter pub run build_runner build and  dart pub run build_runner build. Same result.**
> 4. Try to generate code using another generator in this project. Let's check is it works. **Can I get an easy suggestion to try. It's my first time working with this project**
> 5. Try to move your project to another folder maybe **Tried. Placed code in Docs/Tools folder and placed code directly on desktop same result**
> 6. Try to run generation in admin terminal **Same result**




Exact steps to install and run: 

1. Download swagger-dart-code-generator-master.zip (v2.6) to Documents
2. Extract in Documents folder
3. Copy swagger.json to Documents\swagger-dart-code-generator-master\lib
4. Open swagger-dart-code-generator-master folder in VS code
5. Update build.yaml file 

targets:
  swagger_dart_code_generator:swagger_dart_code_generator:
    sources:
      - lib/**
      - $package$
    builders:
      swagger_dart_code_generator:
        enabled: True
        options:
          input_folder: 'lib/'
          output_folder: 'lib/generated_code/'
	
6. Run Get Packages from pubspec.yaml
7. Run flutter pub get via PowerShell
8. Run flutter pub run build_runner build via PowerShell

Error as described. FileSystemException: Cannot create file, path = 'lib/src' (OS Error: Access is denied.
, errno = 5)

9. Run dart pub run build_runner build via PowerShell. Same error.

**Comment by Vovanella95** [comment]
Hi @DylanCross , I'm happy everything work :) Let us know in case of any issues

**Comment by Invectys** [comment]
This error also occurs when the build file extension is YML It must be YAML
In my case I was wrong when i created build.yml 
Changed to build.yaml and it works

**Comment by Vovanella95** [comment]
@Invectys  I've also faced with such issue. Will fix it.

**Comment by ronald-de-rooij** [comment]
I faced the same issue and solved it by adding the file build.yaml with the following config:

`targets:
  $default:
    sources: 
      - api_spec/**
    builders:
      swagger_dart_code_generator:
        options:
          output_folder: 'lib/generated/api'
          input_folder: 'api_spec/'`

Can you make it more clear in the readme that the build.yaml is required to prevent the error: Build Fail - FileSystem Exception (errno 5). No OS permission.

**Comment by jhancock4d** [comment]
I'm getting similar on Windows 11.

```
FileSystemException: Cannot create file, path = './.dart_tool' (OS Error: Access is denied.
, errno = 5)
dart:io                                                                      _File.createSync
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 76:30   _generateExtensions
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 132:32  SwaggerDartCodeGenerator.buildExtensions
package:build_runner_core/src/package_graph/apply_builders.dart 403:33       _validateBuilder
package:build_runner_core/src/package_graph/apply_builders.dart 183:9        new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner_core/src/package_graph/apply_builders.dart 346:27       _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                                    Iterable.toList
package:build_runner_core/src/package_graph/apply_builders.dart 293:8        createBuildPhases
package:build_runner_core/src/generate/build_impl.dart 109:29                BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 34:42               BuildRunner.create
package:build_runner/src/generate/build.dart 109:35                          build
package:build_runner/src/entrypoint/build.dart 35:18                         BuildCommand._run
package:args/command_runner.dart 209:13                                      CommandRunner.runCommand
package:build_runner/src/entrypoint/run.dart 26:18                           run
.dart_tool\build\entrypoint\build.dart 49:16                                 main
```


The folder has full access and I can edit anything in it.

Here's my build.yaml

```
targets:
  $default:
    sources:
      - api_spec/**
    builders:
      swagger_dart_code_generator:
        options:
          output_folder: lib/generated
          input_urls:
            - https://api.dev.pltfrmd.com/contacts/help/v1/openapi.json

```

**Comment by bmcclure** [comment]
I have this same error in Windows 11, regardless of trying all the previous suggestions. I have several other builders that work fine in other plugins, so this seems specific to swagger-dart-code-generator.

**Comment by bmcclure** [comment]
I mostly solved my issue...

Even though I only want to use "input_urls", the "input_folder" actually has to exist even if it is empty, otherwise I get the error mentioned previously about not being able to create .dart-tool.

As soon as I specify a folder that actually exists, swagger-dart-code-generator gets further. It still errors out for me due to a different issue, but I don't think that has anything to do with this issue.
