### ISSUE TITLE
[BUG] Genereted Future<chopper.Response<Object>> in case use JSON structure "responses/.../schema/properties"

### ISSUE THREAD

**Issue by vadimlukutin** [epam-cross-platform-lab/swagger-dart-code-generator#429]
**Describe the bug**
- In case use json structure "responses/200/content/application/json/schema/properties/...". Generated `Future<chopper.Response<Object>>`
- In case use json structure "responses/200/content/application/json/schema/$ref: "#/components/schemas/ProductModel"". Generated `Future<chopper.Response<ProductModel>>`

**To Reproduce**
On swagger JSON create response schema with property.

**Expected behavior**

**Library version used:**
- flutter_sdk: 3.0.0
- swagger_dart_code_generator: ^2.3.13
- chopper: ^4.0.5
- json_annotation: ^4.5.0

**Comment by Vovanella95** [comment]
Hi @vadimlukutin , I will take a look into it this week

**Comment by Vovanella95** [comment]
Hi @vadimlukutin , Please share part of swagger file with such responses to be more clear. Thanks! Waiting for response!

**Comment by Vovanella95** [comment]
@vadimlukutin  please reopen issue if needed and share swagger file. I can't fix it without any information.
