### ISSUE TITLE
[BUG]  Error: Invalid argument (body)

### ISSUE THREAD

**Issue by vadimlukutin** [epam-cross-platform-lab/swagger-dart-code-generator#431]
**Describe the bug**
Error: Invalid argument (body): "`{\"date_send\":null,\"stock_from_id\":2,\"stock_to_id\":8,\"user_from_id\":null,\"user_to_id\":null,\"comment\":null,\"consignments\":[{\"count\":1,\"product_model_id\":56}]}`"

**To Reproduce**
```
{
    "name": "body",
    "in": "body",
    "description": "Specify 'product_model_id' and 'count' of consignments",
    "required": true,
    "schema": {
        "type": "object",
        "$ref": "#/definitions/ConsignmentBodyPost"
    }
}
```

**Swagger specification link**
[Describing Request Body](https://swagger.io/docs/specification/2-0/describing-request-body/)

**Library version used:**
  swagger_dart_code_generator: ^2.6.0

**Comment by Vovanella95** [comment]
Hi @vadimlukutin , I've tried to reprocude your case and have next generated code:

```dart
///Add a new pet to the store
  ///@param body Specify 'product_model_id' and 'count' of consignments
  @Post(path: '/pet')
  Future<chopper.Response> _petPost(
      {@Body() required ConsignmentBodyPost? body,
      @Header('Cache-Control') String? cacheControl});
```

request looks fine. So, possible, problem is in `ConsignmentBodyPost`. Please provide definition of this or describe expected generated code. Thanks.

**Comment by Vovanella95** [comment]
@vadimlukutin  closing the issue due to no response. Now I have not enough information to fix it. Fill free to reopen issue.
