### ISSUE TITLE
[QUESTION] How to send a patch request without null parameters

### ISSUE THREAD

**Issue by flowhorn** [epam-cross-platform-lab/swagger-dart-code-generator#433]
Hello,
I've got a patch request, which i want to run, and there are a few optional parameters. 
When I try to run the request, it will fill out all the other parameters with a null value.
Is it possible to send this patch request just with the parameters where a value actually is? Because the backend doesn't allow me to send null values.

Thank you very much!

**Comment by Vovanella95** [comment]
Hi @flowhorn , are you want ignore Query, Header or path parameters?
* It's not possible to ignore path parameters, because you can't have 'null' in path.
* Query parameters with null value should be ignored automatically
* Header null properties are also excluded automatically

So what kind of parameter you want to ignore? Can you share more details?

**Comment by flowhorn** [comment]
Hello @Vovanella95 ,
Here is an example of what I mean:

This is the patch-request in loopback:
<img width="800" alt="Bildschirmfoto 2022-07-12 um 10 23 54" src="https://user-images.githubusercontent.com/37595126/178445669-e9e45dcb-eff2-4458-bcfa-94866dd04b11.png">

Here is the function that i try to call:
<img width="375" alt="Bildschirmfoto 2022-07-12 um 10 29 36" src="https://user-images.githubusercontent.com/37595126/178446268-7026bb99-810c-443f-bbaf-a065c73fe279.png">


But if you look into the network-request you will see, that all fields will be send from the object:
<img width="324" alt="Bildschirmfoto 2022-07-12 um 10 24 45" src="https://user-images.githubusercontent.com/37595126/178445781-a0931439-0dcd-4fa2-bbbc-6609740d9f7e.png">

I would like to send the network request without all the fields which are null.

**Comment by Vovanella95** [comment]
Hi @flowhorn , indeed include_if_null is true by default right now. It's issue of JsonSerializable. You can do easy fix.
Just add next code to your build.yaml and re-generate your code.

```yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          include_if_null: false
```


It will exclude all nullabe fields from you models.

**Comment by Vovanella95** [comment]
I hope my answer will help. Closing the issue.
