### ISSUE TITLE
[BUG] Discord invite on README.md has expired

### ISSUE THREAD

**Issue by caniko** [epam-cross-platform-lab/swagger-dart-code-generator#435]

**Comment by caniko** [comment]
@fryette or @Vovanella95 ?

**Comment by Vovanella95** [comment]
Hi @caniko , indeed :) I will add new contacts asap

**Comment by Vovanella95** [comment]
@caniko I have removed discord link. If you want to contact us - just create issue. we will share Telegram or any other contacts if it will be needed
