### ISSUE TITLE
[BUG]Could not find factory for type XX

### ISSUE THREAD

**Issue by linbintie** [epam-cross-platform-lab/swagger-dart-code-generator#436]
upgrade version: 2.4.10 -> 2.6.0
We are getting this error:

Error: Could not find factory for type AdCampaignGet$36Response. Is 'AdCampaignGet$36Response: AdCampaignGet$36Response.fromJsonFactory' included in the CustomJsonDecoder instance creation in bootstrapper.dart?

check regenerate code is different:
![image](https://user-images.githubusercontent.com/38446289/179657903-2a929027-2d0e-4e26-ba18-021d681fdbe0.png)
generated new code lack generatedMapping.putIfAbsent.

swagger file define like:
/ad_campaign:
    get:
      parameters:
        - name: page
          in: query
          type: integer
          format: int32
          default: 0
        - name: size
          in: query
          type: integer
          format: int32
          default: 20
          maximum: 5000
      responses:
        '200':
          description: ok
          schema:
            type: object
            required:
              - data
            properties:
              isFull:
                type: boolean
              data:
                type: array
                items:
                  $ref: '#/definitions/adCampaign'
              pagination:
                $ref: '#/definitions/pagination'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'

**Comment by Vovanella95** [comment]
Hey @linbintie , indeed generation changed in latest versions. It's needed for tree-shaking improvements. It's really strange you have `AdCampaignGet$36Response` and `AdCampaignGet$Response`. What is 36? because we generate only `AdCampaignGet$Response` model for response.

Waiting for answer

**Comment by linbintie** [comment]
I don't know where the 36 came from
my swagger file not have 36

**Comment by linbintie** [comment]
I also think it should be AdCampaignGet$Response model for response.
but run error like this: Could not find factory for type AdCampaignGet$36Response. 
This is exactly where I think there is a problem.

**Comment by Vovanella95** [comment]
@linbintie  it's really strange. 36 can not be taken from nowhere. Could You use global search and find all entrances of AdCampaignGet$36Response?

**Comment by linbintie** [comment]
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/38446289/182757660-fd29c651-0556-47ff-8e4c-3d530058d0d4.png">
Noting found

**Comment by Vovanella95** [comment]
@linbintie  woah :D Looks really strange. Possible you can do `flutter clean` and then `flutter pub get`. I don't have source code of your project and I can't investigate your issue unfortunately. 

You can try to have an experiment. Just generate your file in separate project and make a call. I'm sure everything will be fine.

**Comment by Vovanella95** [comment]
Hi @linbintie any investigation results?

**Comment by linbintie** [comment]
@Vovanella95 thank you for your reply

flutter clean and flutter pub get
I tried it when upgrade to 2.6.0, its useless.
I well try just generate your file in separate project and make a call when I am free

**Comment by Vovanella95** [comment]
@linbintie great!

**Comment by linbintie** [comment]
@Vovanella95 
I try just generate your file in separate project and make a call, but still the same error.
1: 
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/38446289/183543850-ac68a7eb-04c2-4426-a924-6d963d1c59f4.png">

2: 
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/38446289/183544012-1ae91d86-7844-407f-af43-6994db5478e5.png">

like api 1 responses schema use definitions class is run ok. 
api 2  responses schema not definitions class is run error.
I think the problem should be here.

I test change api 2 responses schema definition use definitions class is ok now.
But I think there is a bug in this place

**Comment by Vovanella95** [comment]
@linbintie Could you please share swagger file or part of it? I will make investigation and fin difference

**Comment by linbintie** [comment]
@Vovanella95 
this is my swagger file:
[swagger.yaml.zip](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/9296114/swagger.yaml.zip)

**Comment by Vovanella95** [comment]
@linbintie  Great I see the problem! Will release new version asap!

**Comment by Vovanella95** [comment]
@linbintie  please try `swagger_dart_code_generator: ^2.7.1`

**Comment by linbintie** [comment]
@Vovanella95 
ok, I will upgrade
thanks.
