### ISSUE TITLE
[FEATURE] copyWith extension methods that allow setting a field to null

### ISSUE THREAD

**Issue by vipw** [epam-cross-platform-lab/swagger-dart-code-generator#438]
**Is your feature request related to a problem? Please describe.**
I have an API that allows unsetting a value by POSTing a JSON document with a field set to NULL.

For example a person's age can be unset with by POSTing a Person object to /person/personId
```
{
  "name": "bob",
  "age": null
} 
```

The autogenerated Person class has 
```
extension $PersonExtension on Person {
  Person copyWith(
      {String? name,
      int? age) {
  return Person(
        name: name?? this.name,
        age: age?? this.age);
  }
}
```

This is usually very helpful but doesn't allow setting either field to null.

This is a simplified example, I actually have dozens of entities, each with many members. Otherwise I would just do the obvious thing:
```
newPerson = Person(name: oldPerson.name, age: null);
```

**Describe the solution you'd like**
I'm not sure it's the best solution, but I built my own extension method based on this post: https://stackoverflow.com/a/71732563/759140

```
class Wrapped<T> {
  final T value;
  const Wrapped.value(this.value);
}

extension PersonExtensionWrapped on Person {
  Person copyWrapped(
      {Wrapped<String?>? name,
      Wrapped<int?>? age) {
  return Person(
        name: (name != null ? name.value : this.name),
        age: (age != null ? age.value : this.age)
      );
  }
}

```

It seems bloated to make copyWith and copyWrapped methods. Maybe it could be a configuration flag whether the copyWith uses wrapping or not.

I also had a thought to add a copyButNullSomeFields method that would take bools, and null the specified fields:
```
extension PersonExtensionNull on Person {
  Person copyButNullSomeFields(bool? name, bool? age) {
  return Person(
   name: (name == null || name == false) ? this.name : null;
   age: (age == null || age == false) ? this.name : null;
  }
}
```
But I haven't tried this one out yet. It might be a better for autogenerated code because it would be easy to chain it with copyWith().

**Swagger specification link**
N/A

**Comment by Vovanella95** [comment]
@vipw try new version :) `swagger_dart_code_generator: ^2.7.2`

**Comment by nguyenloki258** [comment]
> @vipw try new version :) `swagger_dart_code_generator: ^2.7.2`
I got error
`
A member named 'copyWith' is defined in extension '$AccountResponseModelExtension' and extension '$AccountResponseModelWrappedExtension', and none are more specific • lib/modules/user_profile/user_profile_controller.dart:214:26 • ambiguous_extension_member_access`

**Comment by Vovanella95** [comment]
@nguyenloki258  could you please share your swagger file? Because my 50 swaggers has been generated well

**Comment by vipw** [comment]
There's one other thing that comes to my mind about this feature. Do you think it's good to allow setting required fields to null?

Maybe there should only be one copyWith method that takes raw types for required members and Wrapped<type> for the optional members. That would correspond more closely to the swagger file definition, but it would break backward compatibility and make code using the generated class more verbose. I'm curious what you think about it.

**Comment by Vovanella95** [comment]
Good evening @vipw!  I think it will make models more flexible. Because who knows how swagger file is configures.

That's correct your PR fix this issue?

**Comment by ko16a46** [comment]
Hello! I'm receiving the same issue as @nguyenloki258 

The issue is that I have multiple swagger files, which each create two different versions of `Wrapped`. 

Later, I have a barrel file that exports the generated models, and there's a conflict because both model files have their own `Wrapped`. As a stopgap fix, I downgraded my version of the package. Technically, you can also work around it by doing `export 'my_api_models.swagger.dart' hide Wrapped` on one of the conflicting models, but it's not ideal since `copyWith` won't work for those models.

Perhaps a better solution would be to copy how [freezed](https://pub.dev/packages/freezed) does `copyWith`. Freezed's way is less verbose since there's no wrapper object needed.

It keeps a private placeholder object, and `copyWith` checks if the given value is equal to the placeholder object. If it's the same placeholder, use the existing; if it's different (even `null`), use the given value. It does some override and casting shenanigans to deal with type safety.

**Comment by Vovanella95** [comment]
Hi @ko16a46 , good idea. Previously, we copy-pasted `freezed` approach. Bun looks like a lot changed since :D I will investigate it and make changes. Thanks!

**Comment by dJani97** [comment]
Getting the same error: 

```
A member named 'copyWith' is defined in extension '$LoginResponseExtension' 
and extension '$LoginResponseWrappedExtension', and none are more specific.
```

For anyone looking for a workaround, this solves it for me. Wrap your API response in one of the extension classes like so, and then use copyWith:

```
$LoginResponseExtension(response.body!).copyWith( .... )
```

**Comment by Vovanella95** [comment]
@dJani97  that would be really helpfull if you share you swagger file

**Comment by dJani97** [comment]
@Vovanella95 it's not an open-source project, can I share it with you without making it public?

**Comment by dJani97** [comment]
I'm sending it by email

**Comment by Vovanella95** [comment]
Hi @dJani97 , @vipw , Fixed your issue. Now copyWith works fine.

```dart
void main() {
  final user = LoginRequest(
    emailAddress: 'vovanella95@mail.ru',
    password: 'password',
  );

  final updatedUser = user.copyWithWrapped(password: null);
}
```

Will release new version later today
