### ISSUE TITLE
[BUG] Enums generate invalid code if - (hyphen minus ) or + (plus sign) are possible values

### ISSUE THREAD

**Issue by vipw** [epam-cross-platform-lab/swagger-dart-code-generator#444]
**Describe the bug**
A json schema enumerated string type that has "-" as a possible value generates invalid code.

Generated code looks like this:
```
enum OrderStatus {
	@JsonValue('swaggerGeneratedUnknown')
  swaggerGeneratedUnknown,
	@JsonValue('placed')
	placed,
	@JsonValue('approved')
	approved,
	@JsonValue('+')
	,
	@JsonValue('-')
	$
}


	const $OrderStatusMap = {
		OrderStatus.placed: 'placed',
	OrderStatus.approved: 'approved',
	OrderStatus.: '+',
	OrderStatus.$: '-'
      };
```

**To Reproduce**
This can be easily reproduced by changing the petstore example: definitions->order->status:
```
        "status": {
          "type": "string",
          "description": "Order Status",
          "enum": [
            "placed",
            "approved",
            "delivered",
            "-",
            "+"
          ]
        },

```

**Expected behavior**
I think the variable names in the generated enum would be hard to be meaningful, but perhaps the unicode codepoints could be used: U002D for minus-hyphen and U002B for plus sign. 

**Swagger specification link**
https://gist.github.com/vipw/afcbd1afb71217b39875a9b88f5096cf

**Library version used:**
master

**Additional context**
I assume there are many other symbols that can't be naively mapped to dart variable names, despite being valid json strings.

**Comment by Vovanella95** [comment]
Hi @vipw , thanks for raising issue. Will take a look into it this week.

**Comment by Vovanella95** [comment]
@liemvu you can share it using private channel. vovanella95@mail.ru

**Comment by Vovanella95** [comment]
@vipw  check `swagger_dart_code_generator: ^2.7.3`
