### ISSUE TITLE
[BUG] multi-part request - again wrong generated

### ISSUE THREAD

**Issue by malaschitz** [epam-cross-platform-lab/swagger-dart-code-generator#448]
Bug #358 is there again.

In version 2.7.3.

There is warning during generation:

[WARNING] Chopper Generator:
POST /profile/avatarupload
Body is null
Use @Body() annotation on your method parameter to provide a body to your request
   e.g.: Future<Response> postRequest(@Body() Map body);
Or explicitly suppress this warning by setting the optionalBody property
   e.g.: @Post(optionalBody: true)

**Comment by Vovanella95** [comment]
Hi @malaschitz  please attach swagger example and expected result

**Comment by Vovanella95** [comment]
@malaschitz  closing issue due to no answer. Feel free to reopen it
