### ISSUE TITLE
[BUG] Fields with $ result in error

### ISSUE THREAD

**Issue by queen3** [epam-cross-platform-lab/swagger-dart-code-generator#449]
If the field contain $ in the name, the JsonKey name is treated as a symbol and this results in an error.

So the generated code is

  @JsonKey(name: '$Solution')
  final String? $Solution;

and the compilation error is

Arguments of a constant creation must be constant expressions.
Undefined name 'Solution'.

I suppose $ has to be escaped somehow in the generated code.

**Comment by Vovanella95** [comment]
hi @queen3 !

Please share part of swagger file, generated this. Thanks!

**Comment by queen3** [comment]
Hello.

Yes, sorry, not sure if I can share the whole file, so here's that part:

    "definitions": {
        "AffectedItem": {
            "type": "object",
            "properties": {
                "Id": {
                    "format": "uuid",
                    "type": "string",
                    "example": "00000000-0000-0000-0000-000000000000"
                },
                "$Solution": {
                    "type": "string"
                },
                "$ItemType": {
                    "type": "string"
                },
                "$Created": {
                    "type": "boolean"
                },
                "$Deleted": {
                    "type": "boolean"
                },
                "$Hint": {
                    "type": "string"
                }
            }
        },

**Comment by Vovanella95** [comment]
@queen3  thanks! Will fix it asap!

**Comment by davorzlotrg** [comment]
I have the same issue with dots in property names. 

`{
  "openapi": "3.0.1",
  "info": {
    "title": "Api",
    "version": "v1"
  },
  "paths": {
	"/api/profiles/work-info": {
      "post": {
        "tags": [
          "Profile"
        ],
        "parameters": [
          {
            "name": "LANGUAGE",
            "in": "header",
            "description": "Controls the language the API uses"
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "Company.Id": {
                    "type": "integer",
                    "format": "int32"
                  },
                  "Company.Name": {
                    "type": "string"
                  },
                  "JobTitle": {
                    "type": "string"
                  }
                }
              },
              "encoding": {
                "Company.Id": {
                  "style": "form"
                },
                "Company.Name": {
                  "style": "form"
                },
                "JobTitle": {
                  "style": "form"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  }
}`
