### ISSUE TITLE
[QUESTION] Is it possible to change the generated method names?

### ISSUE THREAD

**Issue by GnosisSupport** [epam-cross-platform-lab/swagger-dart-code-generator#452]
From what I see currently the endpoint/method names include all possible parts of the path, e.g.

(https://server/swagger/ui/index#!/Solutions/Solutions_Get_SolutionItemTypes) 
/v2/SolutionItemTypes/{solutionPath]
(and by the way the swagger UI description is "Get Solution ItemTypes")

results in the generated method named

v2SolutionItemTypesSolutionPathGet

I wonder if there's a configuration (or it can be added) that allows the developer to control the resulting method names. I see the reason to include everything to make method names unique but it is not always desirable. In addition to be able to configure somehow (using a template etc) the names, maybe an option could be added to select between 
- full path
- that ui part Solutions_Get_SolutionItemTypes
- or the description "Get Solution ItemTypes" (with spaces removed)

**Comment by Vovanella95** [comment]
Hi @GnosisSupport currently we generating method name using path and method type. In this case you will always have unique method name. Currently, you can not modify method name generation, but if you have ideas, how to do this - you're welcome!

**Comment by Vovanella95** [comment]
@GnosisSupport I'm closing the issue. Please let us know in case of any ideas, issues or proposals
