### ISSUE TITLE
[FEATURE] Complex response object with additionalProperties

### ISSUE THREAD

**Issue by queen3** [epam-cross-platform-lab/swagger-dart-code-generator#454]
In the swagger we have a response defined like this:

"responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "title": "ItemData",
                            "type": "object",
                            "properties": {
                                "Summary": {
                                    "type": "string"
                                },
                                "Id": {
                                    "format": "uuid",
                                    "type": "string",
                                    "example": "00000000-0000-0000-0000-000000000000"
                                },
                                "Name": {
                                    "type": "string"
                                },
                                "Sequence": {
                                    "format": "double",
                                    "type": "number"
                                },
                                "Status": {
                                    "type": "string"
                                },
                                "CreatedBy": {
                                    "format": "uuid",
                                    "type": "string",
                                    "example": "00000000-0000-0000-0000-000000000000"
                                },
                                "CreatedOn": {
                                    "format": "date-time",
                                    "type": "string"
                                }
                            },
                            "additionalProperties": {
                                "type": "object"
                            }
                        }
                    }
                },

This is basically a free-form collection that can have any number of properties but some of them are predefined. In the C# code it looks like this:

	public class ItemData : IDictionary<string, object>, IDictionary
	{
		#region Reserved properties

		public Guid Id
		{
			get { return GetGuid(ItemDataProperty.Id); }
			set { this[ItemDataProperty.Id] = value; }
		}

		public string Name
		{
			get { return GetString(ItemDataProperty.Name); }
			set { this[ItemDataProperty.Name] = value; }
		}
  ....

However in the generated model the additionalProperties are not available:

typedef ItemsPage$Items = List<ItemsPage$Items$Item>;

@JsonSerializable(explicitToJson: true)
class ItemsPage$Items$Item {
  ItemsPage$Items$Item({
    this.summary,
    this.id,
    this.name,
    this.sequence,
    this.status,
    this.createdBy,
    this.createdOn,
  });

  factory ItemsPage$Items$Item.fromJson(Map<String, dynamic> json) =>
      _$ItemsPage$Items$ItemFromJson(json);

  @JsonKey(name: 'Summary')
  final String? summary;
  @JsonKey(name: 'Id')
  final String? id;
  @JsonKey(name: 'Name')
  final String? name;
  @JsonKey(name: 'Sequence')
  final double? sequence;
  @JsonKey(name: 'Status')
  final String? status;
  @JsonKey(name: 'CreatedBy')
  final String? createdBy;
  @JsonKey(name: 'CreatedOn')
  final DateTime? createdOn;
  static const fromJsonFactory = _$ItemsPage$Items$ItemFromJson;
  static const toJsonFactory = _$ItemsPage$Items$ItemToJson;
  Map<String, dynamic> toJson() => _$ItemsPage$Items$ItemToJson(this);

I guess the easiest fix (in this case of additionalProperties) would be to store/expose the json in fromJson() and reuse it in toJson(), and the predefined properties just modify the internal map (just like the C# code does).

**Comment by queen3** [comment]
Or even easier, for additionalProperties (or all) methods generate a "raw" accessor which returns just the json map. So in addition to e.g. v2ItemsCollectionPathGet() there will be v2ItemsCollectionPathGetRaw() which returns e.g. Map<> or dynamic.

**Comment by Vovanella95** [comment]
Hi @queen3, I have no ideas how to generate code for your case. Because additional properties means your object can have any count of properties of any or exact type. The only one way to handle it - to parse it by hands. 


If you have idea how can I generate it - let me know. But for now I'm closing the issue because I already had investigation on this.
