### ISSUE TITLE
Is it possible to exclude a class in a swagger model and manually defined it ?

### ISSUE THREAD

**Issue by plantiword** [epam-cross-platform-lab/swagger-dart-code-generator#463]
**Please describe a problem.**
We need to be able to exclude some classes (pagination feature for example) that are the same on many swagger models. When the package generates the code, it creates mutiple internal classes (for pagination), one on each swagger model. 

If we reference the generated code from other places in our project, this code cannot discriminate bewteen the different pagination classes.

***Describe the solution you'd like**
We want to be able to exclude certain classes when generating code using the package (for example using a switch to indicate class names or regex for which the package should not create the code).

**Comment by Vovanella95** [comment]
Hi, currently it's not possible. But you can override response by Map<String, dynamic> and parse it manually.
you can check `response_override_value_map` option. 

Is it helps you?

**Comment by plantiword** [comment]
Hi @Vovanella95 , thanks for the prompt response. I'll check with the dev team and let you know.

**Comment by fryette** [comment]
@plantiword any news?

Can we close the issue?

As well please take a look at the possibility to reduce the swagger file, it also helps to generate only what is needed.

**Comment by plantiword** [comment]
Hi, yes, please go ahead and close it. Many thanks.

**Comment by Vovanella95** [comment]
@plantiword  cool, let us know in case of any questions or issues!
