### ISSUE TITLE
[FEATURE] Migrate to use Chopper 5.0.x

### ISSUE THREAD

**Issue by RoarGronmo** [epam-cross-platform-lab/swagger-dart-code-generator#464]
**Is your feature request related to a problem? Please describe.**
Updated my project to use Chopper 5.0, but generated code then fails: 

I.E: 
![image](https://user-images.githubusercontent.com/11217296/189980850-b407fd70-5f0e-48c9-b1ad-dfcbfc959793.png)

and 
![image](https://user-images.githubusercontent.com/11217296/189981020-c59f38b1-54ab-41e9-bef6-7bd6bea584f7.png)

**Describe the solution you'd like**
Please migrate swagger_dart_code_generator to cope with Chopper 5.0.x

**Comment by RoarGronmo** [comment]
Please be aware that Chopper v5.0.x is Dart v2.17 dependent: 

![image](https://user-images.githubusercontent.com/11217296/189983194-aea9778f-554a-47f5-957c-61aaf1fcf3a9.png)

**Comment by RoarGronmo** [comment]
Confirming breaking change for use of `FutureOr`

![image](https://user-images.githubusercontent.com/11217296/189983793-3d1415e5-7d55-4934-9a14-bf8cb1d8274d.png)

**Comment by Vovanella95** [comment]
@RoarGronmo  good point. Will handle it!
