### ISSUE TITLE
[QUESTION] Auth via securitySchemes

### ISSUE THREAD

**Issue by vadimlukutin** [epam-cross-platform-lab/swagger-dart-code-generator#466]
I need auth by securitySchemes and security. But I cant find any generate method for send API Key.

**Comment by fryette** [comment]
Could you please describe the problem?

If you need to send API key feel free to use interceptors

https://github.com/lejard-h/chopper/issues/122

Please provide a way how you want to do it using clear chopper or HTTP client, to understand how generation can help.

**Comment by vadimlukutin** [comment]
Thank u. Its works.
