### ISSUE TITLE
[FEATURE] Overrides for classes from the Swagger documentation

### ISSUE THREAD

**Issue by Vikrech** [epam-cross-platform-lab/swagger-dart-code-generator#470]
Dear package maintainers,
 
Currently we experience some unpleasant issue with OpenApi documentation. As you could see in the example the class `Links` doesn't have any fields in documentation, but in reality it have some. It might be the case with HAL format for HATEOAS and probably this should be fixed on the backend side.

But from my point of view, it would be really nice if there would be an option for the package to override classes from documentation with other classes, the ones that could be manually written. Possibly it could be done by using class name from the OpenApi documentation and the other class name that should be exchanged with the path to this class.

So please let me know what do you think about this improvement?

OpenApi documentation json file has been attached to this message
[openapi.json.zip](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/9672686/openapi.json.zip)

**Comment by Vovanella95** [comment]
Hi @Vikrech 
I'm on business trip next 2 weeks. Will handle all tickets asap when return home :)
