### ISSUE TITLE
[FEATURE] Please Document How You Expect Enums to Be in the swagger.json file

### ISSUE THREAD

**Issue by jhancock4d** [epam-cross-platform-lab/swagger-dart-code-generator#496]
**Is your feature request related to a problem? Please describe.**
The documentation says that you support enum mappings, but it doesn't say in what format in the file. In the samples, I can't find anything but string values, no mappings that map ints to string values in the enums.

**Describe the solution you'd like**
Please provide explicit guidance on how you want enums presented in the swagger.json file.

As an example I have the following that works in many places but not here:

```
"ContactTypes": {
        "enum": [
          1,
          2,
          3
        ],
        "type": "integer",
        "description": "Contact Types",
        "format": "int32",
        "x-ms-enum": {
          "name": "ContactTypes",
          "modelAsString": true,
          "values": [
            {
              "value": 0,
              "name": "value__",
              "description": "value__"
            },
            {
              "value": 1,
              "name": "Person",
              "description": "Person"
            },
            {
              "value": 2,
              "name": "Organization",
              "description": "Organization"
            },
            {
              "value": 3,
              "name": "Government",
              "description": "Government"
            }
          ]
        }
      },
```

The OpenApi 1-3 schema doesn't support the mapping. V3.1 supports oneof, but it isn't clear if this supports one of.

I assume x-ms-enum isn't supported (Auto Rest) per above?

Does it support oneof instead?

**Swagger specification link**
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/
https://swagger.io/docs/specification/data-models/enums/
https://github.com/stankovski/AutoRest/blob/master/Documentation/swagger-extensions.md#x-ms-enum

**Comment by jhancock4d** [comment]
PS: if it doesn't support ms-x-enum it would be nice if it did, as this is pretty common out there in the wild and would solve the entire problem.

**Comment by Vovanella95** [comment]
Hi @jhancock4d , indeed we do not support 'ms-x-enum'. Could you share swagger file with such enums to implement and test fix?

**Comment by jhancock4d** [comment]
@Vovanella95 here's a link to one: https://api.cadlearning.com/help/v1/swagger.json

Note that OpenApi 3.1 also supports enums with "oneOf" that is perported to do the same. I'd suggest supporting both x-ms-enum and whatever the OpenApi 3.1 standard is for this.

**Comment by fryette** [comment]
I would focus on OpenApi 3.1 instead of custom tags as everything custom needs additional time to support.

**Comment by JohnGalt1717** [comment]
> I would focus on OpenApi 3.1 instead of custom tags as everything custom needs additional time to support.

x-ms-enum is not really a custom tag. It's the defacto standard and used by Microsoft, Google and Amazon to name just 3 large ones.

It just happened to be created by Microsoft while the company that runs Swagger wagged an ideological war about this for several years before finally giving in and accepting that yes, enums are key/value pairs and not just some hard coded text from the language that swagger originated from that didn't have numerical values. (like Dart before it finally was added properly)

**Comment by Vovanella95** [comment]
Hi @JohnGalt1717  @jhancock4d  I have implemented your feature. Looks like swagger you attached generated well. I am closing the issue.

**Comment by jhancock4d** [comment]
Thanks so much!!!
