### ISSUE TITLE
[FEATURE] Merge Models and Enums

### ISSUE THREAD

**Issue by jhancock4d** [epam-cross-platform-lab/swagger-dart-code-generator#499]
**Is your feature request related to a problem? Please describe.**
If you're using micro-services you'll often have shared enums and some models (i.e. Problem Details). Right now this generates duplicates even if the items are in the same project and inputs folder.

**Describe the solution you'd like**
I'd like all processing on the same project to compare all models and enums and if identical, they should be merged and shared.

**Swagger specification link**
N/A

**Comment by Vovanella95** [comment]
Hi @jhancock4d , it's not possible to avoid duplicated absolutely. You can have different enums with same name in different files. To avoid it you can import files with 'as' attribute. 

```dart
import 'service_1.dart' as first;
import 'service_2.dart' as second;

//feel free to use first.CarEnum and second.CarEnum

```

**Comment by Vovanella95** [comment]
@jhancock4d did I answered your question?
