### ISSUE TITLE
[BUG] Properties marked nullable in swagger file are not nullable in generated output

### ISSUE THREAD

**Issue by point-source** [epam-cross-platform-lab/swagger-dart-code-generator#506]
**Describe the bug**
I have a property on line 18748 of [this swagger](https://raw.githubusercontent.com/plaid/plaid-openapi/master/2020-09-14.yml) file like so:
```json
"limit": {
    "type": "number",
    "format": "double",
    "description": "For `credit`-type accounts, this represents the credit limit.\n\nFor `depository`-type accounts, this represents the pre-arranged overdraft limit, which is common for current (checking) accounts in Europe.\n\nIn North America, this field is typically only available for `credit`-type accounts.",
    "nullable": true
},
```

The generated output for this property is:
```dart
limit: (json['limit'] as num).toDouble(),
```

For reference, this is part of the AccountBalance model:
```dart
AccountBalance _$AccountBalanceFromJson(Map<String, dynamic> json) =>
    AccountBalance(
      available: (json['available'] as num).toDouble(),
      current: (json['current'] as num).toDouble(),
      limit: (json['limit'] as num).toDouble(),
      isoCurrencyCode: json['iso_currency_code'] as String,
      unofficialCurrencyCode: json['unofficial_currency_code'] as String,
      lastUpdatedDatetime: json['last_updated_datetime'] == null
          ? null
          : DateTime.parse(json['last_updated_datetime'] as String),
    );
```

When I try to deserialize the server response, it fails because Null is not a subtype of num.

**Expected behavior**
The generated output should allow the limit property (and other properties marked null) to be null.

**Swagger specification link**
[Link to swagger/OpenApi documentation](https://raw.githubusercontent.com/plaid/plaid-openapi/master/2020-09-14.yml)

**Library version used:**
master branch on commit b9ecb611312ca83e8a4dc8310edb67ad4a7d2789 (v2.8.7)

**Additional Info:**
I suspect the issue might be [on this line](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/blob/eb3d315938b405db90e84702d22d1a29f0b888d9/lib/src/swagger_models/responses/swagger_schema.dart#L102):
`..isNullable = (json[kIsNullable] ?? json[kIsNullable] ?? false) as bool;`

It appears to me like the intention was to handle both "x-nullable" and "nullable" cases but accidentally is checking "x-nullable" twice.

Patching this results in this output:
```dart
AccountBalance _$AccountBalanceFromJson(Map<String, dynamic> json) =>
    AccountBalance(
      available: (json['available'] as num?)?.toDouble(),
      current: (json['current'] as num?)?.toDouble(),
      limit: (json['limit'] as num?)?.toDouble(),
      isoCurrencyCode: json['iso_currency_code'] as String?,
      unofficialCurrencyCode: json['unofficial_currency_code'] as String?,
      lastUpdatedDatetime: json['last_updated_datetime'] == null
          ? null
          : DateTime.parse(json['last_updated_datetime'] as String),
    );
```

While this fixes the case that started this ticket, it did not fix a similar issue with the component on line 18570 as references from line 43202:
```json
            "PlaidError": {
                "description": "We use standard HTTP response codes for success and failure notifications, and our errors are further classified by `error_type`. In general, 200 HTTP codes correspond to success, 40X codes are for developer- or user-related failures, and 50X codes are for Plaid-related issues. An Item with a non-`null` error object will only be part of an API response when calling `/item/get` to view Item status. Otherwise, error fields will be `null` if no error has occurred; if an error has occurred, an error code will be returned instead.",
                "type": "object",
                "additionalProperties": true,
                "title": "Error",
                "nullable": true,
                "properties": {
                    "error_type": {
                        "$ref": "#/components/schemas/PlaidErrorType"
                    },
...
```

Reference to the component:
```json
                    "error": {
                        "$ref": "#/components/schemas/PlaidError"
                    },
```

**Comment by aledavidgueva** [comment]
Hi! I have the same problem starting from version 2.8.4... By the moment, i rollback to version 2.8.3

**Comment by Vovanella95** [comment]
@point-source  Could you please share swagger of `AccountBalance`?

**Comment by point-source** [comment]
@Vovanella95 I did. It's right there where it says "Link to Swagger". 

But here's another link just in case: https://raw.githubusercontent.com/plaid/plaid-openapi/master/2020-09-14.yml

I just converted it to json with a yaml to json converter online.

**Comment by Vovanella95** [comment]
@point-source  cool, will take a look!

**Comment by point-source** [comment]
As best I can tell, the second example in my post is because referenced models which have a nullable flag are not marked nullable. Line [684 of swagger_models_generator.dart](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/blob/master/lib/src/code_generators/swagger_models_generator.dart#L685) should be handling this but the `prop.isNullable` flag is not properly set at the time that line is executed.

**Comment by fryette** [comment]
@point-source will you be able to provide a pull request with a fix?

**Comment by point-source** [comment]
Sadly not. I was only able to fix the first issue but not the second. I don't understand this library well enough to close the entire ticket. I can still open a PR though if you want to pull in the bit that I did do. Perhaps with some guidance on where to look I can help with the rest?

**Comment by point-source** [comment]
Is there any other way I can help with this?

**Comment by Vovanella95** [comment]
@point-source  sorry no updates for now. Will take a look into it this week. Thanks for patience!
