### ISSUE TITLE
[QUESTION] How to add error converter?

### ISSUE THREAD

**Issue by InAnadea** [epam-cross-platform-lab/swagger-dart-code-generator#514]
`$JsonSerializableConverter` generated only for successful responses but my swagger documentation also contains a body for error responses.

<img width="515" alt="Screenshot 2022-12-06 at 13 39 39" src="https://user-images.githubusercontent.com/93736963/205902096-8ecc1f8f-2b71-450c-8d66-0fa26e4aedc4.png">

Maybe we can use the same algorithm for error responses?

**Comment by Vovanella95** [comment]
Hello @InAnadea , It's you can add converter next way:

```dart
final petsApi = PetServiceYaml.create(
    client: ChopperClient(
      converter: MyConverter(),
      /// any other settings
    ),
  );
```

**Comment by Vovanella95** [comment]
If you will have questions - reopen issue
