### ISSUE TITLE
[QUESTION] How to change name of the model name?

### ISSUE THREAD

**Issue by InAnadea** [epam-cross-platform-lab/swagger-dart-code-generator#516]
**I have swagger documentation with an error.**
There is one mistake in the swagger documentation. It is a wrong DTO field name. I think it's because of a missing key in the swagger generation configuration. But I can't wait to fix it and I can't edit swagger-generated JSON files every time.

**Comment by Vovanella95** [comment]
Hi @InAnadea , Could you provide part of swagger file and expected generated result?

**Comment by Nazarovv676** [comment]
Yes, sure!

There is an error here. The actual response gives the `name`, not the `projectName`,

```
"ProjectDto": {
    "type": "object",
    "properties": {
        "id": {
            "type": "integer",
            "format": "int64"
        },
        "owner": {
            "$ref": "#/components/schemas/OwnerDto"
        },
        "projectName": {
            "type": "string"
        }
    }
},
```

**Comment by Vovanella95** [comment]
Ahhh I see your point, @Nazarovv676 ,

you can try to use `overriden_models` feature.

Just put ProjectDto to overriden models list and implement it as you want.

Let me know if you will have problems with this.
