### ISSUE TITLE
[FEATURE] Generate multiple clients based on path segments

### ISSUE THREAD

**Issue by fncap** [epam-cross-platform-lab/swagger-dart-code-generator#519]
Hi, I'm fun of nswag and I use it lot of the time when I write in c#!

When I encountered flutter, the first thing that I've been searched for was a tool like nswag ... and I did fall in love with this fantastic project! 

For this reason I would say thank you for your time spent in this work... it saved my time!
 
But ... whenever we encounter a beautiful stuff ... we always want more and more ...
As I wrote at the beginning, nswag is a fantastic tool ... and it has a nice feature that could be a must-have for this side!

Please take a look at the following piece of code:
https://github.com/RicoSuter/NSwag/blob/fca7e8126d634a7971f10c36d274b4e397577ab3/src/NSwag.Commands/Commands/CodeGeneration/OperationGenerationMode.cs#L17-L18

As it displays ... nswag allow different types of client generation modes.
Most useful of them, is `MultipleClientsFromPathSegments` that "simply" generates multiple clients with different operations searching them in path's segments.
 
Could you refer to that mode and implements it also?
It will very appreciate!
Thanks!

**Comment by Vovanella95** [comment]
Hi @fncap , why just not to create new chopper client each time when make a call? I think this feature will be used only by you

**Comment by fncap** [comment]
Hi @Vovanella95, thanks for your reply!

Looking to generated code, I found a single Client implementation, with many functions that are bounded to webapi endpoints.

In my daily work, I produce webapi endpoints that organised with namespaces.
For example, I could have something like `/host/api/services/app/module-name/feature-name/operation-name` that results in a generated method like `apiServicesAppModuleNameFeatureNameOperationNameGet` (ends with Get if HttpGet or else if endpoint is served with different Http method) inside a unique Client class.

nswag simplify this scenario, assuming last two segments of url respectively for Client name and Operation name. 
(most significant terms at the right)
So with the example above we could have a generated client named FeatureName with a function named OperationName, omitting the suffix Get if there is only one Http method inside swagger.

In this way you could have your code organised efficiently, IMHO.

**Comment by Vovanella95** [comment]
Hi @fncap , I understand your idea, but I will not implement it. You can create repository and create client each time manually. 

```dart
class ApiRepository {
Future<UserModel> getUser ({required int id}) {
    return ApiService(client: _createClient).getUser(id: id);
  }
}
```
