### ISSUE TITLE
[BUG] Generation fails if input_folder setting doesn't end with a "/"

### ISSUE THREAD

**Issue by bmcclure** [epam-cross-platform-lab/swagger-dart-code-generator#526]
**Describe the bug**

I was getting the following error when running my build on Windows 11:

```[INFO] Running build...
[SEVERE] swagger_dart_code_generator on lib/swaggersopenapi.yaml:

type 'Null' is not a subtype of type 'YamlMap' in type cast
```

My input folder was specified as "lib/swaggers" and my "input_urls" includes a file names openapi.yaml that gets downloaded during the build.

Changing the input_folder to "lib/swaggers/" fixed the issue for me, however this seems like it should not actually be needed.

**To Reproduce**
1. Install swagger-dart-code-generator in a Flutter project (in Windows 11, but I'm not sure if that matters)
2. Specify input_folder in build.yaml as "lib/swaggers"
3. Make sure the lib/swaggers folder exists
4. Specify a swagger file in the "input_urls" option (I'm not sure if this is required for the issue to occur or if it will also happen with a local-only file)
5. Run build_runner and get error mentioned above.

**Expected behavior**

The input_folder option should work identically whether it ends in a slash or not.

**Library version used:**
2.9.0

**Comment by Vovanella95** [comment]
@bmcclure Unfortunatelly, my processor does not support Windows 11 😆 

Will try to do something with this issue

**Comment by bmcclure** [comment]
The code generator does seem to work fine for me on Windows 11 as long as the path is specified with a slash at the end. I haven't tested every feature though.

**Comment by Vovanella95** [comment]
@bmcclure  so generator works good on Windows 11? Can we close issue?

**Comment by bmcclure** [comment]
It works on Windows 11 but not with the default configuration. I would consider it a bug that input_folder must end with a slash on Windows 11 (and doesn't have a slash in the default value, meaning it's broken on Windows 11 until you add a slash to the end of the input path).

**Comment by Vovanella95** [comment]
@bmcclure So with slash it works everywhere? 

Now in example inputFolder and outputFolder already ands with slash. Just add slashed everywhere and everything will work. Please reopen issue if I'm wrong.

`output_folder: "lib/swagger_generated_code/"`

**Comment by bmcclure** [comment]
Yes you're right, but that seems like a bug to be fixed since everyone using it on Windows will have to discover the same weird behavior that doesn't match how it works on other systems.

**Comment by Vovanella95** [comment]
Hi @bmcclure, I think for now I need to add remark to README.md
