### ISSUE TITLE
Generate null body instead of empty body.

### ISSUE THREAD

**Issue by queendevelopers** [epam-cross-platform-lab/swagger-dart-code-generator#533]
**Please describe a problem.**
We are working on a project, In which if we pass an `empty body (i.e. {} )` to a `DELETE` request then the API throws an error. Because the default swagger_generator generates the empty map for all methods.

**Describe the solution you'd like**
Is there any way we can make Body (Empty map) `null` through `build.yaml` options when the method is `DELETE`? Please also let me if there's a better approach to handle these kinds of situations.

**Comment by Vovanella95** [comment]
Hi @queendevelopers , please provide example of swagger file or part of it

**Comment by Vovanella95** [comment]
@queendevelopers  closing the issue because you did not provided details we asked. Feel free to reopen it and provide details
