### ISSUE TITLE
[QUESTION] Multipart File

### ISSUE THREAD

**Issue by biongoo** [epam-cross-platform-lab/swagger-dart-code-generator#534]
**Please describe a problem.**
Hi! I'm creating avatar uploader and I can't find anywhere solution or example how to convert file. Could I ask you how to convert my http.MultipartFile / File to List of Strings to send it?

**Comment by fryette** [comment]
@biongoo could you please share swagger file?

**Comment by biongoo** [comment]
I will show that on public example: [https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/blob/master/example/lib/swagger_generated_code/pet_service_json.swagger.dart#L199](Example). There is method "petPetIdUploadImagePost" and it has param "List<String>? file,". I have file in type "File" or could have in type "http.MultipartFile" but how can I convert this to "List<String>" to use that method?

**Comment by malaschitz** [comment]
I have the same problem. When is used multipart/form-data, last version of swagger-dart-code-generator generates for it object body with string field. And probably send it as simple json.

**Comment by Vovanella95** [comment]
Hi @biongoo  @malaschitz , I'm not sure how to send image with multipart body. Possible, our generator generated body incorrectly. I will research, how to do this, fix generator and let you know

**Comment by Vovanella95** [comment]
Hi all, @malaschitz , @biongoo !

I've checked how such fields should be generated, and looks like good option to generate `List<int>`, like described [in this tipic](https://stackoverflow.com/questions/59988978/how-to-send-file-using-chopper). `List<int>` can be easely converted to and from `Utf8List`. Let me know in case of questions.
