### ISSUE TITLE
[FEATURE] DateTime Query Parameters

### ISSUE THREAD

**Issue by cputoaster** [epam-cross-platform-lab/swagger-dart-code-generator#536]
**Is your feature request related to a problem? Please describe.**
I am trying to use query parameters in a post function call with a datetime format, which is defined as a valid primitive type in swagger

```
"/core/v1/staff": {
   "post": {
    "operationId": "CoreListStaff2",
    "parameters": [
...
     {
      "name": "filterStartSyncModifiedAt",
      "in": "query",
      "required": false,
      "type": "string",
      "format": "date-time"
     }
...

->

Future<chopper.Response<CollectionResponseStaff>> coreV1StaffPost({
    ...
    String? filterStartSyncModifiedAt,
    ...
```
The function parameters in Dart just show String?, not DateTime?.

**Describe the solution you'd like**
The query parameter should be of type DateTime if the swagger definition is of format date-time

```
Future<chopper.Response<CollectionResponseStaff>> coreV1StaffPost({
    ...
    DateTime? filterStartSyncModifiedAt,
    ...
```

**Swagger specification link**
[query parameters](https://swagger.io/docs/specification/2-0/describing-parameters/#query-parameters)
[primitive types](https://swagger.io/specification/v2/?sbsearch=primitive%20type)

**Comment by Vovanella95** [comment]
Hi @cputoaster , fixed and will be released in `2.13.4`
