### ISSUE TITLE
[QUESTION] enum generate value_{integer} Is this a bug from the recent changes?

### ISSUE THREAD

**Issue by orangeyong** [epam-cross-platform-lab/swagger-dart-code-generator#539]
After the recent version upgrade to 2.10.0, I starting to receive this naming error, where the generated enum defined x-enumNames being ignored by the generator. I am not so sure if any related plugin causing this.

![image](https://user-images.githubusercontent.com/17298163/215343788-3d2e0765-571d-4573-99dc-1a2a06815363.png)

the part of the swagger generated json input as below
![image](https://user-images.githubusercontent.com/17298163/215343886-b8f5b64d-2fa4-4756-b9d5-21afe89facb7.png)

before this it worked very well. the xml input are the same before and after the update (format openapi 3.0.1)
i am now on flutter 3.7

If someone else facing the same thing?

previously it was generating this output
![image](https://user-images.githubusercontent.com/17298163/215343731-3b118fb5-c043-44ff-91ef-db835a32a4d9.png)

i am able to get back previous output when i forced the version to
- swagger-dart-code-generator: 2.8.9 or 2.9.0

**Comment by Vovanella95** [comment]
Hi, @orangeyong , thanks for raising issue. Indeed new Dart 3 enums broken this feature. I will fix it asap

**Comment by Vovanella95** [comment]
@orangeyong  seems to be good now :)
