### ISSUE TITLE
[BUG]Empty String("") is considered as null when enums are generated

### ISSUE THREAD

**Issue by ankit-triomics** [epam-cross-platform-lab/swagger-dart-code-generator#549]
**Describe the bug**
when i generate models and enum from my swagger, there are multiple enums null in a single enum class

** generated enum **
enum RegistryOutputFormat {
  @JsonValue(null)
  swaggerGeneratedUnknown(null),

  @JsonValue('json')
  json('json'),
  @JsonValue('xml')
  xml('xml'),
  @JsonValue('excel')
  excel('excel'),
  @JsonValue('')
  $null('null'),
  @JsonValue('null')
  $null('null');

  final String? value;

  const RegistryOutputFormat(this.value);
}

** assosciated swagger definition**

"format": {
                        "enum": [
                            "json",
                            "xml",
                            "excel",
                            "",
                            null
                        ],
                        "type": "string",
                        "nullable": true,
                        "title": "Format in which data needs to be exported"
  },

the swagger file itself has a empty string and null value as option but it generates both as null in my enum build, this was not happening before.

**To Reproduce**
 - flutter clean
 - flutter pub get
 - flutter packages pub run build_runner build --delete-conflicting-outputs

**Expected behavior**
 - the empty string should not be treated as a null value if there's already a null value explicitily present in the enum

**Swagger specification link**
- can provide privately

**Library version used:**
2.10.0

**Additional context**

**Comment by eirikskogoy** [comment]
Is there any timeline on when this will be fixed?

**Comment by Vovanella95** [comment]
Hi @eirikskogoy , will do my best to fix it next week (at the beginning of week). Thanks for patience!

**Comment by Vovanella95** [comment]
@eirikskogoy  just one thing: could you share full swagger RegistryOutputFormat model descriptiopn?

**Comment by ankit-triomics** [comment]
@Vovanella95 will this work 
`"RegistryOutput": {
                "type": "object",
                "description": "Registry output serializer.",
                "properties": {
                    "registryId": {
                        "type": "string",
                        "readOnly": true
                    },
                    "name": {
                        "type": "string",
                        "nullable": true,
                        "title": "Name of the registry"
                    },
                    "program": {
                        "type": "string",
                        "nullable": true,
                        "title": "Program in which it is part of"
                    },
                    "format": {
                        "enum": [
                            "json",
                            "xml",
                            "excel",
                            "",
                            null
                        ],
                        "type": "string",
                        "nullable": true,
                        "title": "Format in which data needs to be exported"
                    },
                    "structure": {
                        "type": "object",
                        "additionalProperties": {},
                        "description": "Structure of attributes "
                    },
                    "studyId": {
                        "type": "string",
                        "description": "Primary key for model objects",
                        "nullable": true,
                        "readOnly": true
                    }
                },
                "required": [
                    "registryId",
                    "studyId"
                ]
            },`

**Comment by eirikskogoy** [comment]
Awesome! thanks for your quick response. Tell me if you need something else than what ankit-triomics sent to you :)

**Comment by eirikskogoy** [comment]
Sorry, it seems like the thing we see is another thing than this issue.

In version 2.8, swagger unknown did return the string 'swaggerGeneratedUnknown', but now it returns null.
Is this by intention?

**Comment by Vovanella95** [comment]
Hi @eirikskogoy , yes, it's expected. We integrated Flutter 3 enums feature. So null is swaggerGeneratedUnknown now.

**Comment by Vovanella95** [comment]
@eirikskogoy  so issue is fixed?

**Comment by Vovanella95** [comment]
@eirikskogoy  and one more thing.

If you received null - it means it's swaggerGeneratedUnknown (value does not fit any of values of enum)
If you want to send null, but parameter is not nullable - put Enum.swaggerGeneratedUnknown

**Comment by eirikskogoy** [comment]
I do think ankit-triomics still has a problem :)

**Comment by ankit-triomics** [comment]
yes i still have the issue @Vovanella95 @eirikskogoy

**Comment by Vovanella95** [comment]
@ankit-triomics  am I right this part of code has issue?

```json
"RegistryOutput": { "type": "object", "description": "Registry output serializer.", "properties": { "registryId": { "type": "string", "readOnly": true }, "name": { "type": "string", "nullable": true, "title": "Name of the registry" }, "program": { "type": "string", "nullable": true, "title": "Program in which it is part of" }, "format": { "enum": [ "json", "xml", "excel", "", null ], "type": "string", "nullable": true, "title": "Format in which data needs to be exported" }, "structure": { "type": "object", "additionalProperties": {}, "description": "Structure of attributes " }, "studyId": { "type": "string", "description": "Primary key for model objects", "nullable": true, "readOnly": true } }, "required": [ "registryId", "studyId" ] },
```

**Comment by ankit-triomics** [comment]
yes @Vovanella95 , as you can see it has format field which is enum and it has "" and null both which gets generated to null after running build runner

**Comment by Vovanella95** [comment]
@ankit-triomics  got it. Will fix it next week!

**Comment by ankit-triomics** [comment]
thanks @Vovanella95 , will check back next week ;)
