### ISSUE TITLE
[QUESTION] excluded and Overriden Models: one file for each yaml?

### ISSUE THREAD

**Issue by margat78** [epam-cross-platform-lab/swagger-dart-code-generator#550]
**Please describe a problem.**
When use a more Api_xxx.yaml file and exclude more Models form different api file with 

`overriden_models: [ModelFromApi1, ModelFromApi2]`

**Describe the solution you'd like**
I would like:

-  different overriden_models_xxx.dart file 

- Instead of 
`import 'overriden_models.dart';`
 I think is userful generate `part of api_xxx.swagger.dart` so in overriden_models_xxx.dart I can use deserializer of inner object and enums of ModelFromApi1 defined in api_xxx.swagger.dart

**Comment by Vovanella95** [comment]
Hi @margat78 , good idea. Separate overriden_models for each swagger file can save us from conflicts. Will implement it after closing issues!

**Comment by Vovanella95** [comment]
Implemented :) @margat78
