### ISSUE TITLE
[BUG] Swagger model starting with "Map" produces invalid .swagger.dart api

### ISSUE THREAD

**Issue by mgj** [epam-cross-platform-lab/swagger-dart-code-generator#553]
**Describe the bug**
An endpoint which return a schema/model with a name that starts with `Map` breaks code generation. Renaming the `MapXxx`-model to `MyMapXxx` resolves the issue.

The generated `swagger_broken.swagger.dart` looks like this:
```
Future<chopper.Response<MapImage>> restMapImageGet({String? xApiVersion}) {
    return _restMapImageGet(xApiVersion: xApiVersion);
  }
```

**To Reproduce**
I have created a repository with a minimal example: https://github.com/mgj/flutter_openapi_generator_issue
* Clone it
* Run `flutter pub get`
* Run `flutter packages pub run build_runner build`

Observe that the generated `swagger_broken.swagger.dart` is incorrect while `swagger_works.swagger.dart` is correct.

**Expected behavior**
The generated `swagger_works.swagger.dart` *should* instead looks like this:
```
Future<chopper.Response<MyMapImage>> restMapImageGet({String? xApiVersion}) {
    generatedMapping.putIfAbsent(MyMapImage, () => MyMapImage.fromJsonFactory);

    return _restMapImageGet(xApiVersion: xApiVersion);
  }
```

**Swagger specification link**
Working: https://github.com/mgj/flutter_openapi_generator_issue/blob/main/generator_issue/lib/rest/openapi/swagger_works.json
Broken: https://github.com/mgj/flutter_openapi_generator_issue/blob/main/generator_issue/lib/rest/openapi/swagger_broken.json

**Library version used:**
swagger_dart_code_generator: 2.10.1

**Additional context**
No additional context but please let me know if there is any more information I can provide to help resolve this issue.

**Comment by Vovanella95** [comment]
Hi @mgj , thanks for patience. Issue is fixed!. Will be available in 2.10.3 in a day or two!
