### ISSUE TITLE
Build process does not detect Second swagger file content changes

### ISSUE THREAD

**Issue by RoarGronmo** [epam-cross-platform-lab/swagger-dart-code-generator#556]
I have two swagger files in my setup, if do changes to my second swagger file, the build process does not detect them and will not do a rebuild.

Short remedy: Delete all generated files manually and do a build again.

Command used: 
`flutter packages pub run build_runner build --delete-conflicting-outputs`

Please see zip for files
[swagger.zip](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/10816686/swagger.zip)

The section in file `m_office_bing_locations_query_api.swagger`
```
        "parameters": [
            {
                "name":"query",
                "in":"query",
                "required":true,
                "description":"Query text",
                "schema": {
                    "type":"string"
                }
            },
            {
                "name":"key",
                "in":"query",
                "required":true,
                "description":"API key",
                "schema": {
                    "type":"string"
                }
            }
        ],
```
from line 13 was tried added, but the builder didn't detect that change.
Doing changes to the other (first) swagger file triggers a change.

**Comment by Vovanella95** [comment]
Hi @RoarGronmo , I've investigated this issue, and it can not be fixed using our current approach (combining of local files and downloading files from internet). Files on internet also can be changed and generator can not detect it. So, issue will not be fixed, sorry. 

**Solution: Just remove folder with generated code :)**

**Comment by RoarGronmo** [comment]
That's fair enough, you should emphasize that issue in docs !!
