### ISSUE TITLE
[FEATURE] Ability to rename files downloaded from input_urls

### ISSUE THREAD

**Issue by frederikstonge** [epam-cross-platform-lab/swagger-dart-code-generator#558]
It would be really nice if we had the ability to rename the downloaded files from input_urls. If two of your input urls are "swagger.json", it will conflicts. It also impact the generated class name.

**Comment by Vovanella95** [comment]
Hi @frederikstonge , good idea, if you really have such issue - I will add ability to do this.

**Comment by frederikstonge** [comment]
Well, right now, I just copy/paste the whole swagger.json into a local file with the desired name. If the feature was available, I would use it, but it's not mandatory.

**Comment by Vovanella95** [comment]
@frederikstonge  you can implement it if you want :D 

You need just do the next in generator_options.dart 
```dart
@JsonKey(defaultValue: [])
  List<String> inputUrls;
```

replace to

```dart
@JsonKey(defaultValue: [])
  List<InputUrlModel> inputUrls;

class InputUrlModel { // should be serializable
String url;
String? fileName; // should be not mandatory
}
```

Something like this. Then you will be able to set

```yaml
input_urls:
  url: "url/to/file.json"
  fileName: "file_renamed.json"
```

**Comment by bozau** [comment]
Hi @Vovanella95 ,

Just working through adding this feature, just wanted to double check about the g2.dart files, what's the process of re-generating it, or are they renamed to g2 because they are actually manually made/updated (there's a comment at the top saying it's generated).

Cheers.

Boz.
