### ISSUE TITLE
[BUG] doesn't generate models

### ISSUE THREAD

**Issue by ghost** [epam-cross-platform-lab/swagger-dart-code-generator#579]
**Describe the bug**
I'm trying to generate client for [this swagger file](https://coddingtonbear.github.io/obsidian-local-rest-api/openapi.yaml).
api is generated without any errors but none of specified models and schemes are generated. I'm not sure if its a problem with file itself or this package but using swagger's official editor I could generate client for dart(it's old dart).

**To Reproduce**
use [this file](https://coddingtonbear.github.io/obsidian-local-rest-api/openapi.yaml) and generate.

**Swagger specification link**
[link](https://coddingtonbear.github.io/obsidian-local-rest-api/)

**Library version used:**
 2.10.3

**Comment by Vovanella95** [comment]
Hi @raminsafaei , please share your build.yaml configuration. In my case all models generated (there are only 2 NoteJson and Error). What is an actual issue then? 

My Telegram: `@vovanella95` you can contact me directly to solve this issue. Waiting for response!

**Comment by Vovanella95** [comment]
@raminsafaei , let's look into the problem not from swagger editor side, but from logical side. Your swagger has only 2 models - they are generated. `SearchsimpleMatch` is not a model, it's needed, possible, for some external things. `/search/simple` request required just one query parameter `query`.  I don't understand why this model needed and do not see problem in generation of your swagger.

Please let me know if you're not agree with me.

**Comment by Vovanella95** [comment]
@raminsafaei  do you really need these extra models? Why?

**Comment by Vovanella95** [comment]
@raminsafaei  Can not accept your opinion, sorry. `/search/simple` request has `query` parameter. This parameter is `String`. No additional models needed to use this method in any way.

**Comment by ihorkozar** [comment]
met the same problem too (
