### ISSUE TITLE
[BUG] should ignore dot files in input folder

### ISSUE THREAD

**Issue by ichiko** [epam-cross-platform-lab/swagger-dart-code-generator#591]
**Describe the bug**
when "Input folder" has swagger files and `.gitkeep`, this generator throws following error.

```
[INFO] Running build...
[SEVERE] swagger_dart_code_generator on input_folder/.gitkeep:

FormatException: Unexpected end of input (at character 1)
```

It occurs depend on file names in input folder.

work well (same as example):
```
- .gitkeep
- pet_service_json.json
- pet_service_swagger.swagger
- pet_service_yaml.yaml
```

not work well (occurs the error above):
```
- .gitkeep
- custom_pet_service_json.json
- custom_pet_service_swagger.swagger
- custom_pet_service_yaml.yaml
```

**To Reproduce**
- In `example/input_folder`, RENAME `pet_service_*.*` to `custom_pet_service_*.*`.
- run `flutter pub run build_runner build --delete-conflicting-outputs`
- then get the error

**Expected behavior**
dot files should ignored from input files.

**Library version used:**
2.10.4, 2.10.3

**Comment by Vovanella95** [comment]
Hi @ichiko , sorry can not reproduce it on my PC. 

According code, we use only filed ends with `.json` `.yml` and `.swagger`

```dart
final filesList = Directory(normalize(options.inputFolder)).listSync().where(
      (FileSystemEntity file) =>
          _inputFileExtensions.any((ending) => file.path.endsWith(ending)));
```

I will close issue, if you want, you can try to fix it by yourself and create PR (or let me know how can I fix it). I am only one who support this package and. I can not reproduce it. Sorry.
