### ISSUE TITLE
[BUG] Generated enum files import collection package but do not appear to require it

### ISSUE THREAD

**Issue by point-source** [epam-cross-platform-lab/swagger-dart-code-generator#596]
**Describe the bug**
Many of the generated files include an unused import of`package:collection/collection.dart` which causes analysis warnings and drops the pub.dev score if not manually removed. 

**To Reproduce**
Generate code with [this swagger file](https://developer.disguise.one/specs/service.swagger.json) and observe that `service.enums.swagger.dart` import the collection package even though it does not appear to be used.

**Expected behavior**
Either do not import the package or add an analysis/linter exception to the file to ignore.

**Swagger specification link**
https://developer.disguise.one/specs/service.swagger.json

**Library version used:**
2.10.4

**Comment by Vovanella95** [comment]
Hi @point-source , you can just exclude all .swagger.dart files in `analysis_options.yml.` It's good practice.
