### ISSUE TITLE
[BUG] 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by ihorkozar** [epam-cross-platform-lab/swagger-dart-code-generator#601]
When generating I get the following error. Is there any way to understand where exactly it occurs?
`[SEVERE] swagger_dart_code_generator on lib/data/swagger/server_api.json:

type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast
`

The error appeared after updating the swagger documentation. There is probably a possibility that something is wrong with the documentation, but it is not small and maybe you can tell me how to look for the source of the problem.

**Comment by ihorkozar** [comment]
@Vovanella95 Thanks for the answer, I found an error in the documentation by the method of excluding endpoints one by one. It would just be somehow more convenient if the error indicated the dto and the endpoint with which the problem is related, but this is probably unrealizable (

**Comment by Vovanella95** [comment]
@ihorkozar cool. I'm closing the issue. Let us know in case of any questions.

For now we don't plat to add advanced debug information. Feel free to implement it :)
