### ISSUE TITLE
[FEATURE] Ability to replace models

### ISSUE THREAD

**Issue by DenisAnkh** [epam-cross-platform-lab/swagger-dart-code-generator#603]
It would be great to have ability to replace some generated models with self ones . 

Let's there are the following generated from API models:
```dart
Future<List<OrderDto>> getOrders() {
...
}
class OrderDto {
  List<OrderItem> items;
  ...
}
class OrderItemDto {
  int orderId;
  ...
}
```

I need to extend `OrderDto` and `OrderItemDto` as follow:
```dart
/// replaced_models.dart
class OrderModel extend OrderDto {
   // here are some code...
}
class OrderItemModel extend OrderItemDto {
   // here are some code...
}
```
... to get the `OrderModel` and `OrderItemModel` instead of `OrderDto` and `OrderItemDto` in the whole generated code. 
**Important**: The `OrderDto` and `OrderItemDto` must be generated as well (because it is used as base classes for `OrderModel` and `OrderItemModel`) but not used in the generated API methods.

The simpliest way to do it is to add property '**replace_models**' (like 'overriden_models') and '**replace_models_file**':
```dart
  replace_models_file: 
    - '../../domain/models/replaced_models.dart' (or even 'package:app_domain/replaced_models.dart')
  replace_models: 
    - OrderDto: "OrderModel"
    - OrderItemDto: "OrderItemModel"
```
Optional property '**replace_models_file**' contains path to file 'replaced_models.dart' with our overriden models. If the property not supplied then file named "replaced_models.dart" will be imported as part by default. 

The feature would give ability to extend any generated models and use the extended models in generated methods. 
In the case the generated code would be like follow:
```dart
import  '../../domain/models/replaced_models.dart';

Future<List<OrderModel>> getOrders() {
...
}

//The model OrderDto has been generated but replaced with OrderModel in generated methods and properties of other generated models
class OrderDto {
  List<OrderItemModel> items;  //internal properties type OrderItemDto in generated models must be replaced with OrderItemModel
  ...
}
//The model OrderItemDto  has been generated but replaced with OrderModel in generated methods and properties of other generated models
class OrderItemDto {
  int orderId;
  ...
}
```

In client code it will like so:
```dart
final orders =  await api.getOrders(); // will have type List<OrderModel>
final orderItems = orders[0]!.items; // will have type List<OrderItemModel>
```

**Comment by fryette** [comment]
I still don't see any purpose in that.
What is the real use case of it?

**Comment by DenisAnkh** [comment]
> I still don't see any purpose in that.
> What is the real use case of it?

There are a few purposes:
1) It will allow to have simple ability to exclude direct using of generated models from other app layers. In example above we will just to work with OrderModel and OrderItemModel instead of generated OrderDto and OrderItemDto. It give more abstract and layer separation.
2) It will allow to get/build more usefull and specific models than generated by extending the generated ones.  For example OrderModel could implement more interfaces, could have specific methods, factories, properties or fields:

For example let see the psevdo code:
```dart
//a generated model
class OrderDto {
  @JsonKey(name: 'id')
  final int id;
  @JsonKey(name: 'items')
  final List<OrderItemDto> items;
  @JsonKey(name: 'price')
  final double price;
}
```
But let our app need more logic, factory methods, more properties, more fields, more interfaces in the model.  So we can just extend OrderDto like below:
```dart
//our overriden model
class OrderModel extends OrderDto implements PriceCheckable {
   List<OrderPriceCheck>? priceCheckers;

   //Some app specific (and may be very strange) logic that we need to have in the OrderModel...
  factory OrderModel.withPriceChecks(List<OrderPriceCheck> priceCheckers){....}

   //Some app specific (and may be very strange) logic that we need to have in the OrderModel...
  @override 
   OrderPriceCheckResult checkPrice() {     
     if(priceCheckers != null) {
       for(final priceChecker in priceCheckers){
          checkResult = priceChecker.check(this);
          if(!checkResult.isFail) return checkResult;
        } 
     }
   }
}
```

Using in client code: 
```dart
final orderModel = OrderModel.withPriceCheckers(priceCheckers);
final priceCheck = orderModel.checkPrice();
if(priceCheck == null) {
   await api.sendOrder(orderModel);
}
```

**Comment by fryette** [comment]
> _It will allow to have simple ability to exclude direct using of generated models from other app layers. In example above we will just to work with OrderModel and OrderItemModel instead of generated OrderDto and OrderItemDto. It give more abstract and layer separation._

1. And you are right, you should avoid using DTO in the application on lvl higher than services and should introduce some kind of mapping. In another case even if you introduce YOUR models in case of breaking changes you will have the same result...app will not work and you need to make changes on ALL levels of the app.

>_It will allow to get/build more useful and specific models than generated by extending the generated ones. For example OrderModel could implement more interfaces, could have specific methods, factories, properties or fields:_

Based on the statement above(1 point) you should not use this models directly. Instead, you need to introduce **your** own models and make the mapping, extension..more properties and etc. You can imagine that library as SDK. Like Firebase. If in one day you will want to exchange Firebase/Swagger codegen with...any other tool you should design your app with the possibility to avoid 1 Millon changes by isolation of that logic and affect ideally only 1 layer of the application. And if your application at the moment relays on the models...and your API changes and you need to adjust all layers...smth is definitely wrong with app architecture.

**Comment by DenisAnkh** [comment]
[fryette](https://github.com/fryette), thank you for reply. Currently we are working with a big API, that have a lot of big DTOs and methods. We are following layered architecture where Models are separated from DTOs. To link them there are DataMappers with modelFromDto() and modelToDto(). 

So in our app layer we are working only with the models (not dtos). It is working good and clean but causes a lot of boilerplate code (for each DTO we need develop a Model with all props, copyWith(), coperWithWrapped() and etc). One way to radically speed up development on early phase is to use DTOs in app layer, but it is very dirty way. Another way is to extend Models from DTOs and make the replacement in generator. 

This way will allow use Models in app layers and do not create a lot of boilerplate code on the early phases.

**Comment by DenisAnkh** [comment]
[fryette](https://github.com/fryette), OK, I will try. Thank you for the very usefull package!

**Comment by Vovanella95** [comment]
Hi @DenisAnkh , try to use overriden_models feature. Using it you can replace generated models by own models. If it will not help - reopen issue and provide details.

For now - closing issue
