### ISSUE TITLE
[BUG] fileName cannot be provided with List<int> partFile

### ISSUE THREAD

**Issue by mtsrdr** [epam-cross-platform-lab/swagger-dart-code-generator#605]
**Describe the bug**

For more information: https://github.com/lejard-h/chopper/issues/408

I have a .NET Core WebApi with an action to upload files:
``` dart
    [HttpPost("upload-file")]
    public IActionResult Upload(IFormFile file)
    {
        return Ok(new
        {
            fileName = file.FileName,
            contentType = file.ContentType,
        });
    }
```

This action expects a `IFormFile` and requires the FileName and ContentType of the file to work.

But the generator uses `List<int>?` parameter instead of `MultipartFile` so I can't send the `FileName` during the request.

How can I configure the generator to use `MultipartFile` instead of `List<int>`? 

**To Reproduce**
swagger.yaml
``` yaml
openapi: 3.0.1
info:
  title: SampleApi
  version: '1.0'
paths:
  /File/upload-file:
    post:
      tags:
        - File
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                style: form
      responses:
        '200':
          description: Success
components: { }
```

lib/generated_code/swagger_api.swagger.chopper.dart
``` dart
  @override
  Future<Response<dynamic>> _fileUploadFilePost({List<int>? file}) {
    final Uri $url = Uri.parse('/File/upload-file');
    final List<PartValue> $parts = <PartValue>[
      PartValueFile<List<int>?>(
        'file',
        file,
      )
    ];
    final Request $request = Request(
      'POST',
      $url,
      client.baseUrl,
      parts: $parts,
      multipart: true,
    );
    return client.send<dynamic, dynamic>($request);
  }
```

**Expected behavior**
I want the generated code to be like this:
``` dart
  @override
  Future<Response<dynamic>> _fileUploadMultipartPost(
      {required MultipartFile file}) {
    final Uri $url = Uri.parse('/File/upload-multipart');
    final List<PartValue> $parts = <PartValue>[
      PartValueFile<MultipartFile>(
        'file',
        file,
      )
    ];
    final Request $request = Request(
      'POST',
      $url,
      client.baseUrl,
      parts: $parts,
      multipart: true,
    );
    return client.send<dynamic, dynamic>($request);
  }
```

**Library version used:**
``` yaml
dependencies:
  chopper: ^6.1.1
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^2.10.4
```

**Comment by fryette** [comment]
@mtsrdr is it related to the https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/608 ?

**Comment by ko16a46** [comment]
I ran into this issue as well. 

Based on [lejard-h/chopper#160 (comment)](https://github.com/lejard-h/chopper/issues/160#issuecomment-1693253774), if the generated chopper client code uses `http.Multipartfile` instead of `List<int>`, it seems chopper can handle it, and the generated Dart code could allow us to include the filename and content type. 

Without these, our backend .Net Core web API was receiving `null` for the `IFormFile`. We couldn't even get the raw bytes.

In the meantime, I wrote an extension method that manually uses MultipartFile, to avoid overwriting the generated code. Something like this
```dart
// Represents a file with byte data
class FileReference {
  FileReference({
    required this.value,
    required this.contentType,
    required this.filename,
  });

  final List<int> value;
  final String contentType;
  final String filename;
}

extension MyApiExtensions on MyApi {
  Future<Response<dynamic>> apiV1Upload({
    FileReference? file,
    String? description,
  }) {
    final Uri $url = Uri.parse('/api/v1/upload');
    final List<PartValue> $parts = <PartValue>[
      PartValue<String?>(
        'description',
        description,
      ),
      PartValue<MultipartFile?>(
        'file',
        file != null
            ? MultipartFile.fromBytes(
                'file',
                file.value,
                filename: file.filename,
                contentType: MediaType.parse(file.contentType),
              )
            : null,
      ),
    ];
    final Request $request = Request(
      'POST',
      $url,
      client.baseUrl,
      parts: $parts,
      multipart: true,
    );
    return client.send<dynamic, dynamic>($request);
  }
}
```

Would be nice to have this fixed tho. It's a breaking change if all `List<int>` files were turned into `MultipartFile`, so perhaps a setting in a config would work.

**Comment by n0mad-d3v** [comment]
Hello, 
I ran into the same today, with the same config (.NET API + generation with this package). 
While reading the code, I found the line `this.multipartFileType = 'List<int>',` in `GeneratorOptions` class which does not seem to be documented yet (I'll do a PR for that to help others or avoid having the same issue later myself again 😜). 

Then, by creating a build.yml file as explained in the documentation with the following content: 

```
targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/swaggers'
          output_folder: 'lib/generated'
          multipart_file_type: 'MultipartFile' 

```

The generated client is correct and I'm able to assign a file 
```
var response = await _api.myMethodPost(
        [... others params ...]
        file: MultipartFile.fromBytes(
          "file",
          myFile.readAsBytesSync(),
          filename: myFile.filename,
        ),
      );
```

The file is correctly sent to the API, including the filename. 

I hope it helps! 🤞

Have a nice day!
