### ISSUE TITLE
[QUESTION] How I can create PartFile instead of Part in multipart request ?

### ISSUE THREAD

**Issue by ihorkozar** [epam-cross-platform-lab/swagger-dart-code-generator#608]
In my swagger doc I have this field: `"photo": {
                    "type": "file"
                  }`
In result I have:  `@Part('photo') List<int>? photo,`
Related to Chopper documentation I need to have something like  `@PartFile('photo') List<int>? photo,`
Can you give me some advice please ?

**Comment by fryette** [comment]
Thanks for your contribution, I will close this.
