### ISSUE TITLE
[BUG] Code formatting failed.

### ISSUE THREAD

**Issue by vadimlukutin** [epam-cross-platform-lab/swagger-dart-code-generator#613]
I have Open API json code. Validate on JSON on [app.swaggerhub.com](https://app.swaggerhub.com/apis/). 

But have error:

[WARNING] swagger_dart_code_generator on assets/swaggers/organisation_api_docs.json:
[WARNING] Code formatting failed.
          Please raise an issue on https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/issues/
          Reason: Could not format because the source could not be parsed:

line 9283, column 8 of .: Expected an identifier.
     ╷
9283 │         this.,
     │              ^
     ╵
line 9296, column 8 of .: Expected to find ';'.
     ╷
9296 │     final InventoryProductidwriteOff? ;
     │           ^^^^^^^^^^^^^^^^^^^^^^^^^^
     ╵
line 9296, column 34 of .: Operator declarations must be preceded by the keyword 'operator'.
     ╷
9296 │     final InventoryProductidwriteOff? ;
     │                                     ^
     ╵
line 9296, column 34 of .: The string '?' isn't a user-definable operator.
     ╷
9296 │     final InventoryProductidwriteOff? ;
     │                                     ^
     ╵
line 9296, column 34 of .: Methods must have an explicit list of parameters.
     ╷
9296 │     final InventoryProductidwriteOff? ;
     │                                     ^
     ╵
line 9458, column 8 of .: Expected an identifier.
     ╷
9458 │         this.,
     │              ^
     ╵
line 9471, column 8 of .: Expected to find ';'.
     ╷
9471 │     final InventoryidbulkProcessing? ;
     │           ^^^^^^^^^^^^^^^^^^^^^^^^^
     ╵
line 9471, column 33 of .: Operator declarations must be preceded by the keyword 'operator'.
     ╷
9471 │     final InventoryidbulkProcessing? ;
     │                                    ^
     ╵
line 9471, column 33 of .: The string '?' isn't a user-definable operator.
     ╷
9471 │     final InventoryidbulkProcessing? ;
     │                                    ^
     ╵
line 9471, column 33 of .: Methods must have an explicit list of parameters.
     ╷
9471 │     final InventoryidbulkProcessing? ;
     │                                    ^
     ╵
(5 more errors...)
[INFO] 4.4s elapsed, 0/2 actions completed.
[INFO] 5.9s elapsed, 2/3 actions completed.
[INFO] Running build completed, took 6.4s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 41ms

[SEVERE] freezed on lib/src/data/repositories/api/organisation_api_docs.swagger.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:balance3d/src/data/repositories/api/organisation_api_docs.swagger.dart (or an existing part) contains the following errors.
organisation_api_docs.swagger.dart:9283:8: Expected an identifier.
organisation_api_docs.swagger.dart:9296:8: Expected to find ';'.
organisation_api_docs.swagger.dart:9296:34: Operator declarations must be preceded by the keyword 'operator'.
And 12 more...

Try fixing the errors and re-running the build.

[SEVERE] json_serializable on lib/src/data/repositories/api/root_api_docs.swagger.dart (cached):

UnimplementedError: (InvalidTypeImpl) InvalidType
[SEVERE] json_serializable on lib/src/data/repositories/api/organisation_api_docs.swagger.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:balance3d/src/data/repositories/api/organisation_api_docs.swagger.dart (or an existing part) contains the following errors.
organisation_api_docs.swagger.dart:9283:8: Expected an identifier.
organisation_api_docs.swagger.dart:9296:8: Expected to find ';'.
organisation_api_docs.swagger.dart:9296:34: Operator declarations must be preceded by the keyword 'operator'.
And 12 more...

Try fixing the errors and re-running the build.

[SEVERE] chopper_generator on lib/src/data/repositories/api/organisation_api_docs.swagger.dart (cached):

This builder requires Dart inputs without syntax errors.
However, package:balance3d/src/data/repositories/api/organisation_api_docs.swagger.dart (or an existing part) contains the following errors.
organisation_api_docs.swagger.dart:9283:8: Expected an identifier.
organisation_api_docs.swagger.dart:9296:8: Expected to find ';'.
organisation_api_docs.swagger.dart:9296:34: Operator declarations must be preceded by the keyword 'operator'.
And 12 more...

Try fixing the errors and re-running the build.

[SEVERE] Failed after 6.5s

**Comment by vadimlukutin** [comment]
`"/inventory/{id}/bulk_processing": {
            "post": {
                "tags": [
                    "Inventories"
                ],
                "summary": "Массовое оприходование и списание продуктов инвентаризации",
                "operationId": "07db75d149ddfc448e2857193721894d",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "required": true,
                        "style": "simple",
                        "explode": false,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/id_bulk_processing_body"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/Inventory"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthenticated"
                    },
                    "403": {
                        "description": "Not permitted"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },`

**Comment by vadimlukutin** [comment]
After remove Error scheme from allOf.  Have build error. And missing generate `part 'root_api_docs.swagger.g.dart';`.

[INFO] Running build...
[INFO] 11.0s elapsed, 0/2 actions completed.
[INFO] 14.6s elapsed, 0/2 actions completed.
[INFO] 16.0s elapsed, 2/3 actions completed.
[SEVERE] json_serializable on lib/src/data/repositories/api/root_api_docs.swagger.dart:

UnimplementedError: (InvalidTypeImpl) InvalidType
[INFO] 17.8s elapsed, 3/4 actions completed.
[INFO] 18.8s elapsed, 5/6 actions completed.
[INFO] Running build completed, took 19.0s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 44ms

[SEVERE] Failed after 19.0s



```
            "Error": {
                "properties": {
                    "status": {
                        "type": "integer",
                        "example": "422"
                    },
                    "message": {
                        "type": "string"
                    },
                    "errors": {
                        "properties": {
                            "any_field_name": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        },
                        "type": "object"
                    }
                },
                "type": "object"
            },
```

**Comment by vadimlukutin** [comment]
Ok I check trouble. Error appear when '"allOf"' contain more one items.

**Comment by vadimlukutin** [comment]
Again I have test. And error appear when allOf have properties on items. If have some items only with '"$ref"' codegenerate is successfull. 

'"UserWithRoles": {
                "type": "object",
                "allOf": [
                    {
                        "$ref": "#/components/schemas/UserWithRole"
                    },
                    {
                        "$ref": "#/components/schemas/User"
                    }
                ]
            }'

**Comment by fryette** [comment]
@Vovanella95 could you please take a look?

**Comment by Vovanella95** [comment]
@vadimlukutin I will take a look

**Comment by vadimlukutin** [comment]
ok

**Comment by vadimlukutin** [comment]
@Vovanella95  I was send to email.

**Comment by vadimlukutin** [comment]
@Vovanella95
