### ISSUE TITLE
[FEATURE] suffix/prefix for generated models

### ISSUE THREAD

**Issue by mars3142** [epam-cross-platform-lab/swagger-dart-code-generator#626]
**Is your feature request related to a problem? Please describe.**
I consume an external swagger definition and the models don't have e.g. the `Dto` suffix. This could create conflicts for our codebase, if the swagger definition is changed in the future.

**Describe the solution you'd like**
A property like `model_suffix` or `model_prefix` would be helpful, because this way I could be sure, that internal classes wouldn't be named like the generated classes.

**Swagger specification link**
Can't share it, because it's confidential.

**Comment by Vovanella95** [comment]
Hi @mars3142 , we already have `modelPostfix` generation option for models. It's not documented, because works not very stable. Please use this one to generate unique models.
