### ISSUE TITLE
[BUG] type with additionalProperties not translated to Map<String, dynamic> in one case

### ISSUE THREAD

**Issue by countfloyd** [epam-cross-platform-lab/swagger-dart-code-generator#628]
I have automatically generated openapi code with the following type. It is included as a field in another type:

```
    Map_VerificationStandard:
      type: object
      description: The verification standards
      additionalProperties:
        $ref: '#/components/schemas/VerificationStandard'
```

After code generation, I get the following class:

```
@JsonSerializable(explicitToJson: true)
class MapVerificationStandard {
  MapVerificationStandard();

  factory MapVerificationStandard.fromJson(Map<String, dynamic> json) =>
      _$MapVerificationStandardFromJson(json);

  static const toJsonFactory = _$MapVerificationStandardToJson;
  Map<String, dynamic> toJson() => _$MapVerificationStandardToJson(this);

  static const fromJsonFactory = _$MapVerificationStandardFromJson;

  @override
  String toString() => jsonEncode(this);

  @override
  int get hashCode => runtimeType.hashCode;
}
```

If I take the type description and paste it in the parent type, it works correctly, but as the openapi YAML is automatically generated as well, it is difficult to change.

I would expect the generator to generate code with MapVerificationStandard containing a field of type Map<String, dynamic>

Using version 2.11.8

**Comment by Vovanella95** [comment]
Hi @countfloyd , we are not supporting `additionalProperties`. When model has additionalproperties, it means it can be any property with any name and it's impossible to define it before response is handled. For such cases we generate Map<String, dynamic> return type. Just not pay attention to such classes, they will not be used and will be removed by tree-shaking
