### ISSUE TITLE
Additional optional params

### ISSUE THREAD

**Issue by pandora-house** [epam-cross-platform-lab/swagger-dart-code-generator#634]
Hi, your package is really amazing! Can you add a few optional parameters into "Options"?

- optional generated toString() method
- const model constructor

**Comment by Vovanella95** [comment]
Hi @pandora-house , sorry I forgot about your issue. It's already implemented!
Use `override_to_string` to disable toString override
const constructors are already generation

**Comment by pandora-house** [comment]
Спасибо братан
