### ISSUE TITLE
generating dynamic instead of DateTime Type for "date-time"

### ISSUE THREAD

**Issue by anandsubbu007** [epam-cross-platform-lab/swagger-dart-code-generator#637]
**Describe the bug**
after i upgraded to latest version Datetime datatype is not generatind

**To Reproduce**
					"lastUpdateOn": {
						"type": "Date",
						"description": "LastUpdate on On",
						"example": "{Name}",
						"readOnly": true,
						"nullable": false,
						"format": "date-time"
					},

**Expected behavior**
DateTime but it is generating as dynamic

**Swagger specification link**

**Library version used:**
swagger_dart_code_generator: ^2.11.10

**Additional context**
also please add the document for Type & format to datatype in dart. it will be helpful.

**Comment by dJani97** [comment]
This may be related: when switching my project from `^2.8.8` to `^2.11.10`, it started generating `Future<chopper.Response<List<dynamic>>>` instead of `Future<chopper.Response<List<SomeDTO>>>`.

I had to go back to these versions for it to generate properly:

```
chopper: ^6.1.4
...
swagger_dart_code_generator: 2.10.4
chopper_generator: ^6.0.3
```
