### ISSUE TITLE
[QUESTION] g.dart file path

### ISSUE THREAD

**Issue by wolru** [epam-cross-platform-lab/swagger-dart-code-generator#640]
I set the g.dart file to be generated by dividing it into the generated folder. Inside the generated 'swagger.models.swagger.dart' file, part 'swagger.models.swagger.g.dart'; , can this part be customized?

source_gen|combining_builder:
         options:
           build_extensions:
             "^lib/{{dir}}/{{file}}.dart": "lib/{{dir}}/generated/{{file}}.g.dart"

**Comment by Vovanella95** [comment]
Hi @wolru, for now it's not possible. I can not imagine situation when this feature is required. Feel free to fork our generator and customize it.
