### ISSUE TITLE
[QUESTION] How i can turn useBrackets to true without changing generated files by fands

### ISSUE THREAD

**Issue by Nyt1k** [epam-cross-platform-lab/swagger-dart-code-generator#642]
I try to create filters in request like this:
```
final respone = await locationRepository.getLocations(
        paginationPage: paginationPage + 1,
        paginationPageSize: 2,
        populate: 'images',
        filters: {
          'city': {
            r'$eqi': userLocation,
          },
        },
      );
```
but request look like this:
`/api/locations?pagination%5Bpage%5D=0&pagination%5BpageSize%5D=2&populate=images&filters.city.%5B%24eqi%5D=M%C3%A1laga `

It looks like I need to make `useBrackets` to `true` in chopper `Request` model that used in auto generated methods in  full_documentation.swagger.chopper.dart file.

How can i do it or if i can`t, how i can make filters in correct format for request?

**Comment by TrachukV** [comment]
I have exactly the same problem. I don't understand how to fix it

**Comment by Vovanella95** [comment]
Hi @Nyt1k, @TrachukV, we just generate models and chopper requests definitions. Please, provide part of generated code and expected generated code. Then we will make a fix.

For now I'm not fully understand the problem

**Comment by Nyt1k** [comment]
Thank you for answer @Vovanella95! 
Chopper package use class `Request`, this class have field  `useBrackets`.
As I understood this parameter needed when this class will build Uri in format user selected. 
If its `false` format of query will look like this:
`pagination%5Bpage%5D=0&pagination%5BpageSize%5D=2&populate=images&filters.city.%5B%24eqi%5D=Monaco`

If its `true` it looks like this:
`pagination%5Bpage%5D=0&pagination%5BpageSize%5D=2&populate=images&filters%5Bcity%5D%5B%24eqi%5D=Monaco`

The difference between queries in filters format and in generated code from swagger as default `useBrackets` not changing so it set to false. But I need second format of query. 

I resolve this by creating my custom request with parameters i need and I change it in full_documentation.swagger.dart file like this `typedef Request = CustomRequest;`.
I think its not correct solution so maybe you can say how I can resolve this problem correctly.

**Comment by Vovanella95** [comment]
Cool, @Nyt1k , if we can made some changes in our generator, helps yo easier use this feature, let us know!
