### ISSUE TITLE
[BUG] `explode: false` not respected

### ISSUE THREAD

**Issue by dreautall** [epam-cross-platform-lab/swagger-dart-code-generator#644]
**Describe the bug**
`explode: false` should produce a query like `&multiple=option1,option2`. Instead, `&multiple=option1&multiple=option2` is generated. The latter should only be produced with `explode: true`

**To Reproduce**
```
        - in: query
          name: multiple
          description: test field
          required: false
          explode: false
          schema:
            type: array
            items:
              $ref: '#/components/schemas/enum'

(snip)

    enum:
      type: string
      enum:
        - option 1
        - option 2
```

**Swagger specification link**
Query Parameters at https://swagger.io/docs/specification/serialization/

**Library version used:**
2.11.10

**Comment by Vovanella95** [comment]
Hi @dreautall , I've implemented primary version of exploded parameters. Let us know in case of any issues.

P.S. Chopper not supports exploded parameters, so I've implemented some kind of workaround

**Comment by Vovanella95** [comment]
Hi @dreautall , yes, I removed support of exploded parameters. Chopper generator not support it. And we just wrapper over Chopper Generator. All API's should support both of parameters: exploded and no.

We're not going to support it, sorry
