### ISSUE TITLE
Where are the branches for releases 2.11.7, 2.11.8 and 2.11.10?

### ISSUE THREAD

**Issue by Adam-Langley** [epam-cross-platform-lab/swagger-dart-code-generator#647]
**Please describe a problem.**
While attempting to determine if a bug still exists in the product, I need to fork and work on specific recent releases of the code.
The last 3 versions are mentioned in the change-log, but do not have branches (or labels).
Particularly, 2.11.10 is the version currently on pub.dev, but has no branch. The 'master' branch has a pubspec version of 2.11.8 - it seems some things have gotten out of sync.

*from the changelog*
```
# 2.11.10

* Bump `package:http` to `^1.0.0`
* Bump minimum dart version to `^3.0.0`
* Fixed #625 generation of query enum parameters

# 2.11.8

* Fixed generation of fields of some models

# 2.11.7

* Updated SDK version
```

**Describe the solution you'd like**
Congruency between branches (or labels at least), and releases (please :) ).

**Comment by Vovanella95** [comment]
Hi @Adam-Langley , sorry we don't have such branches. You can find apropriate commits using changes in changelog file :)

**Comment by Vovanella95** [comment]
@Adam-Langley  from next version, we will use tags
