### ISSUE TITLE
[BUG] In 2.11.12 fields that are not required appear as required in generated model

### ISSUE THREAD

**Issue by mrares** [epam-cross-platform-lab/swagger-dart-code-generator#661]
**Describe the bug**
Starting in 2.11.12 (the behaviour is not present in 2.11.11, which I reverted to), fields in the model not present in the required list are being generated as required in the model. I suspect this has something to do with #650 

My json doesn't specify nullable on the fields, it just omits the non-required ones from the required list. If I ALSO set nullable: true on the fields not in the required list, then I get the proper behaviour again. Sadly, Strapi doesn't generate the nullable property on the fields.

**To Reproduce**
Please attach swagger and code snippet of generated value

**Expected behavior**
If a list of required properties is provided, then any property not explicitly marked as nullable: false should be assumed to be nullable: true.

**Swagger specification link**
Link to swagger/OpenApi documentation

**Library version used:**
2.11.12

**Additional context**
I am generating swagger.json from Strapi (famous for it's very poor abilities to generate the api docs)

**Comment by Vovanella95** [comment]
Hi @mrares , yes, it depends from nullableFields generator option. I will add it to README.

I make it `true` by default. So bug should be fixed
