### ISSUE TITLE
[BUG] Client generated with 2.11.12 has generic body type Object

### ISSUE THREAD

**Issue by jpraus** [epam-cross-platform-lab/swagger-dart-code-generator#663]
**Describe the bug**
After an upgrade to 2.11.12, the generated client code has a body parameter of type `Object`, whereas the code generated with 2.11.10 has a body parameter of the correct type. Tested with examples in this library as well (pet store).

**To Reproduce**
Run `flutter pub run build_runner build` in the `example` folder and see the `pet_service_json.swagger.chopper.dart` file. Actual result is:
<img width="351" alt="Snímek obrazovky 2023-10-17 v 19 10 26" src="https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/assets/2779120/d2b3ef91-82a6-44cd-9690-90d070b37b7c">

**Expected behavior**
<img width="343" alt="Snímek obrazovky 2023-10-17 v 19 15 25" src="https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/assets/2779120/99bb2b8a-1448-43e5-8172-9c0f3c807323">

**Swagger specification link**
[Link to swagger/OpenApi documentation](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/blob/master/example/input_folder/pet_service_json.json)

**Library version used:**
2.11.12

**Comment by Vovanella95** [comment]
Hi @jpraus , thanks for raising issue. Fixed.

**Comment by jpraus** [comment]
Awesome thank you! When is the next release scheduled?
