### ISSUE TITLE
[BUG] Lack of generatedMapping.putIfAbsent

### ISSUE THREAD

**Issue by zltnDC** [epam-cross-platform-lab/swagger-dart-code-generator#665]
**Describe the bug**
Generated code does not contain "generatedMapping.putIfAbsent" and leads to an exception: Could not find factory for type LoginEmailPost$Response.

**To Reproduce**
swagger:
```
openapi: 3.0.3

paths:
  /login/email:
    post:
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                    type: string
                password:
                    type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
```

**Expected behavior**
Generated code should include generatedMapping.putIfAbsent for the response type

**Library version used:**
swagger_dart_code_generator: 2.11.12

**Comment by Vovanella95** [comment]
Hi @zltnDC , could you prepare example of swagger file?

**Comment by zltnDC** [comment]
Isn't the content of the yaml file enough?

**Comment by Vovanella95** [comment]
@zltnDC  It's enough)) Will take a look into it!
