### ISSUE TITLE
[BUG] type 'List<dynamic>' is not a subtype of type 'String?' in type cast

### ISSUE THREAD

**Issue by RoarGronmo** [epam-cross-platform-lab/swagger-dart-code-generator#672]
**Describe the bug**
This `swagger (2.0)` file won't be parsed and results in following error message:
```
[SEVERE] swagger_dart_code_generator on swaggers/m_office_guardsystems.swagger (cached):

type 'List<dynamic>' is not a subtype of type 'String?' in type cast
[SEVERE] Failed after 357ms
```

No file seems to generated, but the `client_index.dart` file seems to to be updated with the expexted dart file name that should be generated: (`export 'm_office_guardsystems.swagger.dart' show MOfficeGuardsystems; `)

(Consideration for you, please pinpoint line# or sequence where the error occures, so it easier to spot the flaw !)

```
export 'm_office_5009_api.swagger.dart' show MOffice5009Api;
export 'm_office_5018_api.swagger.dart' show MOffice5018Api;
export 'm_office_bing_locations_query_api.swagger.dart'
    show MOfficeBingLocationsQueryApi;
export 'm_office_guardsystems.swagger.dart' show MOfficeGuardsystems;
```

**To Reproduce**
Attaching swagger file (in .txt) since it is approx 6820 lines. 
[m_office_guardsystems.txt](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/13305710/m_office_guardsystems.txt)

You can also download it from here (not structured): https://api.guardsystems.com/v1.9/swagger 

Nothing was produced for this swagger.

**Expected behavior**
Just want the generation to go through.

**Swagger specification link**
Link to swagger/OpenApi documentation

**Library version used:**
`swagger_dart_code_generator: ^2.11.8` 
I expect the latest to be picked: `2.12.1` at least it is what the `pubspec.lock` file shows.

**Additional context**
Since this is a swagger 2.0 definition (not 3.0.1), might something go under the radar ?

**Comment by Vovanella95** [comment]
Hi @RoarGronmo , thanks for raising issue! This issue is not generator issue. Provided swagger file is not valid. If you will put it to [Swagger Editor](https://editor.swagger.io/), you will see error related to `description`. This property should be `string` value.

Closing this issue. Let us know in case of another issues

![Снимок экрана 2023-11-10 в 14 11 10](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/assets/11267533/d8d465f5-2c67-4ae4-96bf-fb38539e5cc4)

**Comment by RoarGronmo** [comment]
Thank you for helping out ! Love that !!

I will inform the creator of the swagger file (link mentioned above), so that they can correct it with a new release !!

Thanx for "Swagger Editor" link, which might help us in future issues.

**Comment by RoarGronmo** [comment]
BTW:
I actually converted this swagger 2.0 to 3.0.1 using the new swagger editor: https://editor-next.swagger.io/ and now the dart code was generated without any complaints. The new swagger editor didn't complain either... so there may be some changes there too, or the "fail-check" in the new swagger editor didn't find them.

[m_office_guardsystems.swagger.txt](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/13319388/m_office_guardsystems.swagger.txt)


Thank you again for your support !!

**Comment by Vovanella95** [comment]
@RoarGronmo let's fix issues when we face them :D
