### ISSUE TITLE
[BUG] Build fails on Flutter 3.16 for iOS or Windows

### ISSUE THREAD

**Issue by juliansteenbakker** [epam-cross-platform-lab/swagger-dart-code-generator#681]
**Describe the bug**
The app can't be build because of the following error: `Error (Xcode): Target native_assets failed: Exception: Package(s) x require the native assets feature to be enabled. Enable using flutter config --enable-native-assets.`

**To Reproduce**
Upgrade to Flutter 3.16, and try to build the app for iOS or Windows.

**Library version used:**
Latest version

**Additional context**
This could be a bug in Flutter, since this seems due to a feature added in Flutter 3.16. See [this Flutter issue](https://github.com/flutter/flutter/issues/138727#issuecomment-1819759190) for more information.

**Comment by Vovanella95** [comment]
Hi @juliansteenbakker , did you tried to execute `flutter config --enable-native-assets`?

**Comment by juliansteenbakker** [comment]
It has been confirmed that this issue is caused by some new feature of flutter, which is also using build.dart, colliding with the build.dart from this package. The --enable-native-assets is only available on master, and not on stable release.

See https://github.com/flutter/flutter/issues/138727#issuecomment-1820606396

The solution to this fix as proposed is to make the build.dart file name configurable, so it does not collide. This is also proposed for the other colliding feature of Flutter. See https://github.com/dart-lang/sdk/issues/54111#issue-2003911503

**Comment by Vovanella95** [comment]
@juliansteenbakker  do you have such problem only with this package?

**Comment by juliansteenbakker** [comment]
This is the only package that requires a build.dart file to be in the root of my project, which causes this issue.

**Comment by Vovanella95** [comment]
@juliansteenbakker  you can also use build.yaml file on freezed or json_serializable packages. Could you please check it?
For example for freezed you can do next:

```yaml
targets:
  $default:
    builders:
      freezed:
        options:
          union_key: type
          union_value_case: pascal
```

I don't have such problem on my PC, so can not fix it. Possible it's not our package issue

**Comment by Vovanella95** [comment]
@juliansteenbakker, the same, 3.16+ version. upgraded today. No errors from my side :(

**Comment by Vovanella95** [comment]
So, issue should be raised to Flutter maybe. It's not an issue of Swagger Generator. I'm closing the issue.

**Comment by juliansteenbakker** [comment]
It happend to me after a `flutter clean` and `flutter pub get`

**Comment by juliansteenbakker** [comment]
Also, it only happens on iOS or Windows, not on building Android.

**Comment by Vovanella95** [comment]
It's strange that you have error during app build, and not during code generation... It's very interesting

**Comment by dcharkes** [comment]
> It's strange that you have error during app build, and not during code generation... It's very interesting. Because package works only when you generating code

This is because a toplevel `build.dart` is now interpreted as a script which has to be run during Flutter app compilation to compile C code.

We'd like to reserve the toplevel `build.dart` for that use case:

* https://github.com/dart-lang/sdk/issues/54334

Would it be possible to use `tool/build.dart` for the swagger code generator instead, according to the https://dart.dev/tools/pub/package-layout ?
