### ISSUE TITLE
[BUG] Different nullability in the generated code, depending on whether the type of the property is specified with '$ref'.

### ISSUE THREAD

**Issue by temoki** [epam-cross-platform-lab/swagger-dart-code-generator#688]
### Describe the bug
Even properties with the same attributes may have different nullability in the generated code, depending on whether the type of the property is specified with '$ref'.

### To Reproduce & Expected behavior
**example.json**
```json
{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Example",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://example.com/"
  } ],
  "paths" : {
    "/api" : {
      "get" : {
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ExampleObject"
                }
              }
            },
            "description" : "Example"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "ExampleObject" : {
        "properties" : {
          "prop_a" : {
            "type" : "string"
          },
          "prop_b" : {
            "$ref" : "#/components/schemas/example_type"
          }
        },
        "required" : [ "prop_a", "prop_b" ],
        "type" : "object"
      },
      "example_type" : {
        "type" : "string"
      }
    }
  }
}
```

The object named `ExampleObject` defines two properties, `prop_a` and `prop_b`. Both of these properties share the following attributes:

* type: string
* required: true
* nullable: not specified (implicitly treated as non-nullable)

The difference lies solely in whether the attributes are specified using `$ref`. However, this results in distinct outcomes in the generated code: `propA` is non-nullable, and `propB` is nullable. The expected outcome is for both `propA` and `propB` to be non-nullable.

**example.models.swagger.dart** (Generated dart code) 
```dart
@JsonSerializable(explicitToJson: true)
class ExampleObject {
  const ExampleObject({
    required this.propA,
    required this.propB,
  });

  ...

  @JsonKey(name: 'prop_a')
  final String propA;
  @JsonKey(name: 'prop_b')
  final String? propB;
```

**build.yml** (Build options)
```yml
targets:
  $default:
    sources:
      - openapi/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'openapi/gen'
          output_folder: 'lib/gen/api'
          separate_models: true
```

### Swagger specification link
-

### Library version used
2.12.2, 2.13.1

The nullability in the generated code was very unstable across several updates after 2.11.11 (2.11.12, 2.11.12, 2.11.13, 2.12.1). It has been adjusted to be closer to the results of 2.11.11 in version 2.12.2. However, the issue described in this ticket has not been resolved yet.

### Additional context

I have prepared an input file as follows and investigated the changes in nullability in the code generated with recent versions, so I will also report the results.

```json
{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Example",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://example.com/"
  } ],
  "paths" : {
    "/api" : {
      "get" : {
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ExampleObject"
                }
              }
            },
            "description" : "Example"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "ExampleObject" : {
        "properties" : {
          "prop" : {
            "type" : "string"
          },
          "prop_nullable" : {
            "nullable" : true,
            "type" : "string"
          },
          "prop_required" : {
            "type" : "string"
          },
          "prop_required_nullable" : {
            "nullable" : true,
            "type" : "string"
          },
          "prop_ref" : {
            "$ref" : "#/components/schemas/example_type"
          },
          "prop_ref_nullable" : {
            "$ref" : "#/components/schemas/example_type_nullable"
          },
          "prop_ref_required" : {
            "$ref" : "#/components/schemas/example_type"
          },
          "prop_ref_required_nullable" : {
            "$ref" : "#/components/schemas/example_type_nullable"
          }
        },
        "required" : [ "prop_ref_required", "prop_ref_required_nullable", "prop_required", "prop_required_nullable" ],
        "type" : "object"
      },
      "example_type" : {
        "type" : "string"
      },
      "example_type_nullable" : {
        "nullable" : true,
        "type" : "string"
      }
    }
  }
}
```

### Property definition of the ExampleObject in example.json

| property | type | required | nullable | $ref _※_ |
| --- | --- | --- | --- | --- |
| prop | string | - | - | --- |
| prop_nullable | string | - | yes | --- |
| prprop_required | string | yes | - | --- |
| prop_required_nullable | string | yes | yes | --- |
| prop_ref | string | - | - | yes |
| prop_ref_nullable | string | - | yes | yes |
| prop_ref_required | string | yes | - | yes |
| prop_ref_required_nullable | string | yes | yes | yes |

_※_ `$ref` is used to reference the type of a property, as in the following example
```yml
        prop_ref:
          $ref: '#/components/schemas/example_type'
```

### Code generation results for example.json by version

- 🔴 : Fields that are required in the constructor
- 🔵 : Nullable fields

| field | 2.11.11 | 2.11.12 | 2.11.12 _※_ | 2.11.13 | 2.12.1 | 2.12.2 |
| --- | :-: | :-: | :-: | :-: | :-: | :-: |
| prop | 🔵 | 🔴 | - | 🔵 | 🔴 | 🔵 |
| propNullable | 🔵 | 🔵 | 🔵 | 🔵 | 🔵 | 🔵 |
| propRequired | 🔴 | 🔴 | - | 🔴 | 🔴 | 🔴 |
| propRequiredNullable | 🔴🔵 | 🔵 | 🔵 | 🔴 | 🔴 | 🔴🔵 |
| propRef | 🔵 | 🔴 | - | 🔵 | 🔴 | 🔵 |
| propRefNullable | 🔵 | 🔴🔵 | 🔵 | 🔵 | 🔴🔵 | 🔵 |
| propRefRequired | 🔴 | 🔴 | - | 🔴🔵 | 🔴 | 🔴🔵 |
| propRefRequiredNullable | 🔴🔵 | 🔴🔵 | 🔵 | 🔴🔵 | 🔴🔵 | 🔴🔵 |

_※_ : When the generation option `nullable_fields: true` is used

Through version updates, the code generated by 2.12.2 (as well as the latest 2.13.1) has come closer to that of 2.11.11, but only propRefRequired still differs.

**Comment by temoki** [comment]
I have prepared an input file as follows and investigated the changes in nullability in the code generated with recent versions, so I will also report the results.

```json
{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Example",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://example.com/"
  } ],
  "paths" : {
    "/api" : {
      "get" : {
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ExampleObject"
                }
              }
            },
            "description" : "Example"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "ExampleObject" : {
        "properties" : {
          "prop" : {
            "type" : "string"
          },
          "prop_nullable" : {
            "nullable" : true,
            "type" : "string"
          },
          "prop_required" : {
            "type" : "string"
          },
          "prop_required_nullable" : {
            "nullable" : true,
            "type" : "string"
          },
          "prop_ref" : {
            "$ref" : "#/components/schemas/example_type"
          },
          "prop_ref_nullable" : {
            "$ref" : "#/components/schemas/example_type_nullable"
          },
          "prop_ref_required" : {
            "$ref" : "#/components/schemas/example_type"
          },
          "prop_ref_required_nullable" : {
            "$ref" : "#/components/schemas/example_type_nullable"
          }
        },
        "required" : [ "prop_ref_required", "prop_ref_required_nullable", "prop_required", "prop_required_nullable" ],
        "type" : "object"
      },
      "example_type" : {
        "type" : "string"
      },
      "example_type_nullable" : {
        "nullable" : true,
        "type" : "string"
      }
    }
  }
}
```

### Property definition of the ExampleObject in example.yml

| property | type | required | nullable | $ref _※_ |
| --- | --- | --- | --- | --- |
| prop | string | - | - | --- |
| prop_nullable | string | - | yes | --- |
| prprop_required | string | yes | - | --- |
| prop_required_nullable | string | yes | yes | --- |
| prop_ref | string | - | - | yes |
| prop_ref_nullable | string | - | yes | yes |
| prop_ref_required | string | yes | - | yes |
| prop_ref_required_nullable | string | yes | yes | yes |

_※_ `$ref` is used to reference the type of a property, as in the following example
```yml
        prop_ref:
          $ref: '#/components/schemas/example_type'
```

### Code generation results for example.yml by version

- 🔴 : Fields that are required in the constructor
- 🔵 : Nullable fields

| field | 2.11.11 | 2.11.12 | 2.11.12 _※_ | 2.11.13 | 2.12.1 | 2.12.2 |
| --- | :-: | :-: | :-: | :-: | :-: | :-: |
| prop | 🔵 | 🔴 | - | 🔵 | 🔴 | 🔵 |
| propNullable | 🔵 | 🔵 | 🔵 | 🔵 | 🔵 | 🔵 |
| propRequired | 🔴 | 🔴 | - | 🔴 | 🔴 | 🔴 |
| propRequiredNullable | 🔴🔵 | 🔵 | 🔵 | 🔴 | 🔴 | 🔴🔵 |
| propRef | 🔵 | 🔴 | - | 🔵 | 🔴 | 🔵 |
| propRefNullable | 🔵 | 🔴🔵 | 🔵 | 🔵 | 🔴🔵 | 🔵 |
| propRefRequired | 🔴 | 🔴 | - | 🔴🔵 | 🔴 | 🔴🔵 |
| propRefRequiredNullable | 🔴🔵 | 🔴🔵 | 🔵 | 🔴🔵 | 🔴🔵 | 🔴🔵 |

_※_ : When the generation option `nullable_fields: true` is used

**Comment by Vovanella95** [comment]
Hi @temoki , according logic, both properties should be not nullable. Fixed

**Comment by temoki** [comment]
@Vovanella95 Thanks⭐️

**Comment by temoki** [comment]
@Vovanella95 
Which version will this fix be included in?

**Comment by Vovanella95** [comment]
Hi @temoki , today :)
