### ISSUE TITLE
[FEATURE] Support for deprecated annotations

### ISSUE THREAD

**Issue by jointhejourney** [epam-cross-platform-lab/swagger-dart-code-generator#699]
Hi, it would be nice if we could parse any deprecated fields from our OpenAPI schema and add the deprecated class annotation in Dart:

https://api.flutter.dev/flutter/dart-core/Deprecated-class.html

It'd make it easier to spot deprecated changes through the IDE.

**Comment by Vovanella95** [comment]
Hi @jointhejourney , could you provide some examples of expected generated code?

**Comment by jointhejourney** [comment]
Hey @Vovanella95 apologies for missing your comment, and I'm glad you were able to implement. Thank you for the awesome package!
