### ISSUE TITLE
[QUESTION] Do not generate different Models for same object in .json file

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [epam-cross-platform-lab/swagger-dart-code-generator#706]
Is it possible to generate just one model and reuse it?

E.g.: In my swagger.json file there is an Address object which is used in different requests.

When generating the dart files, e.g.: Accommodation$Address, Event$Address and so on ...

**Comment by Vovanella95** [comment]
Hi @mariomurrent-softwaresolutions ! Thanks for raising issue. Unfortunately, it's very not trivial task and it will be not easy to define same models in different classes. I am the only one person who supports this package.

I can recommend to split **API and Domain models**. You can create `EventAddress` Domain model and map `Accommodation$Address`,` Event$Address` etc to `EventAddress` and use only `EventAddress` across the app.

So you will have API level with many models -> Repository level that map same models to common single model -> Use this model across the app

Or feel free to contribute :)

**Comment by mariomurrent-softwaresolutions** [comment]
Well yeah that's another idea. 
I solved it now with Flutter to just use the fromJson method to convert between the model. Should also help. I'll let you know.

But I definitely understand, that this is not a trivial thing.

Anyway, very nice work. Keep it up.
