### ISSUE TITLE
[QUESTION] Build fails if a model has "override" as property. Is there a way around this?

### ISSUE THREAD

**Issue by daniel-deboeverie-lemon** [epam-cross-platform-lab/swagger-dart-code-generator#713]
Whilst it is very logical that it does, if one of your models within the swagger has override as property, you get an error when it tries to compile the json annotations.

An example of this would be 
"TestService": {
                "type": "object",
                "properties": {
                    "override": {
                        "type": "string"
                    },
           }

Does the service currently have a way around this?

**Comment by Vovanella95** [comment]
Hi @daniel-deboeverie-lemon , looks like we should add override to this file: [exception_words.dart](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/blob/master/lib/src/exception_words.dart)

I will prepare fix asap
