### ISSUE TITLE
[QUESTION] Running build_runner in this repository?

### ISSUE THREAD

**Issue by shilangyu** [epam-cross-platform-lab/swagger-dart-code-generator#714]
Running build_runner in this repo yields many errors. What is the recommended flow? I have the following questions:

- How to run build_runner in the repo? It crashes due to the `build.yaml` setup.
- Why are generated files in `.g2.dart` files rather than `.g.dart`? json_serializable refuses the generate the former.
- `GeneratorOptions` has duplicated default values (one in the constructor and second in the `JsonKey` annotation). This makes json_serializable complain a lot, would you be open to me changing that?

It all started with me wanting to contribute a fix, but getting stuck at the dev flow of this repo. Answers to the above would be appreciated. Also the example folder is quite outdated, I would like to contribute an upgrade there too.

**Comment by Vovanella95** [comment]
- Hi @shilangyu , If you need to run `build_runner` in this repo - comment all contents in `build.yaml` file in root of project.
- Feel free to replace `.g2 `files to `.g` files. It has been done a long time ago, we copied approach from `chopper` package
- Feel free to make any changes that will not broke generation :) And thanks for contribution!

I'm closing this issue. I hope I answered to all your questions. Feel free to reopen it in case of any other questions!

**Comment by shilangyu** [comment]
Thanks. I will try to also fix the first point to not have to comment out build.yaml. This might be deferring future contributors if the dev flow isn't standard.
