### ISSUE TITLE
[QUESTION] Shareable schemas/components from different file

### ISSUE THREAD

**Issue by d3xt3r2909** [epam-cross-platform-lab/swagger-dart-code-generator#715]
**Please describe a problem.**
Hi thanks for package. My question is: 

Is it possible to have 3 `.json` files (A.json,B.json,C.json) where I am able to use `schemas` from A.json inside B and C. 

**Describe the solution you'd like**
Sharing schemas between files.

What I have tried: 

- Inside B.json I set something like ""$ref": "A.yaml#/components/schemas/SharedShema"
- And this will pass generation but the issue is that `SharedShema` will not be placed inside `.swagger.dart` which fails on runtime

**Comment by fryette** [comment]
At the moment it's not supported. 
You have to combine 3 into 1 using for example [swagger codegen](https://github.com/swagger-api/swagger-codegen)
