### ISSUE TITLE
[BUG] The argument type 'Iterable<dynamic>' can't be assigned to the parameter type 'List<Interceptor>'.

### ISSUE THREAD

**Issue by kevinvenclovas** [epam-cross-platform-lab/swagger-dart-code-generator#779]
**Describe the bug**

![image](https://github.com/user-attachments/assets/0553dfc9-cd58-47e2-a62b-ef20a6197c78)

**To Reproduce**
Please attach swagger and code snippet of generated value

**Expected behavior**

**Swagger specification link**
`
{
  "openapi": "3.0.1",
  "info": {
    "title": "VendingScout",
    "version": "1.0"
  },
  "paths": {
    "/App/structure": {
      "get": {
        "tags": [
          "App"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/StructureReponse"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StructureReponse"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/StructureReponse"
                }
              }
            }
          },
          "400": {
            "description": "BadRequest",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiBadRequestResponse"
                }
              }
            }
          },
          "500": {
            "description": "InternalServerError",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiExceptionResponse"
                }
              }
            }
          },
          "404": {
            "description": "NotFound",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiNotFoundResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ApiBadRequestResponse": {
        "required": [
          "errors"
        ],
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorResponse"
          }
        ],
        "properties": {
          "errors": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ApiBadRequestResponseError"
            }
          }
        },
        "additionalProperties": false
      },
      "ApiBadRequestResponseError": {
        "required": [
          "message"
        ],
        "type": "object",
        "properties": {
          "propertyName": {
            "type": "string",
            "nullable": true
          },
          "message": {
            "minLength": 1,
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "ApiExceptionResponse": {
        "required": [
          "message"
        ],
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorResponse"
          }
        ],
        "properties": {
          "message": {
            "minLength": 1,
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "ApiNotFoundResponse": {
        "required": [
          "message"
        ],
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/ErrorResponse"
          }
        ],
        "properties": {
          "message": {
            "minLength": 1,
            "type": "string"
          }
        },
        "additionalProperties": false
      },
      "AppSettingKey": {
        "enum": [
          "GEOJSON_VERSION",
          "GEOJSON_URL",
          "MAP_STYLE_URL",
          "CLUSTER_ICON",
          "LANGUAGES"
        ],
        "type": "string"
      },
      "AppSettingResponse": {
        "required": [
          "key",
          "value"
        ],
        "type": "object",
        "properties": {
          "key": {
            "$ref": "#/components/schemas/AppSettingKey"
          },
          "value": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "ErrorResponse": {
        "type": "object",
        "additionalProperties": false
      },
      "StructureReponse": {
        "type": "object",
        "properties": {
          "vendingGroups": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/VendingGroupResponse"
            },
            "nullable": true
          },
          "vendingTags": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/VendingTagReponse"
            },
            "nullable": true
          },
          "appSettings": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AppSettingResponse"
            },
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "VendingGroupResponse": {
        "required": [
          "icon",
          "key"
        ],
        "type": "object",
        "properties": {
          "key": {
            "type": "string",
            "nullable": true
          },
          "icon": {
            "type": "string",
            "nullable": true
          },
          "vendingMachines": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/VendingMachineResponse"
            },
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "VendingMachineResponse": {
        "required": [
          "icon",
          "key"
        ],
        "type": "object",
        "properties": {
          "key": {
            "type": "string",
            "nullable": true
          },
          "icon": {
            "type": "string",
            "nullable": true
          },
          "products": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/VendingProductResponse"
            },
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "VendingProductResponse": {
        "required": [
          "icon",
          "key"
        ],
        "type": "object",
        "properties": {
          "key": {
            "type": "string",
            "nullable": true
          },
          "icon": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "VendingTagReponse": {
        "required": [
          "icon",
          "key"
        ],
        "type": "object",
        "properties": {
          "key": {
            "type": "string",
            "nullable": true
          },
          "icon": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}`

**Library version used:**
![image](https://github.com/user-attachments/assets/143bfd32-1545-4d80-a2e6-8f0d8ce4d6f7)

**Additional context**

**Comment by kevinvenclovas** [comment]
![image](https://github.com/user-attachments/assets/b13c72fa-a3e2-4cfc-99d8-d4b3b61a5b36)
Easy fix, updated all libraries

**Comment by Hu-Wentao** [comment]
or use `swagger_dart_code_generator: ^2.15.2` and `chopper: ^7.4.0`

<img width="384" alt="Image" src="https://github.com/user-attachments/assets/6be06894-5a70-49a0-8b90-970aa33c48f7" />
