### ISSUE TITLE
Set ChopperClient interceptors

### ISSUE THREAD

**Issue by FischerDaniel** [epam-cross-platform-lab/swagger-dart-code-generator#93]
I want to set a HeaderInterceptor like this one on the ChopperClient: 

```
import 'dart:async';
import 'package:chopper/chopper.dart';


class HeaderInterceptor implements RequestInterceptor {

  static const String AUTH_HEADER = "Authorization";

  static const String BEARER = "Bearer ";

  HeaderInterceptor(this.accessToken);

  String accessToken;

  @override
  FutureOr<Request> onRequest(Request request) async {
    // 5
    Request newRequest =
        request.copyWith(headers: {AUTH_HEADER: BEARER + accessToken});
    return newRequest;
  }
}
```

Is it possible to set interceptors after the client is generated or can I set which interceptors the client should be generated with? 

In order to access my api right now I change the abstact class of the client after generation like below so I can pass an access token to the HeaderInterceptor. I would of course like this to be done during generation or at least be possible to give interceptors to the client on creation.

```
@ChopperApi()
abstract class ExampleSwagger extends ChopperService {
  static ExampleSwagger create(String accessToken, [ChopperClient client]) {
    if (client != null) {
      return _$ExampleSwagger(client);
    }

    final newClient = ChopperClient(
        services: [_$ExampleSwagger()],
        converter: JsonSerializableConverter(),
        baseUrl: 'https://petstore.swagger.io/v2',
        interceptors: [HeaderInterceptor(accessToken)]);
    return _$ExampleSwagger(newClient);
  }
```

**Comment by fryette** [comment]
Hey!
Glad to see you here!

You can create a client on your side and then pass the ready client to the generated class(ExampleSwagger).

You probably see, that in generated class we have
```
if(client!=null)
```

**Comment by FischerDaniel** [comment]
Thank you, this is exactly what I needed
