### ISSUE TITLE
Generate copy/copyWith methods

### ISSUE THREAD

**Issue by RomainFranceschini** [epam-cross-platform-lab/swagger-dart-code-generator#98]
Hi,

I was wondering what would be the best way to define copy/copyWith methods on the models generated from swagger. 

Ideally, they would be generated but it may be out of scope of this library. Maybe you have some pointers on how to use something like [copy_with_extension](https://pub.dev/packages/copy_with_extension) together with swagger-dart-code-generator.

Thanks for the amazing work!

**Comment by fryette** [comment]
I think we can add it.
Actually good idea

**Comment by Vovanella95** [comment]
@RomainFranceschini Please check this feature in latest version 1.4.6. We did not used external lib and implemented copyWith manually to not have external dependencies.

**Comment by RomainFranceschini** [comment]
@Vovanella95 fantastic ! Already bumped the version and it works like a charm. Thank you for the responsiveness.
