### ISSUE TITLE
problems with "-" on definitions 

### ISSUE THREAD

**Issue by fphilip** [epam-cross-platform-lab/swagger-dart-code-generator#99]
Hi
My old swagger file has a 
`#/definitions/account-address"`

when the generete build runs, the enums dart fils seem ok
_***.enums.swagger.dart**_
`enum AccountAddressType {`

But, the following file seems to just 'capitalize' the definition name, however in the phase of processing the enums that process seems to generate the names correctly ...
_***.swagger.dart**_
`String accountAddressTypeToJson(enums.Account-addressType accountAddressType) {`

**Comment by Vovanella95** [comment]
Hi, we will check it today and fix it ASAP

**Comment by Vovanella95** [comment]
@fphilip Issue is fixed. Please check latest version and let us know if something works bad! Thanks for highlighting issue!

**Comment by fphilip** [comment]
thanks.. works great!!!
